import { Tutorial } from '../types';

export const bifurcationIntroTutorial: Tutorial = {
  id: 'bifurcation-intro',
  title: '分岐理論入門',
  description: 'パラメータ変化による解の質的変化を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'パラメータが運命を変える',
      content: 'ODEのパラメータが変わると、平衡点の数や安定性が突然変化することがあります。\n\nこの質的変化が「分岐（bifurcation）」です。\n\n水が凍る、磁石が磁化する、人口が崩壊する…。分岐は自然の至る所に現れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bifurcation-intro-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'パラメータを変えて分岐を見よう',
      content: 'x\' = μx - x³ のパラメータ μ をスライダーで変えてみましょう。\n\nμ < 0、μ = 0、μ > 0 で平衡点の数と安定性がどう変わるか観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bifurcation-intro-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：サドルノード分岐',
      content: 'x\' = μ + x² はサドルノード分岐の典型例です。\n\nμ < 0：2つの平衡点（安定＋不安定）\nμ = 0：1つの平衡点（半安定）\nμ > 0：平衡点なし\n\nパラメータ μ が0を横切ると、平衡点が消滅します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：ピッチフォーク分岐',
      content: 'x\' = μx - x³ はピッチフォーク分岐の例です。\n\nμ ≤ 0：原点のみ安定\nμ > 0：原点が不安定化し、±√μ に2つの安定平衡点が出現\n\n対称性のある系で典型的に見られ、分岐図がピッチフォーク（熊手）の形をしています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'x\' = μ - x² で分岐が起きるのはどの μ の値か？',
        options: [
          { id: 'a', label: 'μ = -1', correct: false },
          { id: 'b', label: 'μ = 0', correct: true },
          { id: 'c', label: 'μ = 1', correct: false },
          { id: 'd', label: 'μ = 2', correct: false },
        ],
        explanation: 'μ > 0 のとき平衡点 x = ±√μ が存在し、μ < 0 では平衡点がありません。μ = 0 で2つの平衡点が合流して消滅するサドルノード分岐が起きます。',
      },
    },
    {
      id: 'alternate',
      title: 'ホップ分岐',
      content: '二次元系では「ホップ分岐」が重要です。\n\nパラメータが臨界値を横切ると、安定な平衡点がリミットサイクルに変わります。\n\n固有値の実部が0を横切るとき発生し、自励振動の発生メカニズムを説明します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '分岐理論はパラメータによる解の質的変化を分類します。\n\n・サドルノード分岐：平衡点の生成・消滅\n・ピッチフォーク分岐：対称性の破れ\n・ホップ分岐：リミットサイクルの出現\n\n物理・生物・工学の相転移を統一的に理解する枠組みです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bifurcation-intro-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
