import { Tutorial } from '../types';

export const chaosIntroTutorial: Tutorial = {
  id: 'chaos-intro',
  title: 'カオス入門',
  description: '決定論的カオスの基本概念を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '決定論なのに予測不能',
      content: '完全に決定論的なODEが、初期条件のわずかな違いで全く異なる軌道を生むことがあります。\n\nこれが「カオス」です。ランダムではなく、法則に従いながらも長期予測が不可能になります。\n\nバタフライ効果として知られるこの現象を探りましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'chaos-intro-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '初期値敏感性を体験しよう',
      content: '近接する2つの初期条件からの軌道を比較します。\n\n最初は近い軌道が、時間とともに指数的に離れていく様子を観察してください。初期値の差を調整してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'chaos-intro-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：ローレンツ方程式',
      content: 'エドワード・ローレンツが発見した大気モデル：\n\nx\' = σ(y-x), y\' = rx-y-xz, z\' = xy-bz\n\nσ=10, b=8/3, r=28 でカオス的振る舞いを示します。\n\n解は「ストレンジアトラクター」と呼ばれる蝶のような形状に引き込まれます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：リアプノフ指数',
      content: 'カオスの定量的指標がリアプノフ指数 λ です。\n\n近接する2点の距離が e^(λt) のように変化するとき、λ > 0 がカオスの指標となります。\n\nローレンツ系の最大リアプノフ指数は約 0.9 で、隣接軌道が指数的に離れることを示しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'カオスが生じるために必要な連続力学系の次元は最低何次元か？',
        options: [
          { id: 'a', label: '1次元', correct: false },
          { id: 'b', label: '2次元', correct: false },
          { id: 'c', label: '3次元', correct: true },
          { id: 'd', label: '4次元', correct: false },
        ],
        explanation: 'ポアンカレ・ベンディクソンの定理により、2次元の連続力学系ではカオスは生じません。3次元以上が必要です。ローレンツ方程式は3次元です。',
      },
    },
    {
      id: 'alternate',
      title: 'ストレンジアトラクター',
      content: 'カオス的な軌道が引き込まれる集合を「ストレンジアトラクター」と呼びます。\n\nフラクタル構造を持ち、整数でない次元（フラクタル次元）を持つのが特徴です。\n\nローレンツアトラクターの次元は約 2.06 で、2次元と3次元の間にあります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'カオスは決定論的なODEが示す予測不能な振る舞いです。\n\n・初期値鋭敏性：わずかな差が指数的に拡大\n・ストレンジアトラクター：フラクタル構造\n・リアプノフ指数 λ > 0 がカオスの指標\n\n天気予報の限界から経済変動まで、カオスは現代科学の重要テーマです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'chaos-intro-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
