import { Tutorial } from '../types';

export const climateModelTutorial: Tutorial = {
  id: 'climate-model',
  title: '気候モデル入門',
  description: 'エネルギーバランスモデルで気候変動のODEを学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '地球の温度をODEで',
      content: '地球の平均温度はエネルギー収支で決まります。\n\nC dT/dt = S(1-α)/4 - εσT⁴\n\n入射太陽エネルギーと放射冷却のバランスが気温を決定します。\n\nこのシンプルなODEが気候科学の出発点です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'climate-model-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'アルベドを変えてみよう',
      content: 'アルベド（反射率）α を変えて、平衡温度がどう変わるか観察しましょう。\n\n氷が増えるとアルベドが上がり温度が下がる → さらに氷が増えるという正のフィードバックを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'climate-model-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：平衡温度の計算',
      content: 'dT/dt = 0 として平衡温度を求めます。\n\nS(1-α)/4 = εσT⁴\nT = [S(1-α)/(4εσ)]^(1/4)\n\nS = 1361 W/m², α = 0.3, ε = 1 とすると T ≈ 255K（-18°C）。\n\n温室効果なしでは地球は凍りついてしまいます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：氷-アルベドフィードバック',
      content: 'アルベドが温度に依存 α(T) すると、分岐が生じます。\n\n低温状態：α が高く、「雪球地球」\n高温状態：α が低く、温暖な気候\n\n中間状態は不安定で、サドルノード分岐の構造を持ちます。実際に約7億年前に雪球地球が起きたと考えられています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '温室効果を考慮しない場合の地球の平衡温度は約何度か？',
        options: [
          { id: 'a', label: '約15°C', correct: false },
          { id: 'b', label: '約0°C', correct: false },
          { id: 'c', label: '約-18°C', correct: true },
          { id: 'd', label: '約-50°C', correct: false },
        ],
        explanation: 'エネルギーバランスで計算すると約255K（-18°C）です。実際の地球は温室効果により約15°Cです。温室効果が約33°Cの温度上昇をもたらしています。',
      },
    },
    {
      id: 'alternate',
      title: 'ティッピングポイント',
      content: '気候システムには「ティッピングポイント（転換点）」が存在する可能性があります。\n\nODEの言葉では、これはサドルノード分岐やヒステリシスに対応します。\n\nある閾値を超えると不可逆的な変化が起き、元に戻すには大きな努力が必要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '気候モデルはODEの重要な応用分野です。\n\n・エネルギーバランスモデル：C dT/dt = 入射 - 放射\n・フィードバック機構が分岐を生む\n・ティッピングポイントは分岐点に対応\n\nODEの概念が地球規模の課題理解に役立ちます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'climate-model-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
