import { Tutorial } from '../types';

export const coupledOdeMatrixTutorial: Tutorial = {
  id: 'coupled-ode-matrix',
  title: '連立ODEと行列指数関数',
  description: '連立微分方程式を行列の固有値で解く方法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '複数の変数が絡み合う',
      content: '捕食者と被食者の個体数は互いに影響し合います。\n\nx\' = ax + by\ny\' = cx + dy\n\nこのような連立ODEはベクトル形式 X\' = AX で書け、行列 A の固有値・固有ベクトルで解けます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '行列の固有値を変えてみよう',
      content: '行列 A の成分を変えて固有値がどう変わるか、それが解にどう影響するか観察しましょう。\n\n実固有値、複素固有値、重複固有値の場合を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：対角化可能な場合',
      content: 'A = [[1,2],[0,3]] の固有値は λ₁ = 1, λ₂ = 3。\n\n固有ベクトルは v₁ = (1,0), v₂ = (1,1)。\n\nX(t) = c₁e^t(1,0) + c₂e^(3t)(1,1)\n\n行列指数関数 e^(At) = PD(t)P⁻¹ で表現できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：複素固有値の場合',
      content: 'A = [[0,-1],[1,0]] の固有値は λ = ±i（純虚数）。\n\n解は X(t) = c₁(cos t, sin t) + c₂(-sin t, cos t) で、原点の周りを回転する運動になります。\n\n実部が0でない場合は渦巻き状の運動になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'X\' = AX の解は形式的にどう書けるか？',
        options: [
          { id: 'a', label: 'X(t) = A^t X₀', correct: false },
          { id: 'b', label: 'X(t) = e^(At) X₀', correct: true },
          { id: 'c', label: 'X(t) = tA X₀', correct: false },
          { id: 'd', label: 'X(t) = (I + A)t X₀', correct: false },
        ],
        explanation: '連立ODE X\' = AX の解は行列指数関数を用いて X(t) = e^(At) X₀ と書けます。e^(At) = I + At + A²t²/2! + ... です。',
      },
    },
    {
      id: 'alternate',
      title: '行列指数関数の計算法',
      content: 'e^(At) の具体的な計算方法は主に3つあります。\n\n1. 対角化：A = PDP⁻¹ なら e^(At) = Pe^(Dt)P⁻¹\n2. ジョルダン標準形：対角化できない場合\n3. ケイリー・ハミルトンの定理：次数を下げる\n\nいずれも固有値の計算が出発点です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '連立ODEは行列の理論で体系的に解けます。\n\n・X\' = AX → X(t) = e^(At)X₀\n・固有値が解の定性的振る舞いを決定\n・実固有値：指数的増減、複素固有値：振動\n\n線形代数とODEの美しい融合です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
