import { Tutorial } from '../types';

export const dampedOscillationTutorial: Tutorial = {
  id: 'damped-oscillation',
  title: '減衰振動',
  description: '摩擦を含むバネの振動をODEで解析する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '振動はやがて止まる',
      content: '理想的なバネは永遠に振動しますが、現実には摩擦で振動が減衰します。\n\nmx\'\' + cx\' + kx = 0\n\nここで m は質量、c は減衰係数、k はバネ定数です。減衰の強さによって3つのパターンがあります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '減衰係数を変えてみよう',
      content: '減衰係数 c を変えて、振動の様子を観察しましょう。\n\nc が小さいと振動しながら減衰（不足減衰）、c が大きいと振動せず減衰（過減衰）、ちょうど臨界値で臨界減衰になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：不足減衰',
      content: 'c² < 4mk のとき、特性根は複素数 α ± βi です。\n\nx(t) = e^(αt)(C₁cos βt + C₂sin βt)\n\n振動しながら指数的に減衰します。αは減衰率、βは振動の角振動数です。\n\n日常で見るバネの振動はほとんどこのパターンです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：過減衰と臨界減衰',
      content: '過減衰（c² > 4mk）：x(t) = C₁e^(r₁t) + C₂e^(r₂t)\n振動せずゆっくり0に戻ります。\n\n臨界減衰（c² = 4mk）：x(t) = (C₁ + C₂t)e^(rt)\n最も速く0に戻るパターンで、ドアクローザーなどに応用されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '臨界減衰の条件はどれか？',
        options: [
          { id: 'a', label: 'c = 0', correct: false },
          { id: 'b', label: 'c² = 4mk', correct: true },
          { id: 'c', label: 'c² > 4mk', correct: false },
          { id: 'd', label: 'c = mk', correct: false },
        ],
        explanation: '特性方程式の判別式 c² - 4mk = 0 のとき臨界減衰です。重根を持ち、最も速く平衡に戻ります。',
      },
    },
    {
      id: 'alternate',
      title: 'エネルギーの観点',
      content: '減衰振動では力学的エネルギー E = (1/2)mv² + (1/2)kx² が時間とともに減少します。\n\ndE/dt = -cv² ≤ 0\n\n減衰項 cx\' が摩擦力として運動エネルギーを熱に変換しています。エネルギー散逸の速さは速度の二乗に比例します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '減衰振動は二階線形ODEの典型的な応用です。\n\n・不足減衰（c²<4mk）：振動しながら減衰\n・臨界減衰（c²=4mk）：最速で平衡に戻る\n・過減衰（c²>4mk）：振動せず緩やかに戻る\n\n制振設計や制御工学の基礎となる概念です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
