import { Tutorial } from '../types';

export const directionFieldTutorial: Tutorial = {
  id: 'direction-field',
  title: '方向場',
  description: '微分方程式の解を視覚的に理解する方向場を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '矢印が示す解の道筋',
      content: '微分方程式 dy/dx = f(x,y) は、平面上の各点で接線の傾きを定めます。\n\nこの傾きを小さな線分として描いたものが「方向場（direction field）」です。\n\n解曲線は方向場の矢印に沿って流れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '方向場を描いてみよう',
      content: 'dy/dx = x - y の方向場を観察しましょう。\n\n平面上の点をクリックすると、その点を通る解曲線が描かれます。方向場の矢印に沿って曲線が流れる様子を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：dy/dx = y',
      content: 'dy/dx = y の方向場を見ると、y > 0 では傾きが正、y < 0 では傾きが負です。\n\ny = 0 では傾きが0（水平）になります。\n\n解は y = Ce^x であり、方向場からも指数的な増減が読み取れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：dy/dx = -x/y',
      content: 'dy/dx = -x/y の方向場を観察すると、矢印が原点の周りを回っています。\n\n実際にこの方程式の解は x² + y² = C（円）です。\n\n方向場から解の定性的な形が分かるのがポイントです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'dy/dx = 0 となる点の集合をなんと呼ぶか？',
        options: [
          { id: 'a', label: '等傾線（ヌルクライン）', correct: true },
          { id: 'b', label: '平衡点', correct: false },
          { id: 'c', label: '特異点', correct: false },
          { id: 'd', label: '分岐点', correct: false },
        ],
        explanation: 'dy/dx = 0 となる点の集合はヌルクライン（等傾線）と呼ばれます。方向場で水平な線分が並ぶ曲線です。',
      },
    },
    {
      id: 'alternate',
      title: '等傾線の活用',
      content: '等傾線（isocline）は f(x,y) = c（一定値）を満たす曲線です。\n\n等傾線上の全ての点で方向場の傾きは同じ値 c を取ります。\n\nこれを利用すると、方向場を効率よく手描きでき、解の概形を素早く把握できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '方向場は微分方程式の解を視覚的に理解する強力な道具です。\n\n・各点の傾きを線分で描画\n・解曲線は方向場に沿って流れる\n・等傾線を使えば定性的な解析が可能\n\n解の公式が求められない場合でも、方向場から振る舞いを読み取れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
