import { Tutorial } from '../types';

export const doublePendulumTutorial: Tutorial = {
  id: 'double-pendulum',
  title: '二重振り子とカオス',
  description: '二重振り子に現れるカオス的運動を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '予測不能な振り子',
      content: '単振り子は規則的に揺れますが、振り子の先にもう1つ振り子をつけると劇的に変わります。\n\n二重振り子は決定論的なのに、わずかな初期条件の違いで全く異なる動きをします。\n\n4次元の位相空間に住むカオス系です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '二重振り子を動かしてみよう',
      content: '初期角度をわずかに変えた2つの二重振り子を並べて観察しましょう。\n\n最初は似た動きをしていますが、やがて全く異なる軌道を描きます。これがカオスの本質です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：運動方程式',
      content: '二重振り子の運動方程式はラグランジュ力学で導出されます。\n\nθ₁ と θ₂ の連立二階ODE（4つの一階ODEに変換）で記述されます。\n\n非線形な連成項 cos(θ₁-θ₂), sin(θ₁-θ₂) がカオスの源です。\n\nエネルギーは保存されるハミルトン系です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：ポアンカレ断面',
      content: '4次元の位相空間を直接可視化するのは困難です。\n\nポアンカレ断面：特定の条件（例：θ₂ = 0 を正方向に横切る時）でのθ₁, ω₁ をプロットします。\n\n規則的な運動は曲線上の点列、カオスは面上に散らばった点列として現れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '二重振り子のエネルギーはどうなるか？',
        options: [
          { id: 'a', label: '時間とともに増加する', correct: false },
          { id: 'b', label: '時間とともに減少する', correct: false },
          { id: 'c', label: '保存される（摩擦なしの場合）', correct: true },
          { id: 'd', label: 'カオス的に変動する', correct: false },
        ],
        explanation: '二重振り子は摩擦がなければハミルトン系であり、全エネルギー（運動エネルギー＋位置エネルギー）は保存されます。カオスであってもエネルギーは一定です。',
      },
    },
    {
      id: 'alternate',
      title: 'KAMトーラスの崩壊',
      content: '小さなエネルギーでは二重振り子は準周期的に運動します（KAMトーラス上）。\n\nエネルギーを上げると、KAMトーラスが崩壊してカオス領域が広がります。\n\nKAM理論（コルモゴロフ-アルノルド-モーザー）は、この規則→カオスの遷移を記述する深い数学理論です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '二重振り子はカオスを示す最も身近な力学系です。\n\n・単純な構造から複雑な運動が生まれる\n・初期値鋭敏性によりカオス的\n・ポアンカレ断面で高次元の構造を可視化\n\nカオスは特殊ではなく、自然界に遍在する現象です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
