import { Tutorial } from '../types';

export const equilibriumStabilityTutorial: Tutorial = {
  id: 'equilibrium-stability',
  title: '平衡点と安定性',
  description: '平衡点の分類と安定性判定法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '動かない点はどこか？',
      content: 'x\' = f(x) で f(x*) = 0 となる点 x* が平衡点です。\n\n平衡点は「ボールが止まる場所」のようなもの。谷底は安定、山頂は不安定です。\n\n安定性の判定は、摂動を加えたときに元に戻るかどうかで決まります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '平衡点に摂動を加えてみよう',
      content: '平衡点の近くに初期値を置いて、解がどう振る舞うか観察しましょう。\n\n安定な平衡点と不安定な平衡点の違いを体感してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：一次元の安定性判定',
      content: 'x\' = f(x) の平衡点 x* での安定性は f\'(x*) の符号で判定できます。\n\nf\'(x*) < 0：安定（摂動が減衰）\nf\'(x*) > 0：不安定（摂動が増大）\nf\'(x*) = 0：高次の項で判定\n\n例：x\' = -x³ では x* = 0 で f\'(0) = 0 ですが安定です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：二次元の分類',
      content: '二次元系 X\' = AX の平衡点はヤコビ行列 A の固有値で分類されます。\n\n・安定結節点：実固有値が両方負\n・不安定結節点：実固有値が両方正\n・鞍点：実固有値が異符号\n・安定渦巻き：複素固有値の実部が負\n・中心：純虚数固有値',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ヤコビ行列の固有値が -2 ± 3i のとき、平衡点の種類は？',
        options: [
          { id: 'a', label: '安定渦巻き点', correct: true },
          { id: 'b', label: '不安定渦巻き点', correct: false },
          { id: 'c', label: '中心', correct: false },
          { id: 'd', label: '安定結節点', correct: false },
        ],
        explanation: '固有値の実部が -2 < 0 で虚部が ±3 ≠ 0 なので、軌道は原点に向かって渦巻く「安定渦巻き点」です。',
      },
    },
    {
      id: 'alternate',
      title: 'トレースと行列式による判定',
      content: '2×2行列 A のトレース τ = tr(A) と行列式 Δ = det(A) で平衡点を分類できます。\n\nΔ < 0：鞍点\nΔ > 0, τ < 0：安定（結節点 or 渦巻き）\nΔ > 0, τ > 0：不安定\nΔ > 0, τ = 0：中心\n\n固有値を直接計算しなくても分類可能です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '平衡点の安定性解析はODE理論の中核です。\n\n・平衡点：f(x*) = 0 となる点\n・一次元：f\'(x*) の符号で判定\n・二次元：ヤコビ行列の固有値で分類\n\n線形化による局所解析が基本的なアプローチです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
