import { Tutorial } from '../types';

export const eulerMethodTutorial: Tutorial = {
  id: 'euler-method',
  title: 'オイラー法',
  description: 'ODEの最も基本的な数値解法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '一歩ずつ進む',
      content: '解析的に解けないODEでも、数値的に近似解を求められます。\n\n最も単純な方法がオイラー法：y_{n+1} = y_n + h·f(x_n, y_n)\n\n方向場の矢印に沿って小さなステップを繰り返すだけです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ステップ幅を変えてみよう',
      content: 'オイラー法のステップ幅 h を変えて、近似の精度を観察しましょう。\n\nh が小さいほど正確ですが計算量が増えます。どの程度の h で十分な精度が得られるか確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：dy/dx = y の数値解',
      content: 'dy/dx = y, y(0) = 1 をオイラー法で解きます（厳密解は y = e^x）。\n\nh = 0.1：y(1) ≈ 2.594（誤差 4.6%）\nh = 0.01：y(1) ≈ 2.705（誤差 0.5%）\n\nオイラー法は1次精度なので、h を半分にすると誤差も約半分になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：安定性の問題',
      content: 'dy/dx = -10y を h = 0.25 で解くと、数値解が振動して発散します！\n\nオイラー法が安定な条件は |1 + hλ| < 1 です。λ = -10 なら h < 0.2 が必要。\n\n硬い方程式（stiff equation）では非常に小さな h が必要になり、実用上の問題になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'オイラー法の局所打ち切り誤差の次数はどれか？',
        options: [
          { id: 'a', label: 'O(h)', correct: false },
          { id: 'b', label: 'O(h²)', correct: true },
          { id: 'c', label: 'O(h³)', correct: false },
          { id: 'd', label: 'O(h⁴)', correct: false },
        ],
        explanation: 'オイラー法の局所打ち切り誤差は O(h²) です。1ステップあたり h² の誤差が、n = 1/h ステップ蓄積して大域誤差は O(h)（1次精度）になります。',
      },
    },
    {
      id: 'alternate',
      title: '改良オイラー法',
      content: '改良オイラー法（ホイン法）は精度を上げた手法です。\n\nk₁ = f(xₙ, yₙ)\nk₂ = f(xₙ + h, yₙ + hk₁)\ny_{n+1} = yₙ + h(k₁ + k₂)/2\n\n2次精度で、同じ h でもオイラー法より格段に正確です。ルンゲ・クッタ法への橋渡しになります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'オイラー法はODEの数値解法の出発点です。\n\n・y_{n+1} = yₙ + h·f(xₙ, yₙ)\n・1次精度（大域誤差 O(h)）\n・ステップ幅 h と安定性に注意\n\nシンプルですが数値解法の本質的な概念を含んでいます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
