import { Tutorial } from '../types';

export const exactEquationTutorial: Tutorial = {
  id: 'exact-equation',
  title: '完全微分方程式',
  description: 'ポテンシャル関数を利用した完全微分方程式の解法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'ポテンシャルが存在する方程式',
      content: 'M(x,y)dx + N(x,y)dy = 0 が完全微分方程式であるとは、ある関数 F(x,y) が存在して dF = Mdx + Ndy となることです。\n\nこのとき解は F(x,y) = C（等高線）で与えられます。\n\n完全性の条件は ∂M/∂y = ∂N/∂x です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '完全性を確認しよう',
      content: '与えられた方程式の ∂M/∂y と ∂N/∂x を計算し、完全かどうか判定してみましょう。\n\n式をタップして偏微分の計算結果を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：(2xy + 3)dx + (x² + 4y)dy = 0',
      content: 'M = 2xy + 3, N = x² + 4y とします。\n\n∂M/∂y = 2x, ∂N/∂x = 2x → 完全！\n\nF = ∫M dx = x²y + 3x + g(y)\n∂F/∂y = x² + g\'(y) = x² + 4y → g(y) = 2y²\n\n解は x²y + 3x + 2y² = C です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：積分因子で完全化',
      content: '完全でない方程式も、適切な積分因子 μ を掛けると完全になることがあります。\n\nydx - xdy = 0 は ∂M/∂y = 1 ≠ ∂N/∂x = -1 で完全ではありません。\n\nμ = 1/y² を掛けると (1/y)dx - (x/y²)dy = 0 となり、d(x/y) = 0 で解は x/y = C です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '完全微分方程式の判定条件はどれか？',
        options: [
          { id: 'a', label: 'M = N', correct: false },
          { id: 'b', label: '∂M/∂y = ∂N/∂x', correct: true },
          { id: 'c', label: '∂M/∂x = ∂N/∂y', correct: false },
          { id: 'd', label: 'M + N = 0', correct: false },
        ],
        explanation: 'Mdx + Ndy = 0 が完全であるための必要十分条件は ∂M/∂y = ∂N/∂x です。これはポテンシャル関数の混合偏微分の等しさに対応します。',
      },
    },
    {
      id: 'alternate',
      title: '幾何学的な解釈',
      content: '完全微分方程式の解 F(x,y) = C は等高線（レベルセット）です。\n\nベクトル場 (M, N) は等高線に直交する勾配ベクトルに対応します。\n\n完全性の条件 ∂M/∂y = ∂N/∂x は、ベクトル場が「保存的」であることと同値です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '完全微分方程式はポテンシャル関数で解けます。\n\n・判定条件：∂M/∂y = ∂N/∂x\n・解法：F を構成して F(x,y) = C\n・完全でなくても積分因子で完全化できる場合がある\n\n保存力の力学やポテンシャル理論と深く関係しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
