import { Tutorial } from '../types';

export const exponentialGrowthDecayTutorial: Tutorial = {
  id: 'exponential-growth-decay',
  title: '指数増加と指数減衰',
  description: '指数関数で記述される増加・減衰現象をODEの観点から学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '増えるか減るか',
      content: '細菌の増殖、放射性崩壊、銀行の複利…。\n\nこれらはすべて dy/dt = ky という同じODEで記述できます。\n\nk > 0 なら指数増加、k < 0 なら指数減衰です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'kの値を変えてみよう',
      content: 'dy/dt = ky の解 y = y₀e^(kt) を可視化します。\n\nスライダーで k の値を変え、増加と減衰の違いを観察しましょう。k = 0 のとき何が起こるかも確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：細菌の増殖',
      content: '細菌が1時間で2倍になるとします。\n\ndy/dt = ky, y(0) = 100 で y(1) = 200 なら：\n\n200 = 100e^k → k = ln2 ≈ 0.693\n\ny(t) = 100 · 2^t となり、10時間後には約102,400個です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：放射性崩壊と半減期',
      content: '放射性物質の崩壊は dy/dt = -λy で記述されます。\n\n半減期 T₁/₂ は y が半分になる時間で、T₁/₂ = ln2/λ です。\n\n炭素14の半減期は約5730年。考古学の年代測定に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '半減期が10年の物質が最初100gあるとき、20年後には何gか？',
        options: [
          { id: 'a', label: '50g', correct: false },
          { id: 'b', label: '25g', correct: true },
          { id: 'c', label: '10g', correct: false },
          { id: 'd', label: '0g', correct: false },
        ],
        explanation: '10年で半分の50g、さらに10年で半分の25gになります。y = 100 · (1/2)^(20/10) = 25g です。',
      },
    },
    {
      id: 'alternate',
      title: '倍増時間と半減期',
      content: '指数増加では「倍増時間」t₂ = ln2/k が重要な指標です。\n\n指数減衰では「半減期」T₁/₂ = ln2/|k| が対応します。\n\nどちらも k の大きさの逆数に比例し、変化の速さを直感的に表します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '指数増加・減衰は最も基本的なODEモデルです。\n\n・dy/dt = ky → y = y₀e^(kt)\n・k > 0：指数増加（倍増時間 = ln2/k）\n・k < 0：指数減衰（半減期 = ln2/|k|）\n\n自然界の多くの現象がこの単純なモデルで記述できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
