import { Tutorial } from '../types';

export const firstOrderLinearTutorial: Tutorial = {
  id: 'first-order-linear',
  title: '一階線形ODE',
  description: '積分因子を用いた一階線形ODEの解法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '積分因子の魔法',
      content: 'dy/dx + P(x)y = Q(x) の形の一階線形ODEは、積分因子 μ(x) = e^(∫P(x)dx) を掛けることで解けます。\n\n左辺が d/dx[μy] の形にまとまり、両辺を積分するだけで解が得られます。\n\nこの手法は非常に汎用的です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '積分因子を体験しよう',
      content: 'dy/dx + 2y = e^(-x) に積分因子を掛ける過程を順番に確認しましょう。\n\n各ステップをタップして進め、式がどう変形されるか体験してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：dy/dx + 2y = e^(-x)',
      content: 'P(x) = 2 なので μ = e^(2x)。両辺に掛けると：\n\nd/dx[e^(2x)y] = e^(2x) · e^(-x) = e^x\n\ne^(2x)y = e^x + C → y = e^(-x) + Ce^(-2x)\n\n積分因子により一度の積分で解が求まります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：dy/dx - y/x = x',
      content: 'P(x) = -1/x なので μ = e^(-ln|x|) = 1/x。両辺に掛けると：\n\nd/dx[y/x] = 1\n\ny/x = x + C → y = x² + Cx\n\nP(x) が定数でなくても同じ手順で解けます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'dy/dx + 3y = 0 の積分因子 μ(x) はどれか？',
        options: [
          { id: 'a', label: 'e^(3x)', correct: true },
          { id: 'b', label: 'e^(-3x)', correct: false },
          { id: 'c', label: '3x', correct: false },
          { id: 'd', label: 'e^(x/3)', correct: false },
        ],
        explanation: 'P(x) = 3 なので μ = e^(∫3dx) = e^(3x) です。',
      },
    },
    {
      id: 'alternate',
      title: '定数変化法との関連',
      content: '一階線形ODEは「定数変化法」でも解けます。\n\nまず同次方程式 dy/dx + P(x)y = 0 の解 y_h = Ce^(-∫P dx) を求め、C を x の関数 C(x) に置き換えて元の方程式に代入します。\n\n積分因子法と本質的に同じ結果が得られます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '一階線形ODEは積分因子法で体系的に解けます。\n\n・標準形：dy/dx + P(x)y = Q(x)\n・積分因子：μ = e^(∫P(x)dx)\n・解の公式：y = (1/μ)∫μQ dx + C/μ\n\n多くの物理・工学の問題がこの形に帰着されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
