import { Tutorial } from '../types';

export const forcedResonanceTutorial: Tutorial = {
  id: 'forced-resonance',
  title: '強制振動と共振',
  description: '外力を受ける振動系と共振現象を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '橋が崩れる理由',
      content: 'タコマナローズ橋の崩壊は共振の怖さを示す有名な例です。\n\nmx\'\' + cx\' + kx = F₀cos(ωt)\n\n外力の振動数 ω が系の固有振動数に近づくと、振幅が急激に大きくなります。これが共振です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'forced-resonance-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '外力の振動数を変えてみよう',
      content: '外力の角振動数 ω をスライダーで変化させましょう。\n\n固有振動数 ω₀ = √(k/m) に近づくにつれて振幅がどう変わるか観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'forced-resonance-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：共振曲線',
      content: '定常状態の振幅は A(ω) = F₀ / √((k - mω²)² + (cω)²) です。\n\n減衰がない場合（c = 0）、ω = ω₀ で振幅が無限大になります。\n\n減衰がある場合、振幅は有限ですがピークを持ちます。これが共振曲線です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：ビートと過渡応答',
      content: 'ω ≈ ω₀ で減衰がない場合、解は2つの近い振動数の合成になります。\n\nx(t) ≈ (2F₀/m(ω₀²-ω²)) sin((ω₀-ω)t/2) cos((ω₀+ω)t/2)\n\nゆっくりした包絡線（ビート）と速い振動が重なる現象が観察されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '減衰のない系で共振が起きるのはどの条件か？',
        options: [
          { id: 'a', label: 'ω = 0', correct: false },
          { id: 'b', label: 'ω = ω₀（固有振動数）', correct: true },
          { id: 'c', label: 'ω = 2ω₀', correct: false },
          { id: 'd', label: 'ω → ∞', correct: false },
        ],
        explanation: '外力の振動数 ω が固有振動数 ω₀ = √(k/m) に一致するとき、減衰なしでは振幅が無限大になる共振が起きます。',
      },
    },
    {
      id: 'alternate',
      title: 'Q値と帯域幅',
      content: '共振の鋭さを表す指標が Q 値（Quality factor）です。\n\nQ = ω₀m/c = √(mk)/c\n\nQ が大きいほど共振ピークが鋭く、帯域幅 Δω ≈ ω₀/Q が狭くなります。\n\nラジオのチューニングや楽器の音色に関わる重要な概念です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '強制振動と共振はODEの重要な応用です。\n\n・外力 F₀cos(ωt) による定常振動\n・ω ≈ ω₀ で共振（振幅最大）\n・減衰が共振の鋭さ（Q値）を決定\n\n構造物の安全設計から楽器の設計まで、共振の理解は不可欠です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'forced-resonance-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
