import { Tutorial } from '../types';

export const laplaceSolveOdeTutorial: Tutorial = {
  id: 'laplace-solve-ode',
  title: 'ラプラス変換で解くODE',
  description: 'ラプラス変換を用いたODEの解法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '微分を代数に変える',
      content: 'ラプラス変換 L{f(t)} = ∫₀^∞ f(t)e^(-st) dt は微分方程式を代数方程式に変換します。\n\nL{y\'} = sY(s) - y(0) という性質により、微分が s の掛け算に置き換わります。\n\n初期条件が自然に組み込まれるのも大きな利点です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-solve-ode-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '変換の流れを体験しよう',
      content: 'y\'\' + 4y = 0, y(0) = 1, y\'(0) = 0 をラプラス変換で解く過程を順にたどりましょう。\n\n各ステップをタップして変換→代数操作→逆変換の流れを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-solve-ode-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：y\'\' + 4y = 0',
      content: 'ラプラス変換すると：\n\ns²Y - s·1 - 0 + 4Y = 0\n(s² + 4)Y = s\nY(s) = s/(s² + 4)\n\n逆変換で y(t) = cos(2t) を得ます。\n\n特性方程式を使った方法と同じ結果ですが、初期条件の処理が自動的です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：不連続な外力',
      content: 'y\' + y = u(t-1)（単位ステップ）のような不連続な入力も扱えます。\n\nL{u(t-a)} = e^(-as)/s を使い：\n\n(s+1)Y = e^(-s)/s → Y = e^(-s)/(s(s+1))\n\n部分分数分解と推移定理で逆変換できます。通常の方法では難しい問題もラプラス変換なら扱えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'L{y\'(t)} はどれか？（y(0) = a とする）',
        options: [
          { id: 'a', label: 'sY(s) + a', correct: false },
          { id: 'b', label: 'sY(s) - a', correct: true },
          { id: 'c', label: 'Y(s)/s', correct: false },
          { id: 'd', label: 's²Y(s)', correct: false },
        ],
        explanation: 'ラプラス変換の微分公式より L{y\'} = sY(s) - y(0) = sY(s) - a です。',
      },
    },
    {
      id: 'alternate',
      title: '伝達関数との関連',
      content: 'ラプラス変換で定義される伝達関数 H(s) = Y(s)/U(s) はシステムの入出力関係を表します。\n\nH(s) の極が安定性を、零点が応答の形を決めます。\n\n制御工学ではこの伝達関数が中心的な役割を果たします。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ラプラス変換はODEを代数的に解く強力な手法です。\n\n・微分 → s の掛け算に変換\n・初期条件が自動的に組み込まれる\n・不連続入力やインパルスも扱える\n\n制御工学・信号処理の必須ツールです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-solve-ode-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
