import { Tutorial } from '../types';

export const limitCycleTutorial: Tutorial = {
  id: 'limit-cycle',
  title: 'リミットサイクル',
  description: '孤立した周期軌道であるリミットサイクルを学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '自律的な振動',
      content: '心臓の鼓動、ホタルの点滅、経済の景気循環…。\n\n外力なしに自発的に振動する系は「リミットサイクル」を持ちます。\n\n初期条件によらず同じ周期軌道に引き込まれる、非線形特有の現象です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'limit-cycle-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'リミットサイクルへの収束を見よう',
      content: '様々な初期値から出発する軌道を描いてみましょう。\n\n内側からも外側からもリミットサイクルに引き込まれることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'limit-cycle-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：ファン・デル・ポル振動子',
      content: 'x\'\' - μ(1-x²)x\' + x = 0 はファン・デル・ポル方程式です。\n\n|x| < 1 ではエネルギーが注入され、|x| > 1 では散逸します。\n\nこのバランスにより安定なリミットサイクルが生まれます。μ が大きいほど弛緩振動になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：ポアンカレ・ベンディクソンの定理',
      content: '平面力学系で、有界な正の半軌道が平衡点を含まないなら、ω極限集合はリミットサイクルです。\n\nこれがポアンカレ・ベンディクソンの定理で、リミットサイクルの存在を保証する強力な結果です。\n\n三次元以上ではこの定理は成り立たず、カオスが生じ得ます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'リミットサイクルが線形系では存在しない理由は？',
        options: [
          { id: 'a', label: '線形系は振動しないから', correct: false },
          { id: 'b', label: '線形系の周期軌道は孤立しないから', correct: true },
          { id: 'c', label: '線形系は安定だから', correct: false },
          { id: 'd', label: '線形系にはエネルギーがないから', correct: false },
        ],
        explanation: '線形系の中心では無数の同心楕円（周期軌道の族）が存在しますが、孤立した周期軌道（リミットサイクル）にはなりません。リミットサイクルは非線形特有の現象です。',
      },
    },
    {
      id: 'alternate',
      title: '弛緩振動',
      content: 'ファン・デル・ポル方程式で μ が大きいとき、解は「弛緩振動」を示します。\n\nゆっくりした変化と急激な跳躍が交互に現れるパターンです。\n\n神経細胞の発火や心臓の拍動がこの弛緩振動で近似できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'リミットサイクルは非線形ODEに特有の自律振動です。\n\n・孤立した周期軌道に引き込まれる\n・ファン・デル・ポル方程式が代表例\n・ポアンカレ・ベンディクソンの定理で存在を保証\n\n生物学的リズムや電子回路で重要な役割を果たします。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'limit-cycle-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
