import { Tutorial } from '../types';

export const logisticEquationTutorial: Tutorial = {
  id: 'logistic-equation',
  title: 'ロジスティック方程式',
  description: '環境収容力を考慮した人口モデルを学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '無限に増え続けるのか？',
      content: '指数増加モデルでは人口が無限に増え続けます。現実にはそうなりません。\n\n食料・空間などの制約を「環境収容力 K」として導入したのがロジスティック方程式です。\n\ndy/dt = ry(1 - y/K)',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '初期値を変えてみよう',
      content: 'ロジスティック曲線の初期値 y₀ を変えてみましょう。\n\ny₀ < K なら S字型に増加、y₀ > K なら減少して K に収束します。どの初期値からでも最終的に K に近づくことを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：S字曲線',
      content: 'r = 1, K = 100, y(0) = 10 として解くと：\n\ny(t) = 100 / (1 + 9e^(-t))\n\n初期は指数的に増加し、y = K/2 = 50 付近で変曲点を持ち、その後は収容力 K = 100 に漸近します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：平衡点の安定性',
      content: 'ロジスティック方程式には2つの平衡点があります。\n\ny = 0：不安定平衡点（わずかな摂動で離れる）\ny = K：安定平衡点（摂動しても戻る）\n\nf(y) = ry(1-y/K) として f\'(0) = r > 0、f\'(K) = -r < 0 から安定性が分かります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ロジスティック方程式で人口増加率が最大となるのはどの時点か？',
        options: [
          { id: 'a', label: 'y = 0 のとき', correct: false },
          { id: 'b', label: 'y = K/2 のとき', correct: true },
          { id: 'c', label: 'y = K のとき', correct: false },
          { id: 'd', label: 't = 0 のとき', correct: false },
        ],
        explanation: 'dy/dt = ry(1-y/K) を y で微分して0とおくと y = K/2。これが変曲点であり、増加率が最大の点です。',
      },
    },
    {
      id: 'alternate',
      title: '離散ロジスティック写像',
      content: '連続のロジスティック方程式を離散化すると x_{n+1} = rx_n(1 - x_n) になります。\n\nr の値によって、定常状態→周期倍分岐→カオスへと遷移します。\n\n単純な方程式からカオスが生まれるという驚きの結果です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ロジスティック方程式は指数モデルの自然な拡張です。\n\n・dy/dt = ry(1-y/K)：環境収容力 K による制約\n・S字型の成長曲線\n・y = K は安定平衡点\n\n人口動態、疫学、マーケティングなど幅広い応用があります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
