import { Tutorial } from '../types';

export const lotkaVolterraTutorial: Tutorial = {
  id: 'lotka-volterra',
  title: 'ロトカ・ヴォルテラ方程式',
  description: '捕食者-被食者モデルの力学を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'ウサギとキツネ',
      content: '被食者（ウサギ）と捕食者（キツネ）の個体数は周期的に変動します。\n\nx\' = αx - βxy（被食者）\ny\' = -γy + δxy（捕食者）\n\nウサギが増えるとキツネが増え、キツネが増えるとウサギが減る。この相互作用が周期振動を生みます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'lotka-volterra-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '個体数変動を観察しよう',
      content: '初期個体数を変えて、被食者と捕食者の時間発展を観察しましょう。\n\n位相平面上の軌道が閉曲線を描くことを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'lotka-volterra-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：周期的振動',
      content: 'α=1, β=0.5, γ=1, δ=0.5 で計算すると、個体数は周期的に振動します。\n\n被食者のピーク → 捕食者のピーク → 被食者の谷 → 捕食者の谷\n\nこの順序の位相のずれが捕食者-被食者モデルの特徴です。\n\n保存量 V = δx - γln(x) + βy - αln(y) が存在します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：平衡点の解析',
      content: '平衡点は (0,0) と (γ/δ, α/β) の2つです。\n\n(0,0) は鞍点（不安定）。\n(γ/δ, α/β) での固有値は純虚数 ±i√(αγ) で、中心です。\n\nこの中心の周りに閉軌道の族が存在し、保存系であることを反映しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ロトカ・ヴォルテラ方程式で、被食者を大量に除去するとどうなるか？',
        options: [
          { id: 'a', label: '捕食者が増加する', correct: false },
          { id: 'b', label: '両種とも絶滅する', correct: false },
          { id: 'c', label: '振動の振幅が変わるが周期的振動は続く', correct: true },
          { id: 'd', label: '系が平衡に達する', correct: false },
        ],
        explanation: 'ロトカ・ヴォルテラ方程式は保存系なので、初期条件を変えても解は閉軌道を描きます。除去は初期値の変更に相当し、別の閉軌道に移るだけです。',
      },
    },
    {
      id: 'alternate',
      title: 'ヴォルテラの原理',
      content: 'アドリア海で第一次世界大戦中に漁獲が減ったとき、捕食魚が増えた観測があります。\n\nヴォルテラの原理：両種を一律に間引くと、被食者が有利になり捕食者は不利になる。\n\n農薬の過剰使用が害虫を増やす逆説もこの原理で説明できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ロトカ・ヴォルテラ方程式は生態学の基本モデルです。\n\n・被食者-捕食者の周期的共存\n・位相平面上の閉軌道\n・保存量の存在\n\nシンプルなモデルから生態系の本質的な振る舞いが見えてきます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'lotka-volterra-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
