import { Tutorial } from '../types';

export const lyapunovStabilityTutorial: Tutorial = {
  id: 'lyapunov-stability',
  title: 'リアプノフの安定性',
  description: 'リアプノフ関数を用いた安定性解析を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'エネルギーで安定性を証明する',
      content: '線形化では判定できない安定性も、リアプノフ関数を使えば証明できます。\n\n物理的には「エネルギーが減少し続ければ系は安定」という直観です。\n\nV(x) > 0 かつ V\'(x) ≤ 0 ならば平衡点は安定です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'リアプノフ関数の等高線を見よう',
      content: 'リアプノフ関数 V(x,y) の等高線と軌道を重ねて表示します。\n\n軌道が V の等高線を内側に横切る（V が減少する）ことを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：単純な安定性証明',
      content: 'x\' = -x³, y\' = -y³ の原点の安定性を示します。\n\nV(x,y) = x² + y² とすると：\nV\' = 2x(-x³) + 2y(-y³) = -2(x⁴ + y⁴) < 0（原点以外）\n\nV > 0 かつ V\' < 0 なので、原点は漸近安定です。線形化では f\'(0) = 0 で判定不能でした。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：不安定性の証明',
      content: 'x\' = x³ の原点が不安定であることを示します。\n\nV(x) = x² とすると V\' = 2x · x³ = 2x⁴ > 0（x ≠ 0）\n\nV が増加するので不安定です。\n\nリアプノフの方法は安定性だけでなく不安定性の証明にも使えます（チェタエフの定理）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'リアプノフ関数 V が V > 0 かつ V\' < 0 を満たすとき、平衡点は？',
        options: [
          { id: 'a', label: '安定だが漸近安定とは限らない', correct: false },
          { id: 'b', label: '漸近安定', correct: true },
          { id: 'c', label: '不安定', correct: false },
          { id: 'd', label: '判定不能', correct: false },
        ],
        explanation: 'V > 0（正定値）かつ V\' < 0（負定値）のとき、平衡点は漸近安定です。V\' ≤ 0 なら安定（漸近安定とは限らない）です。',
      },
    },
    {
      id: 'alternate',
      title: 'ラサールの不変性原理',
      content: 'V\' ≤ 0（半負定値）でも漸近安定を示せる場合があります。\n\nラサールの不変性原理：V\' = 0 となる集合の中で最大の不変集合が平衡点だけなら漸近安定。\n\n減衰振動 x\'\' + cx\' + x = 0 でエネルギー V = x² + v²、V\' = -2cv² ≤ 0 の場合に有用です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'リアプノフの方法は非線形ODEの安定性を解析する強力な手法です。\n\n・V > 0, V\' ≤ 0：安定\n・V > 0, V\' < 0：漸近安定\n・解を求めずに安定性を証明できる\n\n制御理論や非線形力学で広く使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
