import { Tutorial } from '../types';

export const neuronModelTutorial: Tutorial = {
  id: 'neuron-model',
  title: 'ニューロンモデル',
  description: '神経細胞の発火をODEでモデル化する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '脳の電気信号',
      content: '神経細胞は電気的パルス（活動電位）で情報を伝達します。\n\n膜電位 V の変化は C dV/dt = I - g(V)(V - E) という形のODEで記述できます。\n\nこの方程式はイオンチャネルの開閉ダイナミクスを反映しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '刺激電流を変えてみよう',
      content: '入力電流 I の大きさを変えて、ニューロンの応答を観察しましょう。\n\n閾値以下では発火せず、閾値を超えると活動電位が生じます。電流を増やすと発火頻度が変わることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：ホジキン・ハクスレーモデル',
      content: 'ホジキンとハクスレーは1952年にイカの巨大軸索を用いて活動電位のモデルを構築しました。\n\nC dV/dt = I - gNa m³h(V-ENa) - gK n⁴(V-EK) - gL(V-EL)\n\n4つの変数 (V, m, h, n) の連立ODEで、Na⁺・K⁺チャネルの動態を記述します。ノーベル医学生理学賞を受賞した研究です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：フィッツヒュー・南雲モデル',
      content: 'ホジキン・ハクスレーモデルを簡略化したのがフィッツヒュー・南雲モデルです。\n\nv\' = v - v³/3 - w + I\nw\' = ε(v + a - bw)\n\n2変数でニューロンの本質的な振る舞い（興奮性、発火、弛緩振動）を再現します。ファン・デル・ポル方程式の変形です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ニューロンの「全か無かの法則」をODEの観点で説明すると？',
        options: [
          { id: 'a', label: '線形応答', correct: false },
          { id: 'b', label: '閾値を超えるとリミットサイクルに乗る', correct: true },
          { id: 'c', label: 'カオス的振る舞い', correct: false },
          { id: 'd', label: '指数減衰', correct: false },
        ],
        explanation: '刺激が閾値以下では静止状態（安定平衡点）に留まり、閾値を超えると大きな軌道（リミットサイクルや興奮軌道）に乗ります。これが「全か無かの法則」のODE的解釈です。',
      },
    },
    {
      id: 'alternate',
      title: '発火パターンの多様性',
      content: 'ニューロンの発火パターンは驚くほど多様です。\n\n・トニック発火：定常的な繰り返し\n・バースト発火：群発と休止の繰り返し\n・混合モード振動：小さな振動と大きなスパイクの交互\n\nこれらはすべてODEの分岐理論（ホップ分岐、同次クリニック分岐等）で説明できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ニューロンモデルはODEの生物学的応用の傑作です。\n\n・膜電位の変化をODEで記述\n・ホジキン・ハクスレー：詳細な4変数モデル\n・フィッツヒュー・南雲：簡略化2変数モデル\n\n非線形力学の概念（閾値、リミットサイクル、分岐）が神経科学と結びつきます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
