import { Tutorial } from '../types';

export const nonlinearLinearizationTutorial: Tutorial = {
  id: 'nonlinear-linearization',
  title: '非線形ODEと線形化',
  description: '非線形ODEを平衡点の近傍で線形化する方法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '曲がった世界を真っ直ぐにする',
      content: '非線形ODE x\' = f(x) は一般に解の公式がありません。\n\nしかし平衡点 x* の近傍では、テイラー展開により f(x) ≈ f(x*) + Df(x*)(x - x*) と線形近似できます。\n\nこの「線形化」が局所解析の第一歩です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nonlinear-linearization-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '線形化の精度を確認しよう',
      content: '非線形系と線形化した系の軌道を比較しましょう。\n\n平衡点の近くでは一致し、遠くでは乖離することを確認してください。初期値の距離を変えて精度を観察しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nonlinear-linearization-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：振り子の線形化',
      content: '振り子の方程式 θ\'\' + (g/L)sinθ = 0 は非線形です。\n\nθ ≈ 0 の近くで sinθ ≈ θ と近似すると：\nθ\'\' + (g/L)θ = 0（単振動）\n\nこの線形化は小さな振れ角では正確ですが、大きな角度では誤差が生じます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：ヤコビ行列の計算',
      content: 'x\' = x - xy, y\' = -y + xy の平衡点 (1,1) でのヤコビ行列は：\n\nJ = [[1-y, -x], [y, -1+x]] = [[0, -1], [1, 0]] （(1,1)で評価）\n\n固有値は ±i（中心）。ただし非線形項の影響で真の軌道は渦巻きになる可能性があります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '線形化で安定性が正しく判定できないのはどの場合か？',
        options: [
          { id: 'a', label: '固有値が正の実部を持つとき', correct: false },
          { id: 'b', label: '固有値が負の実部を持つとき', correct: false },
          { id: 'c', label: '固有値の実部が0のとき', correct: true },
          { id: 'd', label: '固有値が実数のとき', correct: false },
        ],
        explanation: '固有値の実部が0のとき（中心など）、非線形項が安定性を左右するため線形化だけでは判定できません。ハートマン・グロブマンの定理の除外ケースです。',
      },
    },
    {
      id: 'alternate',
      title: 'ハートマン・グロブマンの定理',
      content: 'ハートマン・グロブマンの定理：ヤコビ行列の固有値の実部がすべて非零なら、非線形系と線形化系は平衡点の近傍で位相的に同値です。\n\nつまり軌道の定性的な形が一致します。\n\nこの定理が線形化による安定性判定の理論的根拠です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '線形化は非線形ODEの局所解析の基本手法です。\n\n・平衡点でのヤコビ行列を計算\n・固有値から局所的な安定性を判定\n・実部が非零なら線形化で正しく判定可能\n\nリアプノフ法と組み合わせることで、より完全な解析が可能になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nonlinear-linearization-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
