import { Tutorial } from '../types';

export const odeBasicsSummaryTutorial: Tutorial = {
  id: 'ode-basics-summary',
  title: 'ODEの基本まとめ',
  description: 'ODEの基本的な概念と解法を総復習する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '学んだことを振り返ろう',
      content: 'ここまでODEの基本を幅広く学んできました。\n\n変数分離法から始まり、線形ODE、位相平面、安定性、分岐、カオスまで。\n\nこれらの概念を整理し、全体像を把握しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '概念マップを探索しよう',
      content: 'ODEの概念マップをインタラクティブに探索しましょう。\n\n各ノードをタップして、概念間のつながりを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '解法の体系',
      content: '一階ODE解法の体系：\n\n・変数分離法：dy/dx = g(x)h(y)\n・積分因子法：dy/dx + P(x)y = Q(x)\n・完全微分方程式：Mdx + Ndy = 0\n\n二階以上：特性方程式、未定係数法、ラプラス変換\n\n適切な解法を選ぶ目が重要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '定性理論の体系',
      content: '解の公式が得られなくても、定性的理論で振る舞いを理解できます。\n\n・方向場と位相平面：視覚的理解\n・平衡点と安定性：局所解析\n・リアプノフ関数：大域的安定性\n・分岐：パラメータによる質的変化\n・カオス：予測不能性',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'dy/dx + 2xy = x を解くのに最も適切な方法は？',
        options: [
          { id: 'a', label: '変数分離法', correct: false },
          { id: 'b', label: '積分因子法', correct: true },
          { id: 'c', label: '特性方程式', correct: false },
          { id: 'd', label: 'ラプラス変換', correct: false },
        ],
        explanation: 'dy/dx + P(x)y = Q(x) の形なので積分因子法が適切です。P(x) = 2x, Q(x) = x で μ = e^(x²) です。',
      },
    },
    {
      id: 'alternate',
      title: '数値解法の役割',
      content: '解析的に解けないODEは数値解法で近似します。\n\nオイラー法、ルンゲ・クッタ法などがあり、コンピュータの力で複雑な系もシミュレーションできます。\n\n解析的理解と数値計算の両輪が現代のODE研究の基盤です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ODEの基本を総復習しました。\n\n・解法：変数分離、積分因子、特性方程式、ラプラス変換\n・定性理論：平衡点、安定性、分岐、カオス\n・視覚化：方向場、位相平面\n\nこれらの基礎の上に、応用編のチュートリアルが続きます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
