import { Tutorial } from '../types';

export const odeOverviewTutorial: Tutorial = {
  id: 'ode-overview',
  title: 'ODEの全体像',
  description: '常微分方程式の全分野を俯瞰し、学習の道筋を示す',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '変化の科学の全貌',
      content: 'ここまで30のトピックを通じてODEの世界を旅してきました。\n\n基本解法→定性理論→応用→数値解法と、広大な分野を横断しました。\n\nこの最終チュートリアルで全体像を俯瞰しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ode-overview-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ODE分野マップを探索しよう',
      content: 'ODEの各分野の関係を示すマップをインタラクティブに探索しましょう。\n\n各ノードをタップして、分野間のつながりと各分野の要点を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ode-overview-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '理論の柱',
      content: 'ODEの理論的柱は3つあります。\n\n1. 存在と一意性：ピカール・リンデレフの定理\n2. 線形理論：重ね合わせ原理、行列指数関数\n3. 定性理論：位相平面、安定性、分岐、カオス\n\nこれらが互いに補い合い、ODEの深い理解を支えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '応用の広がり',
      content: 'ODEの応用分野は驚くほど広大です。\n\n・物理学：力学、電磁気学、量子力学\n・生物学：人口動態、生態系、神経科学\n・工学：制御理論、回路設計、構造解析\n・社会科学：経済モデル、疫学\n・地球科学：気候モデル、地震学\n\nODEはあらゆる科学の共通言語です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ODEとPDE（偏微分方程式）の主な違いは何か？',
        options: [
          { id: 'a', label: 'ODEは線形、PDEは非線形', correct: false },
          { id: 'b', label: 'ODEは一変数の導関数、PDEは多変数の偏導関数を含む', correct: true },
          { id: 'c', label: 'ODEは解析的、PDEは数値的にしか解けない', correct: false },
          { id: 'd', label: 'ODEは物理学、PDEは工学で使われる', correct: false },
        ],
        explanation: 'ODEは独立変数が1つ（例：時間 t）で通常の導関数を含み、PDEは独立変数が複数（例：時間と空間）で偏導関数を含みます。',
      },
    },
    {
      id: 'alternate',
      title: 'さらなる学びへ',
      content: 'ODEの先には豊かな数学の世界が広がっています。\n\n・偏微分方程式（PDE）：波動、拡散、流体\n・確率微分方程式（SDE）：金融、統計力学\n・遅延微分方程式（DDE）：制御、生物学\n・微分幾何学：多様体上のODE\n\nODEの基礎がこれらすべての出発点です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ODEは変化を記述する数学の根幹です。\n\n・解法：変数分離、積分因子、特性方程式、ラプラス変換\n・定性理論：安定性、分岐、カオス\n・数値解法：オイラー法、ルンゲ・クッタ法\n・応用：物理、生物、工学、社会科学\n\nODEの理解は科学リテラシーの核心です。学び続けましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ode-overview-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
