import { Tutorial } from '../types';

export const pendulumMotionTutorial: Tutorial = {
  id: 'pendulum-motion',
  title: '振り子の運動',
  description: '単振り子の非線形ODEを解析する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'ガリレオの発見',
      content: 'ガリレオは教会のシャンデリアの揺れから振り子の等時性を発見しました。\n\nθ\'\' + (g/L)sinθ = 0\n\nこの方程式は sinθ のため非線形です。小さな振れ角の近似（sinθ ≈ θ）を超えた振る舞いを探りましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '振れ角を大きくしてみよう',
      content: '初期角度を変えて、振り子の運動を観察しましょう。\n\n小さな角度では等時的（周期一定）ですが、大きな角度では周期が長くなることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：位相平面上の振り子',
      content: '(θ, θ\') 平面で振り子の軌道を見ると：\n\n・小さなエネルギー：原点周りの閉曲線（振動）\n・セパラトリクス：平衡点 (±π, 0) を結ぶ特別な軌道\n・大きなエネルギー：開曲線（回転運動）\n\nエネルギー E = θ\'²/2 - (g/L)cosθ で分類できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：楕円積分と厳密な周期',
      content: '非線形振り子の厳密な周期は楕円積分で表されます。\n\nT = 4√(L/g) K(sin(θ₀/2))\n\nK は第一種完全楕円積分です。\n\nθ₀ = 0 で T₀ = 2π√(L/g)（線形近似の周期）、θ₀ が大きくなると T は増加します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '振り子の倒立位置 θ = π はどのような平衡点か？',
        options: [
          { id: 'a', label: '安定結節点', correct: false },
          { id: 'b', label: '鞍点（不安定）', correct: true },
          { id: 'c', label: '中心', correct: false },
          { id: 'd', label: '安定渦巻き点', correct: false },
        ],
        explanation: 'θ = π（倒立位置）ではヤコビ行列の固有値が実数で異符号となり、鞍点です。わずかな摂動で倒れてしまう不安定な平衡点です。',
      },
    },
    {
      id: 'alternate',
      title: 'フーコーの振り子',
      content: 'フーコーの振り子は地球の自転を証明した有名な実験です。\n\n振動面が1日かけてゆっくり回転します。コリオリ力による効果で、回転角は緯度 φ に依存し、1日あたり 360°sinφ です。\n\nODEにコリオリ力項を加えることでモデル化できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '振り子はODEの古典的かつ豊かなテーマです。\n\n・非線形方程式 θ\'\' + (g/L)sinθ = 0\n・位相平面で振動・セパラトリクス・回転を分類\n・厳密な周期は楕円積分で表される\n\n単純に見えて深い数学が隠れた問題です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
