import { Tutorial } from '../types';

export const phasePlaneTutorial: Tutorial = {
  id: 'phase-plane',
  title: '位相平面解析',
  description: '二次元ODEの解を位相平面上で可視化する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '解の軌道を見る',
      content: '二次元連立ODE x\' = f(x,y), y\' = g(x,y) の解を (x(t), y(t)) として平面上にプロットすると「軌道」が描かれます。\n\nこれが位相平面（phase plane）解析です。\n\n時間の情報は失われますが、解の全体的な構造が見えてきます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'phase-plane-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '位相平面上の軌道を描こう',
      content: '位相平面上の点をクリックして、その初期値から出発する軌道を描いてみましょう。\n\n異なる初期値からの軌道がどのようなパターンを形成するか観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'phase-plane-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：単振動の位相平面',
      content: 'x\'\' + x = 0 を連立系 x\' = v, v\' = -x に変換します。\n\n位相平面上の軌道は原点を中心とする楕円（実際は円）です。\n\nエネルギー保存 E = x²/2 + v²/2 = 一定 がこの楕円を定義しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：鞍点',
      content: 'x\' = x, y\' = -y の位相平面では、x軸方向に離れ、y軸方向に近づく軌道が見られます。\n\n原点は「鞍点（saddle point）」と呼ばれる不安定な平衡点です。\n\n固有値が正と負の両方を持つとき、このパターンが現れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '行列の固有値が純虚数 ±βi のとき、位相平面の軌道はどのような形か？',
        options: [
          { id: 'a', label: '直線', correct: false },
          { id: 'b', label: '楕円（中心）', correct: true },
          { id: 'c', label: '螺旋', correct: false },
          { id: 'd', label: '双曲線', correct: false },
        ],
        explanation: '固有値が純虚数 ±βi のとき、軌道は原点を中心とする閉曲線（楕円）になります。原点は「中心（center）」と呼ばれます。',
      },
    },
    {
      id: 'alternate',
      title: 'ヌルクラインの利用',
      content: 'x\' = 0 となる曲線（x-ヌルクライン）と y\' = 0 となる曲線（y-ヌルクライン）の交点が平衡点です。\n\nヌルクラインは位相平面を領域に分割し、各領域での流れの方向を決定します。\n\n非線形系の解析にも有効な手法です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '位相平面解析は二次元ODEの強力な可視化手法です。\n\n・軌道は解 (x(t),y(t)) の平面上のパス\n・平衡点の種類：中心、渦巻き、鞍点、結節点\n・ヌルクラインで流れの構造を把握\n\n定性的理論の基盤となる考え方です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'phase-plane-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
