import { Tutorial } from '../types';

export const rlcCircuitTutorial: Tutorial = {
  id: 'rlc-circuit',
  title: 'RLC回路',
  description: '電気回路の振動をODEで解析する',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '電気のバネ',
      content: 'RLC回路は電気版のバネ・質量・ダンパー系です。\n\nLq\'\' + Rq\' + q/C = V(t)\n\nインダクタンス L（質量）、抵抗 R（摩擦）、キャパシタンス C（バネ）が対応します。\n\n力学と電気回路は同じODEで記述されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '回路パラメータを変えてみよう',
      content: 'R, L, C の値を変えて、電流の振る舞いを観察しましょう。\n\nR が小さい（低抵抗）と振動的、R が大きい（高抵抗）と非振動的になることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：自由振動（R=0）',
      content: 'R = 0 の LC 回路では Lq\'\' + q/C = 0 となります。\n\n解は q(t) = Q₀cos(ω₀t)、ω₀ = 1/√(LC)\n\nエネルギーがインダクタ（磁場）とキャパシタ（電場）の間を永遠に行き来します。\n\nこれは抵抗のないバネの単振動と同じです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：交流電源による共振',
      content: 'V(t) = V₀cos(ωt) を印加すると、ω = ω₀ = 1/√(LC) で共振します。\n\n共振時のインピーダンスは Z = R（最小）となり、電流が最大になります。\n\nラジオのチューニングは L または C を変えて共振周波数を調整する操作です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'RLC回路の固有振動数 ω₀ はどれか？',
        options: [
          { id: 'a', label: 'R/L', correct: false },
          { id: 'b', label: '1/√(LC)', correct: true },
          { id: 'c', label: '√(R/C)', correct: false },
          { id: 'd', label: 'L/R', correct: false },
        ],
        explanation: 'LC回路の固有振動数は ω₀ = 1/√(LC) です。バネ・質量系の ω₀ = √(k/m) に対応し、L が質量 m、1/C がバネ定数 k に対応します。',
      },
    },
    {
      id: 'alternate',
      title: '力学系とのアナロジー',
      content: 'RLC回路とバネ・質量・ダンパー系の対応：\n\n電荷 q ↔ 変位 x\n電流 I ↔ 速度 v\nインダクタンス L ↔ 質量 m\n抵抗 R ↔ 摩擦係数 c\n1/C ↔ バネ定数 k\n\nこのアナロジーにより、一方の知識が他方に転用できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'RLC回路は二階線形ODEの典型的な応用です。\n\n・Lq\'\' + Rq\' + q/C = V(t)\n・力学系と完全なアナロジー\n・共振周波数 ω₀ = 1/√(LC)\n\n電子工学から通信技術まで幅広く応用されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
