import { Tutorial } from '../types';

export const rungeKuttaTutorial: Tutorial = {
  id: 'runge-kutta',
  title: 'ルンゲ・クッタ法',
  description: '高精度なODE数値解法であるルンゲ・クッタ法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '精度と効率の両立',
      content: 'オイラー法は単純ですが精度が低く、実用にはより高精度な方法が必要です。\n\nルンゲ・クッタ法（RK4）は4つの傾きの重み付き平均を取ることで、4次精度を達成します。\n\n科学技術計算で最も広く使われるODE数値解法です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'RK4の精度を確認しよう',
      content: 'オイラー法とRK4の結果を同じステップ幅で比較しましょう。\n\nRK4が圧倒的に高精度であることを確認してください。ステップ幅を変えて精度の違いを観察しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：RK4のアルゴリズム',
      content: '古典的ルンゲ・クッタ法（RK4）：\n\nk₁ = f(xₙ, yₙ)\nk₂ = f(xₙ + h/2, yₙ + hk₁/2)\nk₃ = f(xₙ + h/2, yₙ + hk₂/2)\nk₄ = f(xₙ + h, yₙ + hk₃)\ny_{n+1} = yₙ + h(k₁ + 2k₂ + 2k₃ + k₄)/6\n\nシンプソン則に似た重み付けです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：精度の比較',
      content: 'dy/dx = y, y(0)=1 を h=0.1 で1ステップ計算：\n\nオイラー法：y(0.1) = 1.1（誤差 0.52%）\nRK4：y(0.1) = 1.10517083（誤差 0.0000001%）\n\nh を半分にすると、オイラーは誤差が半分、RK4は誤差が1/16になります（4次精度）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'RK4法の大域誤差の次数はどれか？',
        options: [
          { id: 'a', label: 'O(h²)', correct: false },
          { id: 'b', label: 'O(h³)', correct: false },
          { id: 'c', label: 'O(h⁴)', correct: true },
          { id: 'd', label: 'O(h⁵)', correct: false },
        ],
        explanation: 'RK4の局所打ち切り誤差は O(h⁵)、大域誤差は O(h⁴) です。4次精度なので h を半分にすると誤差は約1/16になります。',
      },
    },
    {
      id: 'alternate',
      title: '適応的ステップ制御',
      content: '実用的な数値積分では、誤差を監視してステップ幅を自動調整します。\n\nRK45（ドルマン・プリンス法）は4次と5次の解を同時に計算し、差を誤差推定に使います。\n\n解が急変する区間では h を小さく、緩やかな区間では h を大きくして効率を最大化します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'ルンゲ・クッタ法は高精度なODE数値解法です。\n\n・4つの傾きの重み付き平均\n・4次精度（大域誤差 O(h⁴)）\n・適応的ステップ制御で実用性向上\n\n科学技術計算の標準ツールとして不可欠です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
