import { Tutorial } from '../types';

export const secondOrderLinearTutorial: Tutorial = {
  id: 'second-order-linear',
  title: '二階線形ODE',
  description: '特性方程式を用いた二階線形ODEの解法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '加速度と力の関係',
      content: 'ニュートンの運動方程式 F = ma は二階ODE mx\'\' = F(t,x,x\') です。\n\nバネの振動、回路の電流、梁のたわみなど、物理の多くの問題が二階線形ODEに帰着されます。\n\nay\'\' + by\' + cy = 0 の解法を学びましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '特性根を変えてみよう',
      content: '特性方程式 ar² + br + c = 0 の係数 a, b, c を変えて、解の形がどう変わるか観察しましょう。\n\n判別式の符号によって、実数解・重解・複素解の3パターンがあります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：異なる実数根',
      content: 'y\'\' - 3y\' + 2y = 0 の特性方程式は r² - 3r + 2 = 0。\n\n(r-1)(r-2) = 0 → r = 1, 2\n\n一般解は y = C₁e^x + C₂e^(2x) です。\n\n2つの独立な指数関数の線形結合になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：複素根（振動解）',
      content: 'y\'\' + 4y = 0 の特性方程式は r² + 4 = 0 → r = ±2i。\n\n一般解は y = C₁cos(2x) + C₂sin(2x) です。\n\n複素根 α ± βi の場合、解は e^(αx)(cos βx, sin βx) の組み合わせになります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'y\'\' + 2y\' + y = 0 の特性方程式の根はどれか？',
        options: [
          { id: 'a', label: 'r = 1（重根）', correct: false },
          { id: 'b', label: 'r = -1（重根）', correct: true },
          { id: 'c', label: 'r = ±1', correct: false },
          { id: 'd', label: 'r = ±i', correct: false },
        ],
        explanation: 'r² + 2r + 1 = (r+1)² = 0 より r = -1（重根）。一般解は y = (C₁ + C₂x)e^(-x) です。',
      },
    },
    {
      id: 'alternate',
      title: '非同次方程式への拡張',
      content: 'ay\'\' + by\' + cy = f(x) の非同次方程式は「一般解 = 同次解 + 特殊解」で解きます。\n\n特殊解を求める方法として未定係数法や定数変化法があります。\n\n同次解が基盤となり、非同次項に応じた特殊解を加えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '二階線形ODEは特性方程式で体系的に解けます。\n\n・異なる実数根：y = C₁e^(r₁x) + C₂e^(r₂x)\n・重根：y = (C₁ + C₂x)e^(rx)\n・複素根 α±βi：y = e^(αx)(C₁cosβx + C₂sinβx)\n\n物理の振動問題の基礎になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
