import { Tutorial } from '../types';

export const separationVariablesTutorial: Tutorial = {
  id: 'separation-variables',
  title: '変数分離法',
  description: '最も基本的なODEの解法である変数分離法を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: 'xとyを分ける',
      content: 'dy/dx = g(x)h(y) の形のODEは、両辺を分離して積分できます。\n\n(1/h(y))dy = g(x)dx と変形し、両辺を積分するだけです。\n\nこの単純だが強力な手法が「変数分離法」です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'separation-variables-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '分離の手順を体験',
      content: 'dy/dx = xy の解法を順を追って体験しましょう。\n\nステップを一つずつ進め、変数分離→積分→一般解の導出を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'separation-variables-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：dy/dx = xy',
      content: 'dy/dx = xy を解きます。\n\n(1/y)dy = x dx → ∫(1/y)dy = ∫x dx\n\nln|y| = x²/2 + C → y = Ae^(x²/2)\n\n初期条件 y(0) = 1 なら A = 1 で y = e^(x²/2) です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：dy/dx = y²',
      content: 'dy/dx = y² を変数分離で解きます。\n\ny⁻²dy = dx → -1/y = x + C → y = -1/(x + C)\n\n初期条件 y(0) = 1 なら C = -1 で y = 1/(1-x) です。\n\nx = 1 で解が発散する「有限時間爆発」が起きます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'dy/dx = y, y(0)=2 の解はどれか？',
        options: [
          { id: 'a', label: 'y = e^(2x)', correct: false },
          { id: 'b', label: 'y = 2e^x', correct: true },
          { id: 'c', label: 'y = 2x', correct: false },
          { id: 'd', label: 'y = e^x + 1', correct: false },
        ],
        explanation: '変数分離で (1/y)dy = dx → ln|y| = x + C → y = Ae^x。y(0) = 2 より A = 2。よって y = 2e^x です。',
      },
    },
    {
      id: 'alternate',
      title: '変数分離できない場合',
      content: 'dy/dx = x + y のように、右辺が g(x)h(y) の積に分解できない場合は変数分離法が使えません。\n\nそのような場合は積分因子法や定数変化法など別の手法が必要になります。\n\n変数分離法が適用できるか見極める力が大切です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '変数分離法はODEの最も基本的な解法です。\n\n・dy/dx = g(x)h(y) の形なら適用可能\n・両辺を分離して積分するだけ\n・初期条件で定数を決定\n\nシンプルですが、多くの実用的なODEがこの方法で解けます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'separation-variables-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
