import { Tutorial } from '../types';

export const sirModelTutorial: Tutorial = {
  id: 'sir-model',
  title: 'SIRモデル',
  description: '感染症の拡大を記述するSIRモデルを学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '感染症の数理',
      content: '感染症はどのように広がり、やがて収束するのか？\n\nSIRモデルは人口を S（感受性）、I（感染者）、R（回復者）に分け、ODEで記述します。\n\nS\' = -βSI, I\' = βSI - γI, R\' = γI\n\nこのシンプルなモデルが感染拡大の本質を捉えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'sir-model-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '感染率を変えてみよう',
      content: '感染率 β と回復率 γ を変えて、感染曲線がどう変わるか観察しましょう。\n\n基本再生産数 R₀ = βS₀/γ が1を超えるかどうかが鍵です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'sir-model-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：感染カーブのピーク',
      content: 'I\' = βSI - γI = I(βS - γ) より：\n\nS > γ/β のとき I は増加、S < γ/β のとき I は減少。\n\nピーク時は S = γ/β（= S₀/R₀）です。\n\nR₀ が大きいほどピークが高く早く来ます。「カーブを平坦にする」とは R₀ を下げることです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：集団免疫',
      content: '感染が拡大しないためには R₀ · S/N < 1、つまり S/N < 1/R₀ が必要です。\n\n免疫を持つ割合が 1 - 1/R₀ を超えると集団免疫が達成されます。\n\n麻疹（R₀ ≈ 15）では約93%、インフルエンザ（R₀ ≈ 2）では約50%が必要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'R₀ = 4 のとき、集団免疫に必要な免疫割合は？',
        options: [
          { id: 'a', label: '25%', correct: false },
          { id: 'b', label: '50%', correct: false },
          { id: 'c', label: '75%', correct: true },
          { id: 'd', label: '100%', correct: false },
        ],
        explanation: '集団免疫の閾値は 1 - 1/R₀ = 1 - 1/4 = 75% です。人口の75%以上が免疫を持てば感染は拡大しません。',
      },
    },
    {
      id: 'alternate',
      title: 'SIRモデルの拡張',
      content: 'SIRモデルには多くの拡張があります。\n\n・SEIR：潜伏期間 E を追加\n・SIS：回復後も再感染（免疫なし）\n・SIRS：免疫が一定期間後に消失\n・年齢構造モデル：年齢層別の接触パターン\n\n現実の感染症に応じてモデルを選びます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'SIRモデルは感染症数理の基本です。\n\n・S\' = -βSI, I\' = βSI - γI, R\' = γI\n・R₀ = βS₀/γ が拡大の閾値\n・集団免疫の閾値は 1 - 1/R₀\n\nODEが公衆衛生政策に直接役立つ好例です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'sir-model-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
