import { Tutorial } from '../types';

export const whatIsOdeTutorial: Tutorial = {
  id: 'what-is-ode',
  title: 'ODEとは',
  description: '常微分方程式の基本概念と意味を学ぶ',
  category: 'ode',
  steps: [
    {
      id: 'hook',
      title: '変化を記述する言葉',
      content: '物体の落下、人口の増減、温度の変化…。\n\n自然界のあらゆる「変化」を数学的に記述する道具が常微分方程式（ODE）です。\n\ndy/dx = f(x, y) という形で、未知関数とその導関数の関係を表します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '初期条件を変えてみよう',
      content: '初期値 y(0) を変えると、解曲線がどう変わるか観察しましょう。\n\nスライダーを動かして、同じ微分方程式でも初期条件によって解が異なることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '例：自由落下',
      content: '最も簡単なODEの例として自由落下を考えます。\n\nv\'(t) = -g（gは重力加速度）\n\nこれは速度 v(t) の時間変化率が一定（-g）であることを意味します。解は v(t) = v₀ - gt です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '例：冷却法則',
      content: 'ニュートンの冷却法則は dT/dt = -k(T - Tₑ) と表されます。\n\nTは物体の温度、Tₑは環境温度、kは冷却定数です。\n\n温度差に比例して冷える速度が変わるという自然な法則がODEで記述できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'dy/dx = 2x の解 y(x) で y(0)=1 を満たすものはどれか？',
        options: [
          { id: 'a', label: 'y = x² + 1', correct: true },
          { id: 'b', label: 'y = 2x + 1', correct: false },
          { id: 'c', label: 'y = x²', correct: false },
          { id: 'd', label: 'y = 2x²', correct: false },
        ],
        explanation: 'dy/dx = 2x を積分すると y = x² + C。初期条件 y(0) = 1 より C = 1。よって y = x² + 1 です。',
      },
    },
    {
      id: 'alternate',
      title: '幾何学的な見方',
      content: 'ODEは各点 (x, y) で「接線の傾き」を指定しています。\n\nこれを平面上に矢印で描くと「方向場」になり、解曲線はこの矢印に沿って流れる曲線です。\n\n代数的な計算だけでなく、視覚的に解の振る舞いを理解できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '常微分方程式（ODE）は変化の法則を記述する数学の道具です。\n\n・未知関数とその導関数の関係式\n・初期条件によって解が一意に定まる\n・方向場で幾何学的に理解できる\n\n次のチュートリアルで方向場を詳しく学びましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
