import { Tutorial } from '../types';

export const aircraftStabilityTutorial: Tutorial = {
  id: 'aircraft-stability',
  title: '航空機の安定性',
  description: '航空機の縦方向運動の安定性をラプラス変換で解析する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '飛行中の安定と不安定',
      content: '航空機が外乱を受けた後、安定に元の姿勢に戻るケースと発散するケースをアニメーションで比較。ピッチ角の時間変化を表示する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '重心位置を変えてみよう',
      content: '航空機の重心位置を前後に移動させ、縦安定性がどう変化するかを観察しよう。重心が後ろに行き過ぎると不安定になる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '縦方向の短周期モード',
      content: '航空機の縦方向運動は短周期モードと長周期モード（フゴイド）に分離できる。短周期: Δα″ + 2ζsp·ωsp·Δα′ + ωsp²·Δα = 入力。ラプラス変換で G(s) = ωsp²/(s² + 2ζsp·ωsp·s + ωsp²)。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: 'フゴイドモード',
      content: 'フゴイドは長周期の緩やかな振動で、高度と速度が交互に変化する。典型的には ζ が小さく、減衰が弱い。伝達関数の極は虚軸近くにあり、長時間持続する振動を示す。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '航空機の安定性判定',
      content: '短周期モードの特性方程式 s²+4s+20=0 の極から安定性を判定せよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 's²+4s+20=0 の根は s=-2±4j。この短周期モードについて正しいのはどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '不安定で発散する', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '安定で振動的に収束する', correct: false },
        ],
        explanation: '実部 -2 < 0 なので安定。虚部 ±4j があるので振動的。ζ = 2/√20 ≈ 0.45 の減衰振動。ωn = √20 ≈ 4.47 rad/s。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'フライ・バイ・ワイヤと安定性増大システム',
      content: '現代の戦闘機は意図的に静的不安定に設計し、コンピュータ制御で安定化する（CCV）。ラプラス解析で不安定な極をフィードバックにより左半面に移動させる。機動性と安定性の両立が可能になる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '航空機の安定性を設計しよう',
      content: '航空機モデルのパラメータを調整し、短周期モードとフゴイドモードの両方が安定となる設計を見つけよう。極配置を確認しながら進める。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
