import { Tutorial } from '../types';

export const basicTransformTableTutorial: Tutorial = {
  id: 'basic-transform-table',
  title: '基本関数の変換表',
  description: 'よく使うラプラス変換ペアを一覧で整理し、パターンを把握する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '変換ペアのギャラリー',
      content: '代表的な関数 1, t, t², e^{at}, sin(ωt), cos(ωt) のグラフが順番に表示され、それぞれの変換結果 F(s) が隣に現れるアニメーション。時間領域と s 領域の対応を視覚的に一望する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '変換表マッチング',
      content: '左側に f(t)、右側に F(s) のカードが並ぶ。正しいペアをドラッグして結び付けよう。例えば f(t) = t^n ↔ F(s) = n!/s^{n+1} など。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'べき乗関数 t^n の変換',
      content: 'L{t^n} = n!/s^{n+1}。n=0 → 1/s、n=1 → 1/s²、n=2 → 2/s³ と規則的に変化する。ガンマ関数を使えば非整数にも拡張でき、L{t^α} = Γ(α+1)/s^{α+1} となる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '三角関数の変換',
      content: 'L{sin(ωt)} = ω/(s²+ω²)、L{cos(ωt)} = s/(s²+ω²)。オイラーの公式 e^{iωt} = cos(ωt) + i·sin(ωt) を使って導出できる。分母 s²+ω² が振動の特徴を表す。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '変換ペアの確認',
      content: 'L{e^{-2t}·sin(3t)} の結果を選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'L{e^{-2t}·sin(3t)} はどれか？（s シフト定理を使う）',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: '3/((s+2)²+9)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '3/(s²+9)', correct: false },
        ],
        explanation: 's シフト定理により L{e^{at}f(t)} = F(s-a)。L{sin(3t)} = 3/(s²+9) なので、s を s+2 に置き換えて 3/((s+2)²+9) となる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '変換表を暗記する必要はあるか？',
      content: '基本的な変換ペアは頻繁に使うため覚えておくと便利だが、表を参照しながら使うのが現実的だ。重要なのは s シフト定理や微分法則などの「性質」を理解することで、複雑な関数も基本ペアに帰着できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '変換表フラッシュカード',
      content: 'フラッシュカード形式で変換ペアを練習しよう。f(t) が表示されたら F(s) を答え、F(s) が表示されたら f(t) を推測する。繰り返して定着させよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
