import { Tutorial } from '../types';

export const bodePlotTutorial: Tutorial = {
  id: 'bode-plot',
  title: 'ボーデ線図',
  description: '周波数応答をゲイン線図と位相線図で表現する方法を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '周波数ごとの応答を一望する',
      content: '正弦波入力の周波数を低→高に変化させると、出力の振幅と位相がどう変わるかをアニメーション表示。この振幅と位相を対数軸上にプロットしたものがボーデ線図。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bode-plot-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'ボーデ線図を描こう',
      content: 'G(s) = K/(τs+1) の K と τ をスライダーで変え、ボーデ線図のゲインと位相がどう変化するかを観察しよう。折れ点周波数 ω=1/τ の位置に注目。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bode-plot-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '1次遅れ系のボーデ線図',
      content: 'G(jω) = 1/(1+jωτ)。ゲイン: |G| = 1/√(1+ω²τ²) → 20log₁₀|G| [dB]。ω≪1/τ で 0dB、ω≫1/τ で -20dB/dec の傾き。位相: ∠G = -arctan(ωτ)。ω=1/τ で -45°。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '漸近線近似法',
      content: 'ボーデ線図は直線（漸近線）で近似できる。1次の極は折れ点以下で 0dB、以上で -20dB/dec。零点は逆に +20dB/dec。これらを足し合わせて全体の概形を得る。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ボーデ線図の読み取り',
      content: 'G(s) = 100/(s+10) のゲイン交差周波数（|G|=1 となる周波数）に最も近いものはどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'G(jω) = 100/(jω+10) で |G(jω)| = 1 となる ω は約いくらか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'ω ≈ 10', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'ω ≈ 100', correct: false },
        ],
        explanation: '|G(jω)| = 100/√(ω²+100) = 1。ω²+100 = 10000 → ω² = 9900 → ω ≈ 99.5 ≈ 100。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'ゲイン余裕と位相余裕',
      content: 'ゲイン余裕はボーデ線図の位相が -180° になる周波数でのゲインの逆数。位相余裕はゲインが 0dB になる周波数での位相の -180° からの余裕。どちらも安定性の指標。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'ボーデ線図を読み解こう',
      content: '与えられた伝達関数のボーデ線図を漸近線近似で描き、ゲイン余裕と位相余裕を読み取る練習をしよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'bode-plot-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
