import { Tutorial } from '../types';

export const chemicalProcessTutorial: Tutorial = {
  id: 'chemical-process',
  title: '化学プロセス制御',
  description: '化学プラントの温度・流量制御をラプラス変換で解析する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '化学反応器の温度制御',
      content: '連続攪拌槽型反応器（CSTR）の温度が目標値に追従する過程をアニメーションで表示。むだ時間と大きな時定数を持つプロセスの制御の難しさを視覚化。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'プロセスパラメータを調整',
      content: '反応器の時定数 τ、むだ時間 L、ゲイン K を変えながら、ステップ応答の変化を観察しよう。L/τ の比が制御の難易度を決める。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'FOPDT モデル',
      content: '化学プロセスは1次遅れ＋むだ時間（FOPDT）G(s) = K·e^{-Ls}/(τs+1) でよく近似される。K はプロセスゲイン、τ は時定数、L はむだ時間。ステップ応答試験から同定できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: 'IMC（内部モデル制御）',
      content: 'プロセスモデル G_m(s) を使った IMC 設計: C_IMC(s) = G_m⁻¹(s)·F(s)。フィルタ F(s) = 1/(λs+1) で実現可能性を確保。λ はチューニングパラメータで、大きいと安定だが遅い。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'プロセス制御の理解',
      content: 'FOPDT モデルで L/τ が大きいとき制御が難しい理由は？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'むだ時間と時定数の比 L/τ が大きい場合、制御が困難になる主な理由はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'プロセスゲインが不安定になるため', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '遅延により制御入力の効果が遅れ、修正が間に合わないため', correct: false },
        ],
        explanation: 'むだ時間が大きいと、制御入力の効果が出力に反映されるまでの遅れが大きく、その間に誤差が蓄積される。位相遅れが増大し安定余裕が減少する。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'カスケード制御とフィードフォワード',
      content: '化学プロセスではカスケード制御（内側に副変数のループ）やフィードフォワード制御（外乱を測定して補償）がよく使われる。ラプラス変換により各ループの設計を独立に行える。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'プロセス制御を設計しよう',
      content: '化学反応器の温度制御系を設計しよう。FOPDT モデルを同定し、PID制御器のパラメータを決定して、目標追従と外乱抑制を両立させる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
