import { Tutorial } from '../types';

export const circuitSDomainTutorial: Tutorial = {
  id: 'circuit-s-domain',
  title: '電気回路のs領域解析',
  description: 'RLC回路のインピーダンスをs領域で統一的に扱う方法を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'インピーダンスの統一表現',
      content: '抵抗R、インダクタL、キャパシタCのインピーダンスがそれぞれ R, sL, 1/(sC) として統一的に表されるアニメーション。オームの法則が s 領域でそのまま使える。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'circuit-s-domain-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'RLC回路のパラメータを変更',
      content: 'R, L, C の値をスライダーで変え、直列RLC回路のインピーダンス Z(s) = R + sL + 1/(sC) と共振特性の変化を観察しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'circuit-s-domain-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '直列RLC回路の解析',
      content: 'Z(s) = R + sL + 1/(sC) = (LCs² + RCs + 1)/(Cs)。伝達関数 H(s) = V_C/V_in = 1/(LCs² + RCs + 1)。これは2次系であり、共振周波数 ω₀ = 1/√(LC)、ダンピング比 ζ = R/(2√(L/C))。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '初期条件の組み込み',
      content: 'コンデンサの初期電圧 v_C(0) やインダクタの初期電流 i_L(0) は、s 領域で等価電圧源・電流源として扱える。V_C(s) = v_C(0)/s + I(s)/(Cs)。これによりスイッチ投入後の過渡応答が計算できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'インピーダンスの計算',
      content: 'R=10Ω と C=0.01F の並列接続のインピーダンス Z(s) はどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'R と C の並列接続のインピーダンス Z(s) はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'R + 1/(sC)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'R/(sRC+1)', correct: true },
        ],
        explanation: '並列: 1/Z = 1/R + sC = (1+sRC)/R → Z = R/(1+sRC)。また 1/Z = sC + 1/R → Z = 1/(sC+1/R)。どちらも同じ式を変形しただけ。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'フィルタ回路の設計',
      content: 'RC回路はローパスフィルタ H(s) = 1/(sRC+1)、CR回路はハイパスフィルタ H(s) = sRC/(sRC+1)。RLC回路はバンドパスフィルタにもなる。s 領域でフィルタ特性を設計できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '回路解析チャレンジ',
      content: '与えられた RLC 回路の伝達関数を s 領域で求め、周波数特性を予測しよう。回路図からインピーダンスを組み立てる練習。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'circuit-s-domain-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
