import { Tutorial } from '../types';

export const convolutionTheoremTutorial: Tutorial = {
  id: 'convolution-theorem',
  title: '畳み込み定理',
  description: '時間領域の畳み込みが s 領域の積に対応する重要な定理を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '畳み込みの視覚化',
      content: '2つの関数 f(τ) と g(t-τ) のスライド積分が進む様子をアニメーションで表示する。τ が 0 から t まで動くとき、重なり部分の面積が出力値になる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'convolution-theorem-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '畳み込みをスライドで体験',
      content: '時刻 t をスライダーで動かし、f(τ) と g(t-τ) の重なり面積がどう変化するかを観察しよう。その面積が畳み込み (f*g)(t) の値になる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'convolution-theorem-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '畳み込み定理の内容',
      content: 'L{(f*g)(t)} = F(s)·G(s)。時間領域の畳み込み ∫₀^t f(τ)g(t-τ)dτ は s 領域では単なる積 F(s)·G(s) になる。逆に L⁻¹{F(s)·G(s)} = (f*g)(t)。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '具体例：L⁻¹{1/[s(s+1)]}',
      content: 'F(s) = 1/s（f(t) = 1）、G(s) = 1/(s+1)（g(t) = e^{-t}）とする。L⁻¹{F·G} = ∫₀^t 1·e^{-τ}dτ = 1-e^{-t}。部分分数分解でも同じ結果：1/s - 1/(s+1) → 1-e^{-t}。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '畳み込み定理の応用',
      content: 'L⁻¹{1/[s²(s+2)]} を畳み込みで考えるとき、最も適切な分解はどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '1/[s²(s+2)] を畳み込みで計算するための分解として適切なのはどれか？',
        options: [
          { id: 'a', label: 'F(s) = 1/s², G(s) = 1/(s+2)', correct: false },
          { id: 'b', label: 'F(s) = 1/s, G(s) = 1/s(s+2)', correct: true },
          { id: 'c', label: 'F(s) = s, G(s) = 1/[s³(s+2)]', correct: false },
          { id: 'd', label: 'F(s) = 1/(s+2)², G(s) = 1/s²', correct: false },
        ],
        explanation: '1/s² → f(t)=t、1/(s+2) → g(t)=e^{-2t} と分解すれば、畳み込み ∫₀^t τ·e^{-2(t-τ)}dτ で逆変換が求められる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '畳み込みの物理的意味',
      content: '畳み込み積分は「過去のすべての入力の影響を現在に積み上げる」操作。入力 u(τ) がシステムのインパルス応答 g(t-τ) を通じて出力に寄与する。これがLTIシステムの入出力関係の本質。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '畳み込み計算を実践',
      content: '2つの簡単な関数の畳み込みを手計算とグラフの両面から求めよう。s 領域での積と時間領域での畳み込みが一致することを確認する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'convolution-theorem-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
