import { Tutorial } from '../types';

export const delaySystemTutorial: Tutorial = {
  id: 'delay-system',
  title: '遅れ系の扱い',
  description: '時間遅れ（むだ時間）を含むシステムのラプラス解析を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'むだ時間の影響',
      content: '入力信号がシステムに届くまでに遅延がある場合、制御が不安定になりやすい。遅延あり・なしの応答を並べて比較するアニメーション。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'delay-system-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '遅延時間を変えてみよう',
      content: 'むだ時間 L をスライダーで変えながら、フィードバック制御系のステップ応答がどう変化するかを観察しよう。遅延が大きいと振動・発散することを体感する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'delay-system-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'むだ時間の伝達関数表現',
      content: '時間遅延 L のシステム: y(t) = u(t-L)。ラプラス変換: Y(s) = e^{-Ls}·U(s)。伝達関数 G_d(s) = e^{-Ls}。これは無限次元系であり、有理関数では正確に表現できない。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: 'パデ近似',
      content: 'e^{-Ls} を有理関数で近似するパデ近似。1次: e^{-Ls} ≈ (1-Ls/2)/(1+Ls/2) = (2-Ls)/(2+Ls)。2次: (12-6Ls+L²s²)/(12+6Ls+L²s²)。近似次数を上げると精度が向上する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'むだ時間の影響',
      content: '1次パデ近似 (2-Ls)/(2+Ls) は何を意味するか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '1次パデ近似で、分子に不安定な零点（右半面のゼロ）が現れるのはなぜか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '近似誤差によるもので物理的意味はない', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'むだ時間系の非最小位相特性を反映している', correct: false },
        ],
        explanation: 'むだ時間系は位相が周波数に比例して遅れるため非最小位相系。パデ近似の右半面の零点はこの特性を近似的に再現している。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'スミス予測器',
      content: 'むだ時間を含むプロセスの制御にはスミス予測器が有効。プロセスモデルを使って遅延の影響を予測・補償し、あたかも遅延がないかのように制御器を設計できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '遅れ系の制御を設計しよう',
      content: 'むだ時間を含むプラントに対して、パデ近似やスミス予測器を使った制御器を設計し、安定な応答を実現しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'delay-system-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
