import { Tutorial } from '../types';

export const derivativeTransformTutorial: Tutorial = {
  id: 'derivative-transform',
  title: '微分のラプラス変換',
  description: '微分が s の乗算に変わる仕組みを理解し、微分方程式の解法に応用する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '微分が乗算になる',
      content: '時間領域で f(t) を微分する操作が、s 領域では s を掛ける操作に変わるアニメーション。微分の矢印が「×s」のブロックに変換される様子を視覚化する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'derivative-transform-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '初期条件の効果を確認',
      content: 'f(t) = sin(ωt) の場合に f(0) の値を変えながら、L{f′(t)} = sF(s) - f(0) の各項がどう変化するかをインタラクティブに確認しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'derivative-transform-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '1階微分の変換',
      content: 'L{f′(t)} = sF(s) - f(0)。部分積分で導出する：∫₀^∞ f′(t)e^{-st} dt = [f(t)e^{-st}]₀^∞ + s∫₀^∞ f(t)e^{-st} dt = -f(0) + sF(s)。初期値 f(0) が自動的に含まれるのが特長。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '2階微分の変換',
      content: 'L{f″(t)} = s²F(s) - sf(0) - f′(0)。1階の結果を再帰的に適用する。これにより y″ + ay′ + by = g(t) の初期値問題が (s² + as + b)Y(s) = G(s) + 初期条件 という代数方程式に変わる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '微分変換の適用',
      content: 'y″ + 4y = 0, y(0)=1, y′(0)=0 をラプラス変換した結果を選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '上記の初期値問題をラプラス変換すると Y(s) はどうなるか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: 'Y(s) = s/(s²+4)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'Y(s) = 1/(s²+4)', correct: false },
        ],
        explanation: 's²Y-s·1-0 + 4Y = 0 → (s²+4)Y = s → Y(s) = s/(s²+4)。逆変換すると y(t) = cos(2t)。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'n階微分への一般化',
      content: 'L{f⁽ⁿ⁾(t)} = sⁿF(s) - s^{n-1}f(0) - s^{n-2}f′(0) - ... - f^{(n-1)}(0)。各初期条件が s のべき乗と組み合わさって現れる。高階の微分方程式でも同じパターンで適用できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '微分方程式を代数方程式に変えよう',
      content: '与えられた微分方程式と初期条件から、ラプラス変換を適用して代数方程式を導出する練習をしよう。各ステップを順番に進めて Y(s) を求めよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'derivative-transform-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
