import { Tutorial } from '../types';

export const digitalControlTutorial: Tutorial = {
  id: 'digital-control',
  title: 'ディジタル制御入門',
  description: '連続系のラプラス変換から離散系のz変換への橋渡しを学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '連続から離散へ',
      content: '連続信号がサンプラーで離散化され、0次ホールドで復元される過程をアニメーションで表示する。サンプリング周期 T がシステムの挙動を変える。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'サンプリング周期を変えてみよう',
      content: 'サンプリング周期 T を変えながら、連続系のステップ応答と離散系のステップ応答を比較しよう。T が大きいと応答が劣化する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 's 領域と z 領域の関係',
      content: 'z = e^{sT} の変換で s 平面から z 平面に写像される。s 平面の左半面は z 平面の単位円内に対応する。安定条件は |z| < 1（単位円の内側）となる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '双一次変換（タスティン変換）',
      content: 's = (2/T)·(z-1)/(z+1) で s 領域の設計を z 領域に変換できる。G(s) = 1/(s+a) に適用すると G(z) = T(z+1)/[2(z-1)+aT(z+1)]。周波数特性が歪むが安定性は保存される。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ディジタル制御の基礎',
      content: 's 平面の虚軸は z 平面のどこに対応するか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 's = jω のとき z = e^{jωT} が描く軌跡はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'z 平面の実軸', correct: false },
          { id: 'c', label: 'b', correct: true },
          { id: 'd', label: 'z 平面の虚軸', correct: false },
        ],
        explanation: 'z = e^{jωT} は |z| = 1 なので単位円上。s 平面の安定境界（虚軸）は z 平面の安定境界（単位円）に写像される。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'サンプリング定理との関係',
      content: 'ナイキスト周波数 ωN = π/T 以上の信号は正しく再現できない（エイリアシング）。制御帯域の5〜10倍のサンプリング周波数が実用的な目安。ラプラス解析で設計した連続系を適切に離散化することが重要。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '連続系を離散化しよう',
      content: 'ラプラス変換で設計した連続制御器を双一次変換で離散化し、z 領域でのステップ応答を確認しよう。サンプリング周期の選定も行う。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
