import { Tutorial } from '../types';

export const feedbackDesignTutorial: Tutorial = {
  id: 'feedback-design',
  title: 'フィードバック系の設計',
  description: 'フィードバック制御系の閉ループ特性を設計する手法を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'フィードバックの力',
      content: '開ループ（フィードバックなし）と閉ループ（フィードバックあり）の応答を並べて比較するアニメーション。フィードバックが外乱抑制と感度低減をもたらす。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'フィードバックゲインを調整',
      content: '単純なフィードバック系 T(s) = KG(s)/(1+KG(s)) のゲイン K を変えて、応答速度と安定性のトレードオフを体験しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '感度関数と相補感度関数',
      content: '感度関数 S(s) = 1/(1+G·C)、相補感度関数 T(s) = G·C/(1+G·C)。S+T=1 が常に成立。S は外乱への感度、T は目標追従性能を表す。両方を同時に小さくすることはできない。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '根軌跡法による設計',
      content: 'ゲイン K を 0→∞ に変えたとき、閉ループの極が s 平面上でたどる軌跡が根軌跡。この軌跡上で望ましい極配置を実現する K を選ぶ。ζ と ωn の仕様を満たす領域に極が入るよう設計する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'フィードバック系の特性',
      content: 'G(s)=1/(s+1) にゲイン K のフィードバックを適用。閉ループの極はどこにあるか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'T(s) = K/[(s+1)+K] = K/(s+1+K) の極はどこか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: 's = -(1+K)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 's = -1', correct: false },
        ],
        explanation: '分母 s+1+K=0 → s=-(1+K)。K>0 なら極は s=-1 よりさらに左に移動し、応答が速くなる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'ロバスト制御の入口',
      content: 'モデルの不確かさがあっても安定性と性能を保証するロバスト制御。H∞制御は感度関数のピーク値を最小化する設計法で、ラプラス変換と周波数応答の理論に基づく。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'フィードバック系を設計しよう',
      content: '指定された仕様（帯域幅、ゲイン余裕、位相余裕）を満たすフィードバック制御器を設計しよう。根軌跡と周波数応答の両面から検証する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
