import { Tutorial } from '../types';

export const heavisideFunctionTutorial: Tutorial = {
  id: 'heaviside-function',
  title: 'ヘヴィサイドの階段関数',
  description: '時間遅れと区分的な入力をラプラス変換で扱う方法を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '時間をずらすスイッチ',
      content: 'ヘヴィサイド関数 u(t-a) が t=a でスイッチを入れるように 0 から 1 にジャンプするアニメーション。複数の階段関数を組み合わせて矩形パルスや階段状入力が作られる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '遅延時間を変えてみよう',
      content: '遅延時間 a をスライダーで変えながら、f(t-a)·u(t-a) のグラフとそのラプラス変換 e^{-as}F(s) の変化を観察しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '第2移動定理',
      content: 'L{f(t-a)·u(t-a)} = e^{-as}F(s)。時間領域で a だけ遅延させることは、s 領域で e^{-as} を掛けることに対応する。u(t-a) のラプラス変換は e^{-as}/s。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '矩形パルスの変換',
      content: '幅 T のパルス p(t) = u(t)-u(t-T)。L{p(t)} = 1/s - e^{-Ts}/s = (1-e^{-Ts})/s。これはスイッチを t=0 で ON にし t=T で OFF にする操作に対応する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '移動定理の適用',
      content: 'L{(t-3)²·u(t-3)} を求めよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'L{(t-3)²·u(t-3)} はどれか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: 'e^{-3s}·2/s³', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '2e^{-3s}/s²', correct: false },
        ],
        explanation: 'f(t) = t² とすると F(s) = 2/s³。第2移動定理により L{(t-3)²·u(t-3)} = e^{-3s}·2/s³。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'デルタ関数との関係',
      content: 'ヘヴィサイド関数の微分はデルタ関数 δ(t)。u′(t) = δ(t)。ラプラス変換でも L{δ(t)} = 1、L{u(t)} = 1/s で、微分定理 s·(1/s) - u(0⁻) = 1 と整合する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '区分的信号を組み立てよう',
      content: 'ヘヴィサイド関数を組み合わせて、指定された区分的信号（階段状、鋸歯状など）を作り、そのラプラス変換を求めよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
