import { Tutorial } from '../types';

export const impulseResponseTutorial: Tutorial = {
  id: 'impulse-response',
  title: 'インパルス応答',
  description: 'デルタ関数入力に対する応答がシステムの本質を表すことを理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '瞬間的な衝撃への反応',
      content: 'ドラムを叩く瞬間のような鋭い入力（インパルス）をシステムに与え、その後の自由振動がシステム固有の特性を反映するアニメーション。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'インパルス応答からシステムを推測',
      content: '表示されるインパルス応答の波形から、1次系か2次系か、減衰が速いか遅いかを判断しよう。パラメータを調整してモデルを一致させる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'インパルス応答と伝達関数の関係',
      content: 'インパルス入力 u(t) = δ(t) のラプラス変換は U(s) = 1。よって Y(s) = G(s)·1 = G(s)。つまりインパルス応答 g(t) = L⁻¹{G(s)}。インパルス応答は伝達関数の逆ラプラス変換そのもの。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '具体例：2次系のインパルス応答',
      content: 'G(s) = ωn²/(s²+2ζωns+ωn²) のインパルス応答は g(t) = (ωn/√(1-ζ²))·e^{-ζωnt}·sin(ωd·t)。初期に急上昇し、減衰振動しながら 0 に戻る。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'インパルス応答の判定',
      content: 'G(s) = 1/(s+3) のインパルス応答はどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'G(s) = 1/(s+3) のインパルス応答 g(t) はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'g(t) = e^{3t}', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'g(t) = e^{-3t}', correct: false },
        ],
        explanation: 'g(t) = L⁻¹{G(s)} = L⁻¹{1/(s+3)} = e^{-3t}。最後の選択肢はステップ応答にあたる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'インパルス応答と畳み込み',
      content: '任意の入力 u(t) に対する出力は y(t) = ∫₀^t g(t-τ)u(τ)dτ（畳み込み積分）で表せる。インパルス応答が分かれば、あらゆる入力に対する応答を計算できる。これがシステム理論の基本原理。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'インパルス応答を測定しよう',
      content: '仮想的なシステムにインパルスを入力し、得られた応答波形からシステムの極と伝達関数を推定する実験をしよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
