import { Tutorial } from '../types';

export const integralTransformTutorial: Tutorial = {
  id: 'integral-transform',
  title: '積分のラプラス変換',
  description: '積分が s の除算に変わる仕組みを理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '積分が除算になる',
      content: '時間領域での積分 ∫₀^t f(τ)dτ が s 領域では F(s)/s になる変換過程をアニメーションで表示する。面積の蓄積が「÷s」に変わる直感的なイメージ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'integral-transform-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '積分結果を比較',
      content: 'f(t) を選択肢（1, t, e^{-t}）から選び、その積分 ∫₀^t f(τ)dτ のグラフと F(s)/s の逆変換結果が一致することをインタラクティブに確認しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'integral-transform-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '積分定理の証明',
      content: 'g(t) = ∫₀^t f(τ)dτ とおくと g′(t) = f(t), g(0) = 0。微分定理より L{g′(t)} = sG(s) - g(0) = sG(s)。一方 L{g′(t)} = L{f(t)} = F(s)。よって G(s) = F(s)/s。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '具体例：∫₀^t sin(τ)dτ',
      content: 'L{sin(t)} = 1/(s²+1) なので、L{∫₀^t sin(τ)dτ} = 1/[s(s²+1)]。実際に積分すると ∫₀^t sin(τ)dτ = 1-cos(t) であり、L{1-cos(t)} = 1/s - s/(s²+1) = 1/[s(s²+1)] と一致する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '積分変換の確認',
      content: 'L{∫₀^t e^{-2τ} dτ} を求めよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'L{∫₀^t e^{-2τ} dτ} はどれか？',
        options: [
          { id: 'a', label: '1/[s(s+2)]', correct: false },
          { id: 'b', label: '1/(s+2)', correct: true },
          { id: 'c', label: 's/(s+2)', correct: false },
          { id: 'd', label: '1/(s²+2)', correct: false },
        ],
        explanation: 'L{e^{-2t}} = 1/(s+2) なので、積分定理により L{∫₀^t e^{-2τ}dτ} = F(s)/s = 1/[s(s+2)]。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '繰り返し積分への拡張',
      content: 'n回積分 ∫₀^t∫₀^{t₁}...f(τ)dτ...dt₁ のラプラス変換は F(s)/sⁿ となる。これは微分定理の逆で、sⁿ で割ることは n 回積分に対応する。積分方程式の解法にも応用できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '微分と積分の対応を整理',
      content: '微分 ↔ s の乗算、積分 ↔ s の除算という対応関係を整理する表を完成させよう。空欄を埋めて対応関係を確認する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'integral-transform-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
