import { Tutorial } from '../types';

export const inverseLaplaceTutorial: Tutorial = {
  id: 'inverse-laplace',
  title: '逆ラプラス変換',
  description: 's 領域から時間領域に戻す方法を習得する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 's 領域から時間領域へ',
      content: 'F(s) = 1/(s²+1) から f(t) = sin(t) が復元される過程をアニメーションで表示する。s 領域の有理式が時間領域の波形に変わる劇的な変化を視覚化。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '部分分数分解を体験',
      content: 'F(s) = (2s+3)/[(s+1)(s+2)] をスライダーで A/(s+1) + B/(s+2) の形に分解しよう。A と B の値を調整して元の式と一致させる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '部分分数分解による逆変換',
      content: 'F(s) = (2s+3)/[(s+1)(s+2)] = A/(s+1) + B/(s+2)。通分して 2s+3 = A(s+2)+B(s+1)。s=-1: 1=A、s=-2: -1=-B → B=1。よって f(t) = e^{-t} + e^{-2t}。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '重複根がある場合',
      content: 'F(s) = 1/(s+1)² の場合、L⁻¹{1/(s+a)²} = t·e^{-at}。よって f(t) = t·e^{-t}。重複根では分母のべきに応じて t の因子が現れる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '逆ラプラス変換',
      content: 'L⁻¹{5/(s²+25)} を求めよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'L⁻¹{5/(s²+25)} はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'cos(5t)', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'sin(5t)', correct: false },
        ],
        explanation: 'L{sin(ωt)} = ω/(s²+ω²)。ω=5 のとき 5/(s²+25) なので、逆変換は sin(5t)。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '複素積分による逆変換（ブロムウィッチ積分）',
      content: '正式な逆ラプラス変換はブロムウィッチ積分 f(t) = (1/2πi)∫_{c-i∞}^{c+i∞} F(s)e^{st} ds で定義される。実用上は部分分数分解と変換表で十分だが、理論的な基盤を知っておくことは有益。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '逆変換チャレンジ',
      content: '様々な F(s) が出題される。部分分数分解を行い、変換表を参照して f(t) を求めよう。難易度が段階的に上がるチャレンジ形式。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
