import { Tutorial } from '../types';

export const laplaceDefinitionTutorial: Tutorial = {
  id: 'laplace-definition',
  title: 'ラプラス変換の定義',
  description: '積分変換 F(s) = ∫₀^∞ f(t)e^{-st} dt の意味を視覚的に理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '無限積分の視覚化',
      content: 'f(t) に e^{-st} を掛けて 0 から ∞ まで積分する過程をアニメーションで表示する。s が大きいほど e^{-st} は急速に減衰し、積分値は変化する。この積分が F(s) を定義する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-definition-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 's の値を変えてみよう',
      content: 'f(t) = 1 のとき、スライダーで s の値を変えながら被積分関数 e^{-st} の形状と積分値 F(s) = 1/s の変化を確認しよう。s > 0 のとき積分が収束することを体感する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-definition-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'f(t) = 1 のラプラス変換',
      content: 'L{1} = ∫₀^∞ e^{-st} dt = [-e^{-st}/s]₀^∞ = 1/s （s > 0）。被積分関数は t → ∞ で 0 に収束するため積分が存在する。これが最も基本的なラプラス変換のペアである。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: 'f(t) = e^{at} のラプラス変換',
      content: 'L{e^{at}} = ∫₀^∞ e^{at}·e^{-st} dt = ∫₀^∞ e^{-(s-a)t} dt = 1/(s-a) （s > a）。収束条件は s > a であり、Re(s) > a の領域で定義される。この領域を収束領域（ROC）と呼ぶ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ラプラス変換の収束条件',
      content: 'f(t) = e^{3t} のラプラス変換の収束条件を答えよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'f(t) = e^{3t} のラプラス変換 F(s) = 1/(s-3) が存在するための条件は？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 's > 0', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 's > 3', correct: false },
        ],
        explanation: 'e^{3t}·e^{-st} = e^{-(s-3)t} が t → ∞ で 0 に収束するためには s - 3 > 0、すなわち s > 3 が必要。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '片側ラプラス変換と両側ラプラス変換',
      content: '工学では通常、片側ラプラス変換（t ≥ 0 の範囲で積分）を使う。これは因果的システム（過去の入力だけに依存するシステム）の解析に適している。両側変換は -∞ から ∞ まで積分するもので、信号処理の理論で使われる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '定義式を組み立てよう',
      content: 'ラプラス変換の定義式の各部分（積分範囲、被積分関数、変数）をドラッグして正しい定義式 F(s) = ∫₀^∞ f(t)e^{-st} dt を組み立てよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-definition-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
