import { Tutorial } from '../types';

export const laplaceOverviewTutorial: Tutorial = {
  id: 'laplace-overview',
  title: 'ラプラス解析の全体像',
  description: 'ラプラス変換の理論と応用を総括し、学習の全体像を把握する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '30のトピックを俯瞰する',
      content: 'ラプラス変換の定義から始まり、性質、逆変換、安定性解析、制御設計、応用分野まで30のトピックが木構造で展開されるアニメーション。全体の繋がりを一望する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-overview-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '知識マップを探索',
      content: '各トピックのノードをクリックすると概要がポップアップ表示される。トピック間の依存関係を矢印で確認しながら、自分の理解度をチェックしよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-overview-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '理論の体系',
      content: '基礎: 定義・変換表・性質（線形性、微分・積分、シフト定理）。解析: 逆変換・初期値問題・伝達関数・極と零点。安定性: ラウス判別・ボーデ線図・ナイキスト線図。これらが制御工学の土台を形成する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '応用の広がり',
      content: '制御: PID制御・フィードバック設計・ロバスト制御。機械: サーボモーター・ロボット・航空機。電気: RLC回路・フィルタ。プロセス: 化学反応器・遅れ系。ディジタル: z変換への橋渡し。ラプラス変換は工学全般の共通言語。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '総合理解度テスト',
      content: 'ラプラス解析の全体像に関する総合問題。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '次のうち、ラプラス変換が直接的に使えない問題はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '線形微分方程式の初期値問題', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '非線形微分方程式の大域的解析', correct: false },
        ],
        explanation: 'ラプラス変換は線形系の解析ツール。非線形方程式には直接適用できない（局所的に線形化すれば部分的に利用可能）。非線形の大域的解析にはリアプノフ法など別の手法が必要。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'さらなる学びへ',
      content: '発展トピック: 状態空間法（多変数系）、最適制御（LQR/LQG）、ロバスト制御（H∞）、非線形制御（リアプノフ法）、適応制御。ラプラス変換の知識はこれら高度な手法の理解の基盤となる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '最終チャレンジ：統合問題',
      content: '変換・逆変換・安定性判定・制御設計を組み合わせた統合問題に挑戦。DCモーターの速度制御系を一から設計し、仕様を満たすPID制御器を完成させよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'laplace-overview-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
