import { Tutorial } from '../types';

export const laplaceBasicsSummaryTutorial: Tutorial = {
  id: 'laplace-basics-summary',
  title: 'ラプラス解析の基本まとめ',
  description: 'ラプラス変換の基本概念を総復習し、知識を整理する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '基本概念のマインドマップ',
      content: 'ラプラス変換を中心に、定義・性質・逆変換・応用が放射状に展開されるマインドマップアニメーション。学んだ概念の全体像を俯瞰する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '概念マップを完成させよう',
      content: '空欄のある概念マップに適切な用語をドラッグして配置し、ラプラス解析の全体像を完成させよう。変換・性質・応用の関連性を確認する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '変換の性質まとめ',
      content: '線形性: L{af+bg}=aF+bG。微分: L{f′}=sF-f(0)。積分: L{∫f}=F/s。sシフト: L{e^{at}f}=F(s-a)。時間遅延: L{f(t-a)u(t-a)}=e^{-as}F(s)。畳み込み: L{f*g}=FG。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '応用分野のまとめ',
      content: '微分方程式の解法 → 初期値問題。伝達関数 → システムの入出力関係。極と零点 → 安定性と応答特性。ボーデ線図・ナイキスト線図 → 周波数領域での解析と設計。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '総合確認',
      content: 'ラプラス変換の性質に関する総合問題。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '次のうち誤っているものはどれか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: 'L{f·g} = F(s)·G(s)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'L{f′(t)} = sF(s) - f(0)', correct: false },
        ],
        explanation: 'L{f·g} ≠ F·G。s 領域での積は畳み込みの変換であり、時間領域での関数の積ではない。L{f*g}=F·G（畳み込み定理）が正しい。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '次のステップへ',
      content: '基本を理解した次は、PID制御、電気回路、ロボット制御などの実応用に進もう。ラプラス変換は理論と実践を橋渡しする強力なツールであり、制御工学の基盤となる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '総合チャレンジ',
      content: '変換公式、性質、安定性判別を組み合わせた総合問題に挑戦。制限時間内にできるだけ多くの問題を解こう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
