import { Tutorial } from '../types';

export const linearityLaplaceTutorial: Tutorial = {
  id: 'linearity-laplace',
  title: '線形性',
  description: 'ラプラス変換の線形性 L{af+bg} = aF+bG を理解し活用する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '重ね合わせの原理',
      content: '2つの関数 f(t) と g(t) を足し合わせた信号のラプラス変換が、それぞれの変換結果の和と一致する様子をアニメーションで示す。色分けされたグラフが合成されていく。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'linearity-laplace-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '係数を変えて確認',
      content: 'f(t) = sin(t) と g(t) = e^{-t} に対して、係数 a, b をスライダーで変えながら L{a·f + b·g} = a·F(s) + b·G(s) が成り立つことをインタラクティブに確認しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'linearity-laplace-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '線形性の証明',
      content: 'L{af(t)+bg(t)} = ∫₀^∞ [af(t)+bg(t)]e^{-st} dt = a∫₀^∞ f(t)e^{-st} dt + b∫₀^∞ g(t)e^{-st} dt = aF(s)+bG(s)。積分の線形性からラプラス変換の線形性が直接導かれる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '線形性の活用例',
      content: 'L{3t² + 5e^{-2t}} = 3·L{t²} + 5·L{e^{-2t}} = 3·(2/s³) + 5·(1/(s+2)) = 6/s³ + 5/(s+2)。複雑な関数も基本変換の線形結合として計算できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '線形性の適用',
      content: 'L{2cos(t) - 3sin(2t)} を求めよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'L{2cos(t) - 3sin(2t)} はどれか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: '2s/(s²+1) - 6/(s²+4)', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '2/(s²+1) - 3/(s²+4)', correct: false },
        ],
        explanation: 'L{cos(t)} = s/(s²+1)、L{sin(2t)} = 2/(s²+4)。線形性により 2·s/(s²+1) - 3·2/(s²+4) = 2s/(s²+1) - 6/(s²+4)。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '線形性が成り立たない場合',
      content: 'ラプラス変換は線形演算子だが、f(t)·g(t) のような積に対しては L{fg} ≠ F·G である。積のラプラス変換は畳み込み積分と関連するが、単純な積にはならない。この区別は重要だ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '線形結合を分解しよう',
      content: '与えられた複合関数を基本関数の線形結合に分解し、各項のラプラス変換を適用して最終結果を組み立てる練習をしよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'linearity-laplace-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
