import { Tutorial } from '../types';

export const nyquistPlotTutorial: Tutorial = {
  id: 'nyquist-plot',
  title: 'ナイキスト線図',
  description: '周波数応答を複素平面上にプロットし、安定性を判定する方法を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '複素平面を巡る軌跡',
      content: 'G(jω) を ω=0 から ∞ まで変化させると、複素平面上に曲線が描かれる。この軌跡がナイキスト線図。-1+j0 の点を囲むかどうかで安定性が判定できる驚きの定理。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nyquist-plot-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'ナイキスト軌跡を追跡',
      content: '周波数 ω をスライダーで変えながら、G(jω) の点が複素平面上を移動する様子を追跡しよう。軌跡の形状と -1 点との関係に注目。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nyquist-plot-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'ナイキストの安定判別法',
      content: '閉ループ系の安定性は、開ループ伝達関数 G(s)H(s) のナイキスト軌跡が -1+j0 の点を反時計回りに囲む回数 N で判定される。N = P - Z（P:開ループの右半面の極数、Z:閉ループの右半面の極数）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '具体例：1次系',
      content: 'G(s) = K/(s+1) のナイキスト軌跡。G(jω) = K/(1+jω)。実部 K/(1+ω²)、虚部 -Kω/(1+ω²)。ω:0→∞ で半円を描き、-1 を囲まないため安定（任意の K>0 で）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ナイキスト判別',
      content: 'ナイキスト軌跡が -1 点を時計回りに1回囲んだ。開ループに右半面の極がない場合、閉ループは？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'N=-1（時計回りに1回）、P=0 のとき、閉ループの右半面の極数 Z はいくつか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'Z = 0（安定）', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'Z = 1（不安定）', correct: false },
        ],
        explanation: 'Z = P - N = 0 - (-1) = 1。閉ループに1つの右半面の極があるため不安定。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'ボーデ線図との関係',
      content: 'ナイキスト線図とボーデ線図は同じ周波数応答の異なる表現。ボーデはゲインと位相を分離表示するため設計に便利。ナイキストは安定性判別に直接使える。両者を使い分けるのが実践的。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'ナイキスト線図で安定性判定',
      content: '複数のナイキスト線図が表示される。-1 点との位置関係を判断して安定性を判定しよう。周回数を正確に数える練習。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'nyquist-plot-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
