import { Tutorial } from '../types';

export const periodicTransformTutorial: Tutorial = {
  id: 'periodic-transform',
  title: '周期関数のラプラス変換',
  description: '周期 T の関数に対するラプラス変換公式を導出し活用する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '繰り返す波形',
      content: '矩形波や鋸歯状波のような周期関数が無限に繰り返される様子を表示し、1周期分の変換から全体の変換が得られることをアニメーションで示す。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '周期を変えて確認',
      content: '矩形波の周期 T をスライダーで変え、ラプラス変換 F₁(s)/(1-e^{-Ts}) の値がどう変化するかを観察しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '周期関数の変換公式',
      content: 'f(t+T) = f(t) の場合、L{f(t)} = F₁(s)/(1-e^{-Ts})。F₁(s) = ∫₀^T f(t)e^{-st}dt は1周期分の積分。等比級数の和 1+e^{-Ts}+e^{-2Ts}+... = 1/(1-e^{-Ts}) から導出される。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '矩形波の変換',
      content: '振幅 1、周期 2a の矩形波（0<t<a で 1、a<t<2a で -1）。F₁(s) = (1-e^{-as})²/[s(1+e^{-as})] を簡約して L{f} = (1/s)·tanh(as/2)。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '周期関数の変換',
      content: '周期 T の関数の変換公式で正しいものはどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: '周期 T の関数 f(t) のラプラス変換で正しい公式はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'L{f} = F₁(s)·e^{-Ts}', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'L{f} = F₁(s)/(1-e^{-Ts})', correct: false },
        ],
        explanation: '周期関数のラプラス変換は1周期分の変換 F₁(s) を 1/(1-e^{-Ts}) で割ったものになる。これは幾何級数の和から導かれる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'フーリエ級数との関係',
      content: '周期関数はフーリエ級数に展開できる。各調和成分のラプラス変換を取ることもできるが、上記の公式の方が直接的で効率的。フーリエ変換は定常状態、ラプラス変換は過渡状態の解析に適する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '周期信号を変換しよう',
      content: '様々な周期波形（三角波、鋸歯状波、半波整流）が出題される。1周期分の積分を計算し、周期公式を適用して完全な変換を求めよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
