import { Tutorial } from '../types';

export const pidControlTutorial: Tutorial = {
  id: 'pid-control',
  title: 'PID制御',
  description: '比例・積分・微分制御の仕組みをラプラス変換で理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'P・I・D の3つの力',
      content: '目標温度に向かうヒーター制御を例に、P（現在の誤差に比例）、I（過去の誤差を積算）、D（誤差の変化率）の3要素がそれぞれどう貢献するかをアニメーション表示。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'PIDゲインを調整しよう',
      content: 'Kp, Ki, Kd の3つのスライダーを動かして、ステップ応答のオーバーシュート、整定時間、定常偏差を改善しよう。最適なバランスを見つける。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'PID制御器の伝達関数',
      content: 'C(s) = Kp + Ki/s + Kd·s = (Kd·s² + Kp·s + Ki)/s。P項は即応性、I項は定常偏差の除去、D項は振動の抑制を担う。s 領域で統一的に表現できる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '1次プラントのPID制御',
      content: 'プラント G(s) = 1/(s+1) にPID制御器 C(s) を適用。閉ループ伝達関数 T(s) = C·G/(1+C·G)。Kp=10, Ki=5, Kd=2 のとき T(s) = (2s²+10s+5)/(s²+(1+2s²+10s+5)/s) と簡約される。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'PID制御の効果',
      content: 'P制御のみで定常偏差が残るとき、追加すべき要素はどれか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'P制御のみで定常偏差が残る場合、それを解消するために追加すべき要素は？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'D制御（微分）のみ', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'I制御（積分）のみ', correct: false },
        ],
        explanation: 'I制御は誤差を時間積分するため、定常偏差があるかぎり制御入力が増え続け、最終的に偏差を 0 にする。D制御は応答速度改善に効果があるが定常偏差は除去できない。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'PIDチューニング手法',
      content: 'ジーグラー・ニコルスの限界感度法：Kp のみで振動が持続する限界ゲイン Ku と限界周期 Tu を求め、Kp=0.6Ku, Ki=Kp/(0.5Tu), Kd=Kp·0.125Tu とする経験的手法。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'PID制御設計チャレンジ',
      content: '与えられた仕様（オーバーシュート10%以下、整定時間2秒以内、定常偏差0）を満たすPIDゲインを見つけよう。試行錯誤で最適なパラメータを探る。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
