import { Tutorial } from '../types';

export const poleZerosTutorial: Tutorial = {
  id: 'poles-zeros',
  title: '極と零点',
  description: '伝達関数の極と零点がシステムの振る舞いを決める仕組みを理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '複素平面上の極と零点',
      content: 'G(s) = (s+1)/[(s+2)(s+3)] の極（×印）と零点（○印）が複素平面上にプロットされ、対応する時間応答が同時に表示されるアニメーション。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '極をドラッグして動かそう',
      content: '複素平面上の極の位置をドラッグして移動させ、時間応答がリアルタイムで変化する様子を観察しよう。左半面の極は安定、右半面は不安定を体感する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '極の位置と時間応答',
      content: '実軸上の極 s=-a: e^{-at}（減衰）。虚軸上の極 s=±jω: sin(ωt), cos(ωt)（振動）。複素極 s=-a±jω: e^{-at}sin(ωt)（減衰振動）。極の実部が減衰率、虚部が振動周波数を決める。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '零点の効果',
      content: '零点は特定の周波数成分を打ち消す効果がある。G(s)=(s+z)/[(s+p₁)(s+p₂)] の零点 s=-z が極 s=-p₁ に近いと、対応するモードの振幅が小さくなる。零点は応答の形状を修正する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '極の位置と安定性',
      content: 'G(s) = 1/(s²-4) の極を求め、安定性を判定せよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'G(s) = 1/(s²-4) の極と安定性について正しいものはどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '極は s=±2、安定', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '極は s=±2、不安定', correct: false },
        ],
        explanation: 's²-4=0 → s=±2。s=2 は右半面にあるため不安定。インパルス応答に e^{2t} の項が含まれ発散する。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '支配極の概念',
      content: '複数の極があるとき、虚軸に最も近い極（最も減衰が遅い極）が応答を支配する。これを支配極と呼ぶ。高次システムの解析では支配極に着目することで近似的な理解が得られる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '極・零点マップから応答を予測',
      content: '与えられた極・零点マップから時間応答の概形を予測し、正解と比較しよう。極の位置から減衰率や振動周波数を読み取る練習。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
