import { Tutorial } from '../types';

export const robotControlTutorial: Tutorial = {
  id: 'robot-control',
  title: 'ロボット制御',
  description: 'ロボットアームの関節制御をラプラス変換で解析する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'ロボットアームの動き',
      content: 'ロボットアームの1関節が目標角度に滑らかに移動する様子をアニメーションで表示。オーバーシュートや振動を抑えた制御が求められる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'robot-control-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '関節の応答を制御',
      content: 'ロボットアームの関節モデル（慣性モーメント J、粘性 B）のパラメータとPIDゲインを調整し、滑らかな位置決めを実現しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'robot-control-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '1リンクアームのモデル',
      content: 'J·θ″ + B·θ′ + mgl·sin(θ) = τ。sin(θ) ≈ θ と線形化すると G(s) = Θ(s)/T(s) = 1/(Js² + Bs + mgl)。2次系の標準形に帰着し、ωn = √(mgl/J)、ζ = B/(2√(Jmgl))。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '重力補償付き制御',
      content: '重力項 mgl·sin(θ) をフィードフォワードで補償すると、残る動力学は J·θ″ + B·θ′ = τ′。G(s) = 1/(Js² + Bs) = 1/[s(Js+B)]。積分器を含むため、位置制御が可能になる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ロボット制御の理解',
      content: '線形化したロボットアームモデルの固有振動数を高くするにはどうすればよいか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'ωn = √(mgl/J) を大きくする方法として正しいものはどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '慣性モーメント J を大きくする', correct: false },
          { id: 'c', label: 'b', correct: true },
          { id: 'd', label: 'アームの質量 m を減らす', correct: false },
        ],
        explanation: 'ωn = √(mgl/J) なので、分子を大きくするか分母を小さくすればよい。g を大きくする（物理的には困難だが）と ωn は増加する。実用的には J を減らすかリンク設計を変更する。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '多関節ロボットへの拡張',
      content: '多関節ロボットは非線形連成系だが、各関節を局所的に線形化し独立にラプラス解析できる。計算トルク法では非線形項を補償し、各軸を独立の線形系として制御する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'ロボットアームを制御しよう',
      content: '仮想ロボットアームの目標軌道追従制御を設計しよう。制御ゲインを調整して、滑らかで正確な動作を実現する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'robot-control-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
