import { Tutorial } from '../types';

export const routhHurwitzTutorial: Tutorial = {
  id: 'routh-hurwitz',
  title: 'ラウス・フルビッツの安定判別',
  description: '根を求めずに安定性を判別するラウス表の作り方と使い方を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '根を求めずに安定性を知る',
      content: '高次の特性方程式の根を直接求めるのは困難。ラウス表を構成するだけで、右半面の根の数が分かる驚きのアルゴリズムをアニメーションで紹介。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'routh-hurwitz-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'ラウス表を作ってみよう',
      content: '特性方程式の係数を入力すると、ラウス表が1行ずつ構築される。各行の第1列の符号変化を確認して、右半面の根の数を求めよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'routh-hurwitz-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'ラウス表の構成法',
      content: '特性多項式 aₙsⁿ+aₙ₋₁sⁿ⁻¹+...+a₀ に対し、第1行は aₙ, aₙ₋₂, aₙ₋₄,...、第2行は aₙ₋₁, aₙ₋₃,...。以降の行は交差積で計算する。第1列の符号変化の数が右半面の根の数。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '具体例：s³+2s²+3s+6',
      content: '行1: [1, 3]、行2: [2, 6]、行3: [(2·3-1·6)/2, 0] = [0, 0]。第1列に 0 が現れる特殊ケース。補助多項式 2s²+6 を微分して 4s を使い判定を続ける。虚軸上に根がある。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ラウス判別法の適用',
      content: 's³+4s²+5s+2=0 の安定性をラウス表で判定せよ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 's³+4s²+5s+2=0 のラウス表で第1列の符号変化は何回か？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: '0回（安定）', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '1回（不安定）', correct: false },
        ],
        explanation: '行1:[1,5]、行2:[4,2]、行3:[(4·5-1·2)/4,0]=[18/4,0]=[4.5,0]、行4:[2]。第1列は 1,4,4.5,2 で全て正。符号変化 0 回 → 安定。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '特殊ケースの扱い',
      content: 'ラウス表で第1列に 0 が現れる場合は ε 置換法を使う。行全体が 0 になる場合は補助多項式を微分して代用する。これらの特殊ケースは虚軸上の根や対称根の存在を示す。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'ラウス表を完成させよう',
      content: '与えられた特性方程式に対してラウス表の空欄を埋め、安定性を判定する練習問題に挑戦しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'routh-hurwitz-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
