import { Tutorial } from '../types';

export const sDomainStabilityTutorial: Tutorial = {
  id: 's-domain-stability',
  title: 's領域での安定性',
  description: '極の位置とシステム安定性の関係を s 平面で理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '安定・不安定・臨界安定',
      content: '左半面の極（安定：減衰）、右半面の極（不安定：発散）、虚軸上の極（臨界安定：持続振動）の3つのケースを同時にアニメーション表示する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 's-domain-stability-animation',
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '極を移動させて安定性を確認',
      content: '複素平面上の極をドラッグして移動させ、対応する時間応答がリアルタイムで変化する様子を観察。虚軸をまたぐと安定↔不安定が切り替わる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 's-domain-stability-interactive',
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'BIBO安定性の条件',
      content: '有界入力・有界出力（BIBO）安定であるためには、伝達関数のすべての極が複素平面の左半面（Re(s)<0）にあることが必要十分条件。特性方程式のすべての根の実部が負であればよい。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '特性方程式の分析例',
      content: 's³+6s²+11s+6=0 を因数分解すると (s+1)(s+2)(s+3)=0。すべての根 s=-1,-2,-3 は左半面にあるため安定。一方 s³+s²-2s=0 → s(s+2)(s-1)=0 は s=1 が右半面にあり不安定。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '安定性の判定',
      content: '特性方程式 s²+2s+5=0 のシステムは安定か？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 's²+2s+5=0 の根をもつシステムの安定性はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '不安定（発散する）', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '安定（減衰振動する）', correct: false },
        ],
        explanation: '根は s = -1±2j。実部が -1 < 0 なのですべて左半面にあり、安定。応答は e^{-t}sin(2t) 型の減衰振動となる。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '安定余裕の概念',
      content: '安定性の度合いを定量化するのがゲイン余裕と位相余裕。極が虚軸からどれだけ離れているかが安定性の「余裕」を表す。設計では十分な余裕を確保する必要がある。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '安定性判定の練習',
      content: '与えられた特性方程式からすべての根を求め、s 平面にプロットして安定性を判定しよう。根の実部の符号に注目する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 's-domain-stability-summary',
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
