import { Tutorial } from '../types';

export const servoMotorTutorial: Tutorial = {
  id: 'servo-motor',
  title: 'サーボモーター制御',
  description: 'サーボモーターの位置・速度制御をラプラス変換で解析する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'モーターが目標角度に向かう',
      content: 'サーボモーターが指令角度に向かって回転し、オーバーシュートしながら収束する様子をアニメーション表示。制御系の応答が目に見える。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'モーターパラメータを調整',
      content: 'モーターのイナーシャ J と粘性摩擦 B をスライダーで変え、ステップ応答の変化を観察しよう。重いモーターと軽いモーターの違いを体感する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: 'DCモーターの伝達関数',
      content: 'DCモーターの運動方程式: J·θ″ + B·θ′ = K·i(t)。電気回路: L·di/dt + R·i = V - K·θ′。ラプラス変換して整理すると G(s) = Θ(s)/V(s) = K/[s(JLs² + (JR+BL)s + BR+K²)]。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '簡略化モデルでの制御',
      content: '電気時定数が機械時定数より十分小さい場合、G(s) ≈ Km/[s(τm·s+1)]。Km はモーターゲイン、τm は機械時定数。この2次系モデルでPID制御を設計する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'モーター制御の理解',
      content: 'モーターの角度制御で伝達関数に 1/s が含まれる理由は？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'DCモーターの角度制御で G(s) に 1/s の因子がある理由として正しいのはどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '電気回路のインダクタンス成分', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '角速度から角度への積分関係', correct: false },
        ],
        explanation: '角度 θ は角速度 ω の積分: θ = ∫ω dt。ラプラス変換では Θ(s) = Ω(s)/s。この 1/s が角速度→角度の積分を表す。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'カスケード制御',
      content: 'サーボモーターでは電流ループ（最内側）→ 速度ループ → 位置ループ（最外側）のカスケード制御がよく使われる。内側のループから順に設計し、帯域幅を段階的に下げていく。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'サーボ系を設計しよう',
      content: '目標角度への追従と外乱抑制を両立するサーボ系を設計しよう。PIDゲインとフィルタパラメータを調整して仕様を満たす。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
