import { Tutorial } from '../types';

export const solveIvpTutorial: Tutorial = {
  id: 'solve-ivp',
  title: '初期値問題を解く',
  description: 'ラプラス変換を使って初期値問題（IVP）を系統的に解く手順を学ぶ',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '4ステップで解く',
      content: '① 変換 → ② 代数操作 → ③ 部分分数分解 → ④ 逆変換。この4ステップで初期値問題が解ける流れをフローチャートアニメーションで表示する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '初期条件を変えてみよう',
      content: 'y″+y=0 の初期条件 y(0) と y′(0) をスライダーで変えながら、解 y(t) の波形がどう変化するかを観察しよう。振幅と位相が初期条件で決まることを体感する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '例題：y″+3y′+2y=0',
      content: '初期条件 y(0)=1, y′(0)=0。変換: (s²+3s+2)Y = s+3。Y = (s+3)/[(s+1)(s+2)] = 2/(s+1) - 1/(s+2)。逆変換: y(t) = 2e^{-t} - e^{-2t}。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '非斉次方程式の例',
      content: 'y′+2y=e^{-t}, y(0)=1。変換: (s+2)Y-1 = 1/(s+1)。Y = 1/(s+2) + 1/[(s+1)(s+2)] = 1/(s+2) + 1/(s+1) - 1/(s+2) = 1/(s+1)。逆変換: y(t) = e^{-t}。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '初期値問題',
      content: 'y′-y=0, y(0)=3 の解を選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'y′-y=0, y(0)=3 の解はどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: 'y(t) = 3e^{-t}', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'y(t) = 3e^{t}', correct: false },
        ],
        explanation: '変換: sY-3-Y=0 → (s-1)Y=3 → Y=3/(s-1)。逆変換: y(t)=3e^{t}。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '連立微分方程式への拡張',
      content: 'ラプラス変換は連立微分方程式にも適用できる。各方程式を変換して連立代数方程式にし、クラメルの公式や掃き出し法で各未知関数の Y(s) を求め、それぞれ逆変換する。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'IVP解法の全手順を実践',
      content: '微分方程式と初期条件が与えられる。変換 → 整理 → 部分分数分解 → 逆変換の各ステップを穴埋め形式で完成させ、解を求めよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
