import { Tutorial } from '../types';

export const stepResponseTutorial: Tutorial = {
  id: 'step-response',
  title: 'ステップ応答',
  description: 'システムにステップ入力を加えたときの応答特性を分析する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'スイッチを入れた瞬間',
      content: 't=0 でスイッチが ON になり、システムが定常状態へ向かう過程をアニメーションで表示する。オーバーシュート、立ち上がり時間、整定時間が可視化される。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: 'ダンピング比を変えてみよう',
      content: '2次系 G(s) = ωn²/(s²+2ζωns+ωn²) のダンピング比 ζ をスライダーで変え、ステップ応答の波形変化を観察しよう。ζ < 1 で振動的、ζ = 1 で臨界制動、ζ > 1 で過制動。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '1次系のステップ応答',
      content: 'G(s) = 1/(τs+1) のステップ応答: Y(s) = 1/[s(τs+1)]。逆変換: y(t) = 1-e^{-t/τ}。時定数 τ 後に約63%に達し、4τ 後にほぼ定常値。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '2次系のステップ応答',
      content: 'ζ < 1 のとき、ステップ応答は y(t) = 1 - (e^{-ζωnt}/√(1-ζ²))·sin(ωd·t+φ)。ωd = ωn√(1-ζ²) は減衰振動周波数。オーバーシュート量は Mp = e^{-πζ/√(1-ζ²)}。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ステップ応答の特性',
      content: 'ζ=0.5, ωn=4 のときのオーバーシュート量に最も近い値を選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'ζ=0.5 のときのオーバーシュート量 Mp は約何%か？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '約 5%', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '約 16%', correct: false },
        ],
        explanation: 'Mp = e^{-πζ/√(1-ζ²)} = e^{-π·0.5/√0.75} = e^{-1.814} ≈ 0.163 = 約16%。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'ステップ応答の仕様と設計',
      content: '制御工学では、立ち上がり時間 tr、整定時間 ts、オーバーシュート Mp などの仕様が与えられる。これらの仕様を満たす ζ と ωn を決定することが制御系設計の出発点となる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '仕様からパラメータを決めよう',
      content: '要求されるオーバーシュート量と整定時間から、ζ と ωn を求める練習をしよう。スライダーで調整して仕様範囲内に収める。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
