import { Tutorial } from '../types';

export const transferFunctionTutorial: Tutorial = {
  id: 'transfer-function',
  title: '伝達関数',
  description: 'システムの入出力関係を s 領域で記述する伝達関数を理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: 'ブラックボックスとしてのシステム',
      content: '入力 U(s) がブラックボックス G(s) を通って出力 Y(s) = G(s)·U(s) になる様子をアニメーションで表示する。伝達関数はシステムの「性格」を表す。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '伝達関数のパラメータを変える',
      content: '1次系 G(s) = K/(τs+1) のゲイン K と時定数 τ をスライダーで変え、ステップ入力に対する出力波形の変化を観察しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '伝達関数の定義',
      content: '初期条件がすべて 0 のとき、伝達関数 G(s) = Y(s)/U(s)。例：m·y″+c·y′+k·y = u(t) → G(s) = 1/(ms²+cs+k)。分母多項式を特性多項式と呼ぶ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: '伝達関数から時間応答を求める',
      content: 'G(s) = 1/(s+2) にステップ入力 U(s) = 1/s を加えると Y(s) = 1/[s(s+2)] = 1/(2s) - 1/(2(s+2))。逆変換: y(t) = (1-e^{-2t})/2。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: '伝達関数の理解',
      content: 'G(s) = 10/(s+5) のインパルス応答を選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'G(s) = 10/(s+5) にインパルス入力（U(s)=1）を加えたときの出力 y(t) はどれか？',
        options: [
          { id: 'a', label: 'a', correct: true },
          { id: 'b', label: 'y(t) = 10e^{-5t}', correct: false },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: 'y(t) = 2(1-e^{-5t})', correct: false },
        ],
        explanation: 'Y(s) = G(s)·1 = 10/(s+5)。逆変換: y(t) = 10e^{-5t}。インパルス応答は伝達関数の逆変換そのもの。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: 'ブロック線図の結合則',
      content: '直列接続: G = G₁·G₂。並列接続: G = G₁+G₂。フィードバック接続: G = G₁/(1+G₁·G₂)。ブロック線図を使うとシステム全体の伝達関数を組み立てられる。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: 'ブロック線図を組み立てよう',
      content: 'ブロック要素をドラッグ＆ドロップで配置し、指定された全体伝達関数を実現するブロック線図を組み立てよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
