import { Tutorial } from '../types';

export const whyLaplaceTutorial: Tutorial = {
  id: 'why-laplace',
  title: 'なぜラプラス変換？',
  description: '微分方程式を代数方程式に変える魔法のような変換の動機を理解する',
  category: 'laplace',
  steps: [
    {
      id: 'hook',
      stepType: 'animation',
      title: '微分方程式 vs 代数方程式',
      content: 'バネ・ダンパ系の運動方程式 m·x″ + c·x′ + k·x = F(t) を直接解くのは難しい。しかしラプラス変換を使えば、s の多項式に変わり簡単に解ける。この変換の威力をアニメーションで体感しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'touch',
      stepType: 'interactive',
      title: '時間領域とs領域を行き来する',
      content: '左側に時間領域の信号 f(t) = e^{-at}、右側にラプラス変換 F(s) = 1/(s+a) が表示される。パラメータ a を動かして、時間領域での減衰の速さと s 領域での極の位置の関係を確認しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
    {
      id: 'example-1',
      stepType: 'explanation',
      title: '微分方程式を解く従来の方法',
      content: '2階線形微分方程式 y″ + 3y′ + 2y = 0 を特性方程式で解く方法を振り返る。特性方程式 r² + 3r + 2 = 0 → (r+1)(r+2) = 0 → y = C₁e^{-t} + C₂e^{-2t}。初期条件の適用が手間になる場合がある。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'example-2',
      stepType: 'explanation',
      title: 'ラプラス変換で同じ問題を解く',
      content: '同じ方程式にラプラス変換を適用する。s²Y(s) - sy(0) - y′(0) + 3[sY(s) - y(0)] + 2Y(s) = 0。初期条件を代入するだけで Y(s) が求まり、逆変換で y(t) が得られる。初期条件の処理が自然に組み込まれるのがラプラス変換の強みだ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'predict',
      stepType: 'quiz',
      title: 'ラプラス変換の利点は？',
      content: 'ラプラス変換の最大の利点として正しいものを選べ。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      quiz: {
        question: 'ラプラス変換の最大の利点として最も適切なものはどれか？',
        options: [
          { id: 'a', label: 'a', correct: false },
          { id: 'b', label: '関数をフーリエ級数に展開できる', correct: true },
          { id: 'c', label: 'b', correct: false },
          { id: 'd', label: '微分方程式を代数方程式に変換し、初期条件も自然に扱える', correct: false },
        ],
        explanation: 'ラプラス変換は微分・積分演算を s の乗算・除算に置き換え、初期条件も変換式に自然に含まれるため、線形微分方程式を効率的に解ける。',
      },
    },
    {
      id: 'alternate',
      stepType: 'explanation',
      title: '工学での活用場面',
      content: 'ラプラス変換は制御工学、電気回路解析、信号処理など幅広い分野で使われる。伝達関数という概念を通じて、システムの入出力関係を簡潔に記述できる。回路のインピーダンスも s 領域で統一的に扱える。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
    },
    {
      id: 'summary',
      stepType: 'interactive',
      title: '変換の流れを体験',
      content: '微分方程式 → ラプラス変換 → 代数方程式 → 解を求める → 逆ラプラス変換 → 時間領域の解。この一連のフローをドラッグ＆ドロップで並べ替え、正しい手順を確認しよう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
    },
  ],
};
