import { Tutorial } from '../types';

export const aStarGraphTutorial: Tutorial = {
  id: 'a-star-graph',
  title: 'A*アルゴリズムとグラフ',
  description: 'ヒューリスティクスを活用した効率的な最短経路探索を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '賢い探索',
      content: 'ダイクストラ法は全方向に均等に探索しますが、目的地の方向がわかっていれば？\n\nA*アルゴリズムはヒューリスティクスで探索を効率化します。\n\nA*がダイクストラ法より少ない探索で最短経路を見つける様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ヒューリスティクスを試そう',
      content: '始点と終点を選んで A* を実行してみましょう。\n\nヒューリスティクス関数を変えると探索効率が変わります。\n\nダイクストラ法と比較して探索されるノード数を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'A*の仕組み',
      content: 'A*は各ノードの評価関数 f(v) で優先順位を決めます。\n\nf(v) = g(v) + h(v)\n- g(v)：始点からvまでの実際のコスト\n- h(v)：vから目標までの推定コスト（ヒューリスティクス）\n\nh(v) が許容的（過大評価しない）なら最適解を保証します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '許容的ヒューリスティクス',
      content: '許容的（admissible）：h(v) ≤ h*(v)（実際の最短距離以下）\n\n例：\n- ユークリッド距離：直線距離は最短距離以下\n- マンハッタン距離：格子状グラフで許容的\n\n整合的（consistent）：h(u) ≤ w(u,v) + h(v) なら、ノードの再訪問が不要になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'A*アルゴリズムが最適解を保証するために、ヒューリスティクス関数に必要な条件は？',
        options: [
          { id: 'a', label: '常に0であること', correct: false },
          { id: 'b', label: '実際の最短距離以下であること（許容的）', correct: true },
          { id: 'c', label: '実際の最短距離と等しいこと', correct: false },
          { id: 'd', label: '常に定数であること', correct: false },
        ],
        explanation: 'ヒューリスティクスが許容的（過大評価しない）であれば、A*は最適な最短経路を見つけることが保証されます。',
      },
    },
    {
      id: 'alternate',
      title: 'IDA*とその他の変種',
      content: 'A*はメモリを大量に使うため、メモリ制約のある場合：\n\n- IDA*：反復深化＋A*で線形メモリ\n- SMA*：メモリ制限付きA*\n- 双方向A*：始点と終点の両方から探索\n\nカーナビのルート検索では A* の変種が広く使われています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. A*はヒューリスティクスで探索を効率化\n2. f(v) = g(v) + h(v) で優先順位を決定\n3. 許容的ヒューリスティクスが最適性を保証\n\nA*の探索を操作して効率を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
