import { Tutorial } from '../types';

export const anomalyDetectionTutorial: Tutorial = {
  id: 'anomaly-detection',
  title: '異常検知とグラフ',
  description: 'グラフ構造の異常パターンを検出する手法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '異常を見つけ出す',
      content: '金融取引ネットワークで不正を検出、SNSでボットアカウントを発見——グラフの異常検知は重要な応用です。\n\nグラフ上の異常パターンが強調されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'anomaly-detection-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '異常ノードを見つけよう',
      content: 'ネットワーク内で通常と異なる振る舞いをするノードを見つけましょう。\n\n次数、クラスタリング係数、中心性などの特徴量に注目してください。\n\n異常なノードはどのような特徴を持っていますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'anomaly-detection-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフ上の異常の種類',
      content: 'グラフにおける異常の種類：\n\n- 異常ノード：通常と異なる接続パターンの頂点\n- 異常辺：予期しないつながり\n- 異常サブグラフ：不自然な構造（クリーク、星型など）\n- 時間的異常：突然の変化\n\nそれぞれ異なる検出アプローチが必要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '検出手法',
      content: 'グラフ異常検出手法：\n\n- 構造的特徴量：次数分布、クラスタリング係数の異常\n- OddBall：自我ネットワークのパターンで異常検出\n- DOMINANT：GNNベースの異常検出（再構成誤差）\n- スペクトル法：ラプラシアンの固有値異常\n\n教師なし学習が多いのが特徴です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'グラフ異常検知で「教師なし学習」が多い理由は？',
        options: [
          { id: 'a', label: '教師データが不要で簡単だから', correct: false },
          { id: 'b', label: '異常データの正解ラベルが少なく入手困難だから', correct: true },
          { id: 'c', label: '教師あり学習では精度が出ないから', correct: false },
          { id: 'd', label: 'グラフデータには教師あり学習が使えないから', correct: false },
        ],
        explanation: '実際の異常（不正、ボット等）のラベル付きデータは非常に少なく入手困難なため、教師なし学習アプローチが多く使われます。',
      },
    },
    {
      id: 'alternate',
      title: '不正検知の実例',
      content: 'グラフ異常検知の実例：\n\n- クレジットカード不正：取引グラフの異常パターン\n- マネーロンダリング：資金移動ネットワークの不自然な循環\n- ボット検知：SNSでの異常な接続パターン\n\nグラフの構造を活用することで、個別のトランザクション分析では見つけられない不正を検出できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフ異常検知はノード・辺・サブグラフレベルがある\n2. 構造的特徴量やGNNで検出\n3. 不正検知やセキュリティに応用\n\n異常パターンを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'anomaly-detection-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
