import { Tutorial } from '../types';

export const bfsApplicationsTutorial: Tutorial = {
  id: 'bfs-applications',
  title: 'BFSの応用',
  description: '幅優先探索の応用例と実装パターンを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '波紋のように広がる探索',
      content: 'BFS（幅優先探索）は始点から波紋のように広がります。\n\n近い頂点から順に探索するため、最短距離の計算に最適です。\n\nBFSの探索順が波のように広がるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'BFSを実行してみよう',
      content: '始点を選んでBFSを実行してみましょう。\n\nキューに入る順番と、各頂点が発見される距離を観察してください。\n\n同じ距離の頂点は同じ「層」に属します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'BFSの応用：最短距離',
      content: '重みなしグラフでの最短距離をBFSで求められます。\n\n応用例：\n- 迷路の最短解法\n- SNSでの「知り合いの知り合い」の距離\n- ネットワークのホップ数計算\n\nすべて O(V+E) で解けます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'BFSの応用：二部グラフ判定',
      content: 'BFSで二部グラフの判定ができます。\n\n方法：BFSの各層に交互に2色を割り当て、同じ層内で辺があれば二部グラフでない\n\nまた、連結成分の列挙にもBFSは使えます。\n\n多始点BFS（複数の始点から同時に開始）は0-1BFSの基礎にもなります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'BFSで使用するデータ構造はどれですか？',
        options: [
          { id: 'a', label: 'スタック', correct: false },
          { id: 'b', label: 'キュー', correct: true },
          { id: 'c', label: '優先度キュー', correct: false },
          { id: 'd', label: '配列', correct: false },
        ],
        explanation: 'BFSはキュー（FIFO）を使います。先に発見された頂点から順に処理することで、近い頂点を先に探索します。',
      },
    },
    {
      id: 'alternate',
      title: '0-1 BFS',
      content: '辺の重みが0か1のグラフでは、通常のBFSを拡張した0-1 BFSが使えます。\n\n重み0の辺はキューの先頭に、重み1の辺はキューの末尾に追加します（両端キュー使用）。\n\nダイクストラ法より高速で、O(V+E) で最短経路が求まります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. BFSは重みなしグラフの最短距離を求める\n2. 二部グラフ判定、連結成分列挙にも応用可能\n3. 0-1 BFSで重み0/1のグラフにも拡張できる\n\nBFSの探索を操作して動作を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
