import { Tutorial } from '../types';

export const biologicalNetworkTutorial: Tutorial = {
  id: 'biological-network',
  title: '生物ネットワーク',
  description: 'タンパク質相互作用や代謝ネットワークのグラフ解析を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '生命をグラフで理解する',
      content: 'タンパク質の相互作用、遺伝子の制御関係、代謝経路——生物学はグラフで溢れています。\n\nグラフ理論は生命科学の重要なツールです。\n\n生物ネットワークの構造を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'biological-network-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '生物ネットワークを探索しよう',
      content: 'タンパク質相互作用ネットワーク（PPI）を探索しましょう。\n\nハブタンパク質やモジュール構造を見つけてください。\n\n中心性の高いタンパク質は生存に重要なことが多いです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'biological-network-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'タンパク質相互作用ネットワーク',
      content: 'PPI（Protein-Protein Interaction）ネットワーク：\n\n- ノード：タンパク質\n- エッジ：物理的な相互作用\n\n特徴：\n- スケールフリー性\n- 高いモジュラリティ（機能モジュール）\n- ハブタンパク質は必須遺伝子に対応することが多い',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '遺伝子制御ネットワーク',
      content: '遺伝子制御ネットワーク（GRN）：\n\n- ノード：遺伝子\n- エッジ：制御関係（活性化/抑制）\n- 有向グラフ\n\nモチーフ（頻出パターン）：\n- フィードフォワードループ\n- 自己制御ループ\n\nこれらのモチーフは生物学的機能に対応しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'タンパク質相互作用ネットワークのハブタンパク質はどのような特徴がありますか？',
        options: [
          { id: 'a', label: '相互作用が少ない', correct: false },
          { id: 'b', label: '生存に不可欠な場合が多い', correct: true },
          { id: 'c', label: 'ネットワークの端に位置する', correct: false },
          { id: 'd', label: 'すべて同じ機能を持つ', correct: false },
        ],
        explanation: 'ハブタンパク質は多くの相互作用を持ち、ノックアウト（除去）すると生存に影響することが多いため、必須タンパク質である可能性が高いです。',
      },
    },
    {
      id: 'alternate',
      title: '薬物標的の発見',
      content: 'グラフ解析による薬物ターゲットの発見：\n\n- ネットワーク薬理学：疾病遺伝子とPPIの関係からターゲットを特定\n- ドラッグリポジショニング：既存薬の新しい適用を予測\n- GNNによる分子特性予測：分子グラフから薬効を予測\n\nグラフ理論が創薬を加速しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 生物学はグラフで溢れている（PPI、GRN、代謝）\n2. ハブやモチーフが生物学的機能に対応\n3. 創薬にグラフ解析が活用されている\n\n生物ネットワークを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'biological-network-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
