import { Tutorial } from '../types';

export const bipartiteGraphTutorial: Tutorial = {
  id: 'bipartite-graph',
  title: '二部グラフ',
  description: '頂点を2つのグループに分け、グループ間のみに辺があるグラフを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '2つのチームの関係',
      content: '求人サイトでは「企業」と「求職者」の2グループがあり、応募関係でつながっています。\n\nこのように2つのグループ間の関係を表すのが二部グラフです。\n\n頂点が2色に分かれるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '二部グラフか判定しよう',
      content: '頂点を2色で塗り分けてみましょう。\n\n隣接する頂点が同じ色にならなければ二部グラフです。\n\n奇数長のサイクルがあると二部グラフにはなれません。確認してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '二部グラフの定義',
      content: '二部グラフ G = (U ∪ V, E) は、頂点集合を U と V に分割し、辺は U と V の間のみに存在するグラフです。\n\n同じグループ内の頂点同士は辺で結ばれません。\n\n判定条件：グラフが二部グラフ ⟺ 奇数長のサイクルを含まない',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '二部グラフの応用',
      content: '二部グラフの具体例：\n\n- 学生と授業の履修関係\n- ユーザーと商品の購入関係\n- 労働者とタスクの割り当て\n\nこれらの問題ではマッチング（最適な対応付け）が重要になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '次のうち二部グラフでないものはどれですか？',
        options: [
          { id: 'a', label: '長さ4のサイクル（C₄）', correct: false },
          { id: 'b', label: '長さ3のサイクル（三角形 C₃）', correct: true },
          { id: 'c', label: '木', correct: false },
          { id: 'd', label: 'パスグラフ', correct: false },
        ],
        explanation: '三角形は長さ3（奇数）のサイクルなので二部グラフではありません。木やパス、偶数長サイクルは二部グラフです。',
      },
    },
    {
      id: 'alternate',
      title: '完全二部グラフ',
      content: '完全二部グラフ K_{m,n} は、U側にm個、V側にn個の頂点があり、すべてのペアが辺で結ばれたグラフです。\n\n辺の数は m×n 本です。\n\nK_{3,3} は平面グラフでないことが知られており、平面性の判定に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 二部グラフは頂点を2グループに分け、グループ間のみ辺がある\n2. 奇数長サイクルがなければ二部グラフ\n3. マッチングなど重要な応用がある\n\n頂点の色分けを試して二部グラフを体感しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
