import { Tutorial } from '../types';

export const bipartiteMatchingFlowTutorial: Tutorial = {
  id: 'bipartite-matching-flow',
  title: '二部マッチングとフロー',
  description: '二部マッチング問題を最大フローで解く方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '完璧な割り当て',
      content: 'すべての学生に異なるプロジェクトを割り当てたい。\n\nこの問題は二部マッチングであり、最大フロー問題として解けます。\n\nフローでマッチングが構成されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'マッチングをフローで解こう',
      content: '二部グラフにソースとシンクを追加して、最大フロー問題に変換しましょう。\n\n各辺の容量を1として、最大フローを求めてください。\n\nフロー値がマッチングの数に対応します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '二部マッチングのフロー変換',
      content: '二部グラフ G=(U∪V, E) に対して：\n\n1. ソース s を追加し、U の各頂点へ容量1の辺を張る\n2. V の各頂点からシンク t へ容量1の辺を張る\n3. U→V の辺は容量1\n\nこのネットワークの最大フロー = 最大マッチング',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'ホッパクロフト・カープ法',
      content: '二部マッチング専用の高速アルゴリズムもあります。\n\nホッパクロフト・カープ法は O(E√V) で最大マッチングを求めます。\n\nフロー変換は汎用的ですが、専用アルゴリズムの方が高速な場合があります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '二部グラフの最大マッチングをフローで求めるとき、各辺の容量はいくつに設定しますか？',
        options: [
          { id: 'a', label: '0', correct: false },
          { id: 'b', label: '1', correct: true },
          { id: 'c', label: '頂点数', correct: false },
          { id: 'd', label: '辺数', correct: false },
        ],
        explanation: '各辺の容量を1にすることで、フロー値が一致する辺の数（マッチング数）に対応します。',
      },
    },
    {
      id: 'alternate',
      title: 'ケーニヒの定理との関係',
      content: 'ケーニヒの定理：二部グラフにおいて最大マッチング = 最小頂点被覆\n\n最大フロー最小カット定理と合わせると：\n最大マッチング = 最大フロー = 最小カット = 最小頂点被覆\n\nこれは線形計画法の整数性に基づいています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 二部マッチングは最大フロー問題に帰着できる\n2. 容量1の辺でフロー値=マッチング数\n3. ケーニヒの定理で頂点被覆とも関連する\n\nフロー変換を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
