import { Tutorial } from '../types';

export const circuitDagTutorial: Tutorial = {
  id: 'circuit-dag',
  title: '回路設計とDAG',
  description: 'デジタル回路の設計における有向非巡回グラフの役割を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'チップの中のDAG',
      content: 'CPUやGPUの中では、論理ゲートがDAG（有向非巡回グラフ）として接続されています。\n\n信号は入力から出力へ一方向に流れ、サイクルはありません。\n\n論理回路が信号を処理する様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '論理回路を組もう',
      content: 'AND、OR、NOTゲートを組み合わせて論理回路を構成しましょう。\n\n入力値を変えて出力がどう変わるか観察してください。\n\n回路はDAGとして表現されています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '組合せ論理回路とDAG',
      content: '組合せ論理回路はDAGで表現されます。\n\n- 入力：入次数0のノード\n- 出力：出次数0のノード\n- ゲート：内部ノード\n\nトポロジカルソート順に評価すれば、正しい出力が得られます。\n\nクリティカルパス（最長パス）が回路の遅延を決定します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'クリティカルパス解析',
      content: 'クリティカルパス：DAGの最長パス\n\n回路のタイミング解析ではクリティカルパスが性能のボトルネックです。\n\n最長パスはトポロジカルソート順にDP（動的計画法）で O(V+E) で求まります。\n\nこれはプロジェクト管理のPERT/CPMと同じ手法です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '組合せ論理回路で性能のボトルネックを決めるのは？',
        options: [
          { id: 'a', label: '最短パス', correct: false },
          { id: 'b', label: 'クリティカルパス（最長パス）', correct: true },
          { id: 'c', label: 'ノードの総数', correct: false },
          { id: 'd', label: '辺の重みの合計', correct: false },
        ],
        explanation: 'クリティカルパス（最長パス）が信号伝播の遅延を決定し、回路全体の性能ボトルネックになります。',
      },
    },
    {
      id: 'alternate',
      title: '順序回路とフィードバック',
      content: '順序回路（フリップフロップを含む）はフィードバックループを持ちますが、クロック単位で見ればDAGです。\n\n各クロックサイクル内では組合せ論理がDAGとして評価され、フリップフロップでクロック境界の値が記憶されます。\n\nパイプライン設計でクリティカルパスを短縮します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. デジタル回路はDAGで表現される\n2. クリティカルパスが性能を決定\n3. トポロジカルソートで正しい評価順序を求める\n\n論理回路を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
