import { Tutorial } from '../types';

export const communityDetectionTutorial: Tutorial = {
  id: 'community-detection',
  title: 'コミュニティ検出',
  description: 'ネットワーク内の密なグループ（コミュニティ）を検出する方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'グループを見つける',
      content: 'SNSには友人グループ、サークル、職場の同僚など自然なグループがあります。\n\nこれらのコミュニティをアルゴリズムで自動検出できるでしょうか？\n\nコミュニティが色分けされるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'community-detection-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'コミュニティを分けよう',
      content: 'ネットワークの頂点をグループに分けて、コミュニティを検出してみましょう。\n\nグループ内の辺が多く、グループ間の辺が少ないのが良い分割です。\n\n最適な分割を見つけてください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'community-detection-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'モジュラリティ',
      content: 'モジュラリティ Q は分割の良さを測る指標です。\n\nQ = (1/2m) Σ [A_{ij} - k_i k_j/(2m)] δ(c_i, c_j)\n\nQ が大きいほど良い分割です。\n\n- Q ≈ 0：ランダム程度\n- Q > 0.3：意味のあるコミュニティ構造',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '検出アルゴリズム',
      content: '代表的なコミュニティ検出アルゴリズム：\n\n- ルーヴァン法：モジュラリティを貪欲に最大化（高速）\n- ギルバン・ニューマン法：辺の媒介中心性でカット\n- ラベル伝播法：隣接頂点のラベルを多数決で伝播\n- スペクトル法：ラプラシアン行列の固有ベクトルを利用',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'モジュラリティQが高い分割はどのような特徴がありますか？',
        options: [
          { id: 'a', label: 'グループ間の辺が多い', correct: false },
          { id: 'b', label: 'グループ内の辺が多くグループ間の辺が少ない', correct: true },
          { id: 'c', label: 'すべてのグループのサイズが等しい', correct: false },
          { id: 'd', label: 'グラフが非連結になる', correct: false },
        ],
        explanation: 'モジュラリティが高い分割は、グループ内の辺密度が高く、グループ間の辺密度が低い状態です。',
      },
    },
    {
      id: 'alternate',
      title: '重なりのあるコミュニティ',
      content: '現実のコミュニティは重なりがあります（1人が複数グループに所属）。\n\n重複コミュニティ検出法：\n- COPRA：ラベル伝播の拡張\n- BigCLAM：確率モデル\n\nまた、階層的なコミュニティ構造も重要で、異なる解像度でのコミュニティを考えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. コミュニティは密なつながりを持つ頂点グループ\n2. モジュラリティで分割の良さを評価\n3. 様々なアルゴリズムで検出可能\n\nコミュニティ分割を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'community-detection-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
