import { Tutorial } from '../types';

export const cycleTreeTutorial: Tutorial = {
  id: 'cycle-tree',
  title: 'サイクルと木',
  description: '閉路（サイクル）を持たない連結グラフ「木」の特別な性質を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '枝分かれするが、輪にならない',
      content: '家族の家系図やフォルダの階層構造を思い浮かべてください。\n\n枝分かれはあるけれど、ぐるっと一周する「輪」はありません。\n\nこのような構造を「木」と呼びます。木が成長するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '辺を追加してサイクルを作ろう',
      content: '木に辺を1本追加すると、必ずサイクルができます。試してみましょう。\n\n逆に、サイクルから辺を1本取り除くと、木に戻ります。\n\nこの関係を体感してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '木の定義と性質',
      content: '木（tree）は、連結でサイクルを持たないグラフです。\n\n木の重要な性質：\n- n頂点の木は必ず n-1 本の辺を持つ\n- 任意の2頂点間に唯一のパスが存在する\n- 辺を1本取り除くと非連結になる\n- 辺を1本追加するとサイクルが生まれる',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'サイクルの検出',
      content: 'サイクル（閉路）は、始点と終点が同じパスです。\n\nグラフにサイクルがあるかどうかは、DFS（深さ優先探索）で判定できます。\n\n探索中に訪問済みの頂点に戻ったらサイクルが存在します。計算量はO(V+E)です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '10頂点の木の辺の数はいくつですか？',
        options: [
          { id: 'a', label: '10', correct: false },
          { id: 'b', label: '9', correct: true },
          { id: 'c', label: '8', correct: false },
          { id: 'd', label: '11', correct: false },
        ],
        explanation: 'n頂点の木は必ず n-1 本の辺を持ちます。よって10頂点の木は9本の辺を持ちます。',
      },
    },
    {
      id: 'alternate',
      title: '森とルート付き木',
      content: '連結でないがサイクルを持たないグラフを「森（forest）」と呼びます。森は木の集まりです。\n\nまた、1つの頂点を「根（ルート）」として特別扱いすると「ルート付き木」になります。\n\nファイルシステムの階層構造はルート付き木の代表例です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 木は連結でサイクルのないグラフ\n2. n頂点の木は n-1 本の辺を持つ\n3. 木では任意の2頂点間に唯一のパスが存在する\n\n木に辺を追加・削除してサイクルとの関係を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
