import { Tutorial } from '../types';

export const degreeSequenceTutorial: Tutorial = {
  id: 'degree-sequence',
  title: '次数と次数列',
  description: '頂点の次数（接続する辺の数）とグラフの次数列について学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '人気者は何人とつながっている？',
      content: 'SNSで友達が多い人、少ない人がいますね。\n\nグラフ理論では、頂点につながる辺の数を「次数」と呼びます。\n\n各頂点の次数が変化するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'degree-sequence-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '辺を追加して次数を観察しよう',
      content: '頂点間に辺を追加したり削除したりして、次数の変化を観察しましょう。\n\n辺を1本追加すると、両端の頂点の次数がそれぞれ1ずつ増えます。\n\nすべての頂点の次数の合計はどうなるでしょうか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'degree-sequence-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '次数の定義',
      content: '頂点 v の次数 deg(v) は、v に接続する辺の数です。\n\n有向グラフでは入次数 deg⁻(v) と出次数 deg⁺(v) を区別します。\n\n例：三角形グラフでは各頂点の次数は2です。完全グラフ K₄ では各頂点の次数は3です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '握手の補題',
      content: '握手の補題（ハンドシェイキング補題）：\n\nすべての頂点の次数の合計 = 2 × 辺の数\n\nΣ deg(v) = 2|E|\n\nこれは各辺が2つの頂点の次数に寄与するためです。結果として、奇数次数の頂点は必ず偶数個存在します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '5頂点のグラフで辺が7本あるとき、すべての頂点の次数の合計はいくつですか？',
        options: [
          { id: 'a', label: '7', correct: false },
          { id: 'b', label: '10', correct: false },
          { id: 'c', label: '14', correct: true },
          { id: 'd', label: '35', correct: false },
        ],
        explanation: '握手の補題より、次数の合計 = 2 × 辺の数 = 2 × 7 = 14 です。',
      },
    },
    {
      id: 'alternate',
      title: '次数列とグラフの存在',
      content: '次数列とは、グラフの各頂点の次数を降順に並べたものです。\n\n例：(3, 2, 2, 1) は4頂点のグラフの次数列です。\n\n任意の数列が次数列になれるわけではありません。エルデシュ・ガライの定理で判定できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 次数 deg(v) は頂点に接続する辺の数\n2. 握手の補題：次数の合計 = 2 × 辺の数\n3. 次数列はグラフの構造を反映する重要な特徴量\n\n辺を追加・削除して次数の変化を確認してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'degree-sequence-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
