import { Tutorial } from '../types';

export const dependencyManagementTutorial: Tutorial = {
  id: 'dependency-management',
  title: '依存関係管理',
  description: 'ソフトウェアパッケージの依存関係をグラフで管理する方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ライブラリの依存地獄',
      content: 'npm installで大量のパッケージがインストールされるのはなぜ？\n\nパッケージの依存関係はグラフを形成し、正しい順序でインストールする必要があります。\n\n依存関係グラフが展開される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '依存関係を解決しよう',
      content: 'パッケージの依存関係グラフでインストール順序を決めましょう。\n\nトポロジカルソートで正しい順序が求まります。\n\n循環依存がある場合はどうなるか確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '依存関係グラフ',
      content: 'パッケージマネージャの依存関係はDAG（理想的には）です。\n\n- npm/yarn：package.jsonのdependencies\n- pip：requirements.txt\n- Maven：pom.xml\n\nインストール順序はトポロジカルソートで決定されます。\n\n循環依存は問題を引き起こします。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'バージョン競合と解決',
      content: 'ダイヤモンド依存問題：\nA → B → D@1.0\nA → C → D@2.0\n\n解決策：\n- npm：ネストされたnode_modules（重複許可）\n- pip：最新バージョンを選択\n- pnpm：シンボリックリンクで共有\n\nセマンティックバージョニング(semver)で互換性を管理します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ソフトウェアの依存関係グラフに循環依存がある場合、何が問題になりますか？',
        options: [
          { id: 'a', label: 'インストールが高速になりすぎる', correct: false },
          { id: 'b', label: 'トポロジカルソートが適用できない', correct: true },
          { id: 'c', label: 'パッケージのサイズが小さくなる', correct: false },
          { id: 'd', label: 'バージョンが自動更新される', correct: false },
        ],
        explanation: '循環依存があるとDAGではなくなり、トポロジカルソートで正しいインストール順序を決められません。',
      },
    },
    {
      id: 'alternate',
      title: 'サプライチェーンセキュリティ',
      content: '依存関係グラフはセキュリティリスクにもなります。\n\n- 依存関係攻撃：悪意あるパッケージの混入\n- 推移的依存：直接依存していなくても影響を受ける\n- SBOM：ソフトウェア部品表で依存関係を管理\n\nグラフ解析で脆弱な依存パスを特定できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. パッケージ依存関係はDAGで管理\n2. トポロジカルソートで正しい順序を決定\n3. バージョン競合やセキュリティもグラフで分析\n\n依存関係を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
