import { Tutorial } from '../types';

export const dfsApplicationsTutorial: Tutorial = {
  id: 'dfs-applications',
  title: 'DFSの応用',
  description: '深さ優先探索の応用例と発見時刻・終了時刻を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '迷路を奥まで探る',
      content: 'DFS（深さ優先探索）は行き止まりまで進み、戻って別の道を探ります。\n\n再帰やスタックで実装され、グラフの構造を深く解析できます。\n\nDFSが木の奥深くまで潜っていく様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'dfs-applications-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'DFSを実行してみよう',
      content: '始点を選んでDFSを実行しましょう。\n\n各頂点の発見時刻と終了時刻を観察してください。\n\n辺の分類（木辺、後退辺、前進辺、交差辺）も確認しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'dfs-applications-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'DFSの辺分類',
      content: 'DFSで得られる辺の分類：\n\n- 木辺：DFS木の辺\n- 後退辺：祖先への辺（サイクルの存在を示す）\n- 前進辺：子孫への辺（有向グラフのみ）\n- 交差辺：兄弟への辺（有向グラフのみ）\n\nサイクル検出は後退辺の有無で判定できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'DFSの応用',
      content: 'DFSの主な応用：\n\n- サイクル検出\n- トポロジカルソート（後述）\n- 強連結成分の分解\n- 関節点と橋の検出\n- 二重連結成分の分解\n\nいずれも O(V+E) で計算可能です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'DFSでサイクルの存在を示す辺の種類はどれですか？',
        options: [
          { id: 'a', label: '木辺', correct: false },
          { id: 'b', label: '後退辺', correct: true },
          { id: 'c', label: '前進辺', correct: false },
          { id: 'd', label: '交差辺', correct: false },
        ],
        explanation: '後退辺は現在の頂点から祖先への辺であり、これが存在するとサイクルがあることを意味します。',
      },
    },
    {
      id: 'alternate',
      title: '関節点と橋',
      content: '関節点：除去するとグラフが非連結になる頂点\n橋：除去するとグラフが非連結になる辺\n\nDFSの発見時刻と lowlink 値を使って O(V+E) で検出できます。\n\nlowlink[v] = DFS木でvの部分木から後退辺で到達できる最小の発見時刻\n\nネットワークの脆弱性分析に重要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. DFSは辺を4種類に分類できる\n2. 後退辺がサイクルの存在を示す\n3. 関節点・橋の検出など構造解析に有効\n\nDFSの探索を操作して辺の分類を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'dfs-applications-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
