import { Tutorial } from '../types';

export const directedUndirectedTutorial: Tutorial = {
  id: 'directed-undirected',
  title: '有向グラフと無向グラフ',
  description: '辺に方向があるかないかでグラフの性質が大きく変わることを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '一方通行と双方向',
      content: '道路には一方通行と双方向の道があります。\n\nSNSでも「相互フォロー」と「片方だけフォロー」がありますね。\n\nこの違いをグラフで表現するのが有向・無向の概念です。矢印のあるグラフとないグラフを見比べてみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '有向辺と無向辺を切り替えよう',
      content: '辺をクリックして、有向（矢印あり）と無向（矢印なし）を切り替えてみましょう。\n\n有向グラフでは辺に向きがあり、(A→B) と (B→A) は別の辺です。\n\n無向グラフでは向きがなく、{A,B} は1本の辺です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '無向グラフの例',
      content: '無向グラフの代表例は友人関係です。\n\nAとBが友人なら、BとAも友人です。この対称性が無向グラフの特徴です。\n\n道路網でも、双方向の道路は無向辺で表現できます。辺 {u,v} はどちらの方向にも通れます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '有向グラフの例',
      content: 'Twitterのフォロー関係は有向グラフです。AがBをフォローしても、BがAをフォローしているとは限りません。\n\nウェブのリンク構造も有向です。ページAからBにリンクがあっても、BからAにリンクがあるとは限りません。\n\n食物連鎖も有向グラフで表現されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '次のうち、有向グラフで表現するのが最も適切なものはどれですか？',
        options: [
          { id: 'a', label: '握手の関係', correct: false },
          { id: 'b', label: 'メールの送受信関係', correct: true },
          { id: 'c', label: '兄弟関係', correct: false },
          { id: 'd', label: '同じクラスにいる関係', correct: false },
        ],
        explanation: 'メールの送受信は「AがBに送る」という方向性があるため、有向グラフが適切です。握手・兄弟・同クラスは対称的な関係なので無向グラフで表せます。',
      },
    },
    {
      id: 'alternate',
      title: '混合グラフという考え方',
      content: '実は有向辺と無向辺を混ぜた「混合グラフ」も存在します。\n\n現実の道路網は一方通行と双方向が混在しているので、混合グラフが最も自然な表現です。\n\nまた、無向グラフは各辺を双方向の有向辺2本に置き換えれば有向グラフとして扱えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 無向グラフ：辺に向きがない（対称的な関係）\n2. 有向グラフ：辺に向きがある（非対称な関係）\n3. 現実世界の関係を適切に表現するには、向きの有無を正しく選ぶことが大切\n\nグラフを操作して有向・無向の違いを体感しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
