import { Tutorial } from '../types';

export const distributedGraphTutorial: Tutorial = {
  id: 'distributed-graph',
  title: '分散システムとグラフ',
  description: '分散コンピューティングにおけるグラフアルゴリズムを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '巨大グラフを分散処理',
      content: '数十億のノードを持つグラフは1台のマシンに収まりません。\n\n分散システムでグラフを処理する技術が必要です。\n\nグラフが複数のマシンに分割される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'distributed-graph-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'グラフ分割を試そう',
      content: 'グラフを複数のパーティションに分割してみましょう。\n\nパーティション間のカット辺を最小にするのが理想です。\n\n通信コストの変化を観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'distributed-graph-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフの分割方法',
      content: 'グラフパーティショニング：\n\n- 頂点分割：頂点を各マシンに分配\n- 辺分割：辺を各マシンに分配\n\n目標：負荷均等化 + パーティション間の通信最小化\n\nMETIS、KaHIPなどのツールが使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '分散グラフフレームワーク',
      content: '主要な分散グラフ処理フレームワーク：\n\n- Pregel（Google）：頂点中心の計算モデル\n- Apache Giraph：Pregelのオープンソース実装\n- GraphX（Apache Spark）：Spark上のグラフ処理\n\nBSP（Bulk Synchronous Parallel）モデルで同期的に計算を繰り返します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '分散グラフ処理でパーティション間の通信を減らすために重要なのは？',
        options: [
          { id: 'a', label: '辺の重みを大きくする', correct: false },
          { id: 'b', label: 'カット辺を最小にするグラフ分割', correct: true },
          { id: 'c', label: 'ノード数を減らす', correct: false },
          { id: 'd', label: 'ランダムに分割する', correct: false },
        ],
        explanation: 'パーティション間のカット辺を最小にすることで、マシン間の通信コストを削減できます。',
      },
    },
    {
      id: 'alternate',
      title: 'GNNの分散学習',
      content: '大規模GNNの分散学習：\n\n- ミニバッチサンプリング（GraphSAGE方式）\n- グラフの部分サンプリングで勾配を近似\n- サブグラフ分割による並列学習\n\n数十億ノードのグラフでもGNNを学習できるようになっています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 巨大グラフは分散処理が必要\n2. グラフ分割で通信コストを最小化\n3. Pregel等のフレームワークで頂点中心計算\n\n分散処理を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'distributed-graph-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
