import { Tutorial } from '../types';

export const eulerPolyhedraTutorial: Tutorial = {
  id: 'euler-polyhedra',
  title: 'オイラーの多面体公式',
  description: '多面体の頂点・辺・面の間に成り立つ美しい関係式を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '立体の不変量',
      content: 'サイコロ（立方体）は頂点8、辺12、面6です。8 - 12 + 6 = 2。\n\n正四面体は頂点4、辺6、面4です。4 - 6 + 4 = 2。\n\nいつも2になるのは偶然でしょうか？多面体が回転する様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '多面体を数えてみよう',
      content: '様々な多面体の頂点・辺・面を数えてみましょう。\n\n多面体を回転させて、V - E + F の値を確認してください。\n\nどの凸多面体でも V - E + F = 2 になるはずです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'オイラーの多面体公式',
      content: '凸多面体に対して：V - E + F = 2\n\nV：頂点の数、E：辺の数、F：面の数\n\nこの値 2 は「オイラー標数」と呼ばれ、トポロジー（位相幾何学）の基本概念です。\n\n穴のない閉じた曲面のオイラー標数は常に 2 です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '平面グラフとの関係',
      content: '多面体の各面を平面に展開すると平面グラフになります。\n\nよって、平面グラフに対しても V - E + F = 2 が成り立ちます（F は外側の面を含む）。\n\nこのように多面体の公式とグラフ理論は深く結びついています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '正十二面体は面が12個、頂点が20個です。辺の数はいくつですか？',
        options: [
          { id: 'a', label: '28', correct: false },
          { id: 'b', label: '30', correct: true },
          { id: 'c', label: '32', correct: false },
          { id: 'd', label: '24', correct: false },
        ],
        explanation: 'V - E + F = 2 より、20 - E + 12 = 2、E = 30 です。',
      },
    },
    {
      id: 'alternate',
      title: 'トーラスと高次の曲面',
      content: 'ドーナツ型（トーラス）のオイラー標数は 0 です。\n\n穴が g 個ある曲面のオイラー標数は 2 - 2g です。\n\nこの一般化はトポロジーの重要なテーマであり、曲面の分類に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. オイラーの多面体公式：V - E + F = 2\n2. 平面グラフにも同じ公式が成り立つ\n3. オイラー標数はトポロジーの基本的な不変量\n\n様々な多面体で公式を確認してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
