import { Tutorial } from '../types';

export const eulerPathTutorial: Tutorial = {
  id: 'euler-path',
  title: 'オイラー路とオイラー回路',
  description: 'すべての辺をちょうど1回ずつ通る経路について学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ケーニヒスベルクの橋',
      content: '18世紀のケーニヒスベルクの街には7つの橋がありました。\n\n「すべての橋をちょうど1回ずつ渡って散歩できるか？」——この問いがグラフ理論の始まりです。\n\nオイラーの有名な解答をアニメーションで見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'euler-path-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'オイラー路を見つけよう',
      content: 'すべての辺をちょうど1回通る経路を見つけてみましょう。\n\n辺をクリックして順番に選択してください。\n\nすべての辺を通れるパスは見つかりますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'euler-path-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'オイラー路とオイラー回路の条件',
      content: 'オイラー路：すべての辺をちょうど1回通るパス\nオイラー回路：始点に戻るオイラー路\n\n存在条件（連結グラフ）：\n- オイラー回路がある ⟺ すべての頂点の次数が偶数\n- オイラー路がある ⟺ 奇数次数の頂点が0個または2個',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'ケーニヒスベルクの解答',
      content: 'ケーニヒスベルクの橋のグラフでは、すべての頂点の次数が奇数でした。\n\n奇数次数の頂点が4つあるため、オイラー路もオイラー回路も存在しません。\n\nオイラーはこの問題を解くことで、グラフ理論を創始しました（1736年）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '正方形の4頂点をすべての辺で結んだグラフ（C₄）にオイラー回路は存在しますか？',
        options: [
          { id: 'a', label: '存在する（すべての頂点の次数が2で偶数）', correct: true },
          { id: 'b', label: '存在しない（奇数次数の頂点がある）', correct: false },
          { id: 'c', label: '頂点が4つなので存在しない', correct: false },
          { id: 'd', label: '辺が4本なので判定できない', correct: false },
        ],
        explanation: 'C₄ではすべての頂点の次数が2（偶数）です。したがってオイラー回路が存在します。',
      },
    },
    {
      id: 'alternate',
      title: 'フルーリーのアルゴリズム',
      content: 'オイラー路の存在が保証されたら、実際に経路を構成できます。\n\nフルーリーのアルゴリズム：「橋を渡るのは最後の手段にする」\n\n現在の頂点から辺を選ぶとき、その辺が橋（削除するとグラフが非連結になる辺）でなければ優先的に選びます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. オイラー路はすべての辺をちょうど1回通る経路\n2. 存在条件は頂点の次数で完全に判定できる\n3. グラフ理論はオイラーの橋の問題から始まった\n\nグラフを操作してオイラー路を探してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'euler-path-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
