import { Tutorial } from '../types';

export const flowNetworkAppTutorial: Tutorial = {
  id: 'flow-network-app',
  title: 'フローネットワーク応用',
  description: '最大フロー・最小カットの実践的な応用を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'フローの実践応用',
      content: '最大フローと最小カットは理論だけでなく、多くの実問題に応用されます。\n\n画像のセグメンテーション、スケジューリング、ネットワーク設計——すべてフロー問題です。\n\n応用例のアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '画像セグメンテーションを試そう',
      content: '画像の前景と背景を分離する問題をフローネットワークで解きましょう。\n\n各ピクセルをノード、隣接関係を辺として、最小カットで分離します。\n\n結果を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '画像セグメンテーション',
      content: '画像のセグメンテーションを最小カットで解く：\n\n1. 各ピクセルをノード、隣接ピクセル間に辺\n2. ソース（前景）とシンク（背景）を追加\n3. 各ノードの前景/背景らしさを容量に反映\n4. 最小カットが最適な分離を与える\n\nGraph Cutsアルゴリズムとして知られています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'プロジェクト選択問題',
      content: '利益付きプロジェクト選択もフロー問題：\n\n- 各プロジェクトに利益（正）とコスト（負）\n- プロジェクト間に依存関係\n- 利益を最大化するプロジェクトの部分集合を選択\n\nこれは最小カット問題に帰着し、効率的に解けます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '画像セグメンテーションでGraph Cutsが利用するグラフアルゴリズムは？',
        options: [
          { id: 'a', label: '最短経路', correct: false },
          { id: 'b', label: '最小カット', correct: true },
          { id: 'c', label: 'トポロジカルソート', correct: false },
          { id: 'd', label: '最小全域木', correct: false },
        ],
        explanation: 'Graph Cutsは最小カット（＝最大フロー）を使って画像の前景と背景を最適に分離します。',
      },
    },
    {
      id: 'alternate',
      title: 'スケジューリングへの応用',
      content: 'フローネットワークの他の応用：\n\n- 割り当て問題：最小費用フローで最適割り当て\n- 配送計画：容量制約付きフロー\n- 通信ネットワーク設計：帯域幅の最大化\n\nフロー理論はオペレーションズリサーチの根幹です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. フローは画像処理、スケジューリング等に応用\n2. 画像セグメンテーションは最小カット問題\n3. プロジェクト選択もフローで解ける\n\nフローの応用を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
