import { Tutorial } from '../types';

export const floydWarshallTutorial: Tutorial = {
  id: 'floyd-warshall',
  title: 'ワーシャル・フロイド法',
  description: '全頂点ペア間の最短経路を求めるアルゴリズムを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'すべてのペアの距離',
      content: 'すべての都市ペア間の最短距離を一度に求めたい。\n\nワーシャル・フロイド法は動的計画法でこれを効率的に解きます。\n\n距離行列が更新されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'floyd-warshall-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '中継点を追加しよう',
      content: '中継点を1つずつ追加して、最短距離がどう変わるか観察しましょう。\n\n頂点kを中継すると、d[i][j] と d[i][k]+d[k][j] の小さい方に更新されます。\n\n行列の変化を観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'floyd-warshall-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'アルゴリズムの手順',
      content: 'ワーシャル・フロイド法：\n\nfor k = 1 to n:\n  for i = 1 to n:\n    for j = 1 to n:\n      d[i][j] = min(d[i][j], d[i][k] + d[k][j])\n\n計算量：O(V³)、空間：O(V²)\n\n動的計画法の典型例です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '負閉路と経路復元',
      content: '対角要素 d[i][i] < 0 となる頂点iがあれば、負閉路が存在します。\n\n経路復元：next[i][j] に「iからjへの最短経路で次に通る頂点」を記録すれば、実際の経路を再構成できます。\n\n更新時に next[i][j] = next[i][k] とします。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ワーシャル・フロイド法の計算量はどれですか？',
        options: [
          { id: 'a', label: 'O(V²)', correct: false },
          { id: 'b', label: 'O(V³)', correct: true },
          { id: 'c', label: 'O(VE)', correct: false },
          { id: 'd', label: 'O(V² log V)', correct: false },
        ],
        explanation: '3重ループなので O(V³) です。密グラフではダイクストラ法のV回実行より効率的です。',
      },
    },
    {
      id: 'alternate',
      title: '推移閉包',
      content: 'ワーシャル・フロイド法を変形すると「推移閉包」も求められます。\n\n推移閉包：頂点iから頂点jに到達可能かどうかの行列\n\nd[i][j] = d[i][j] OR (d[i][k] AND d[k][j])\n\nこれも O(V³) で計算でき、到達可能性解析に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ワーシャル・フロイド法はすべての頂点ペアの最短距離を求める\n2. 動的計画法でO(V³)で計算\n3. 負閉路検出や推移閉包にも応用可能\n\n距離行列の更新を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'floyd-warshall-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
