import { Tutorial } from '../types';

export const fourColorTutorial: Tutorial = {
  id: 'four-color',
  title: '四色定理',
  description: '平面グラフは4色で彩色できるという有名な定理を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '地図は何色で塗れる？',
      content: '世界地図を隣接する国が異なる色になるように塗るには、何色必要でしょうか？\n\n驚くべきことに、どんな地図でも4色あれば十分です。\n\n地図が4色で塗り分けられるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'four-color-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '4色で地図を塗ろう',
      content: '表示された地図（平面グラフ）を4色以下で塗り分けてみましょう。\n\n隣接する領域が同じ色にならないように注意してください。\n\n本当に4色で足りることを体感しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'four-color-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '四色定理の歴史',
      content: '1852年にフランシス・ガスリーが予想を提出しました。\n\n124年後の1976年、アッペルとハーケンがコンピュータを使って証明しました。\n\nこれは初めてコンピュータが本質的に使われた数学の証明として話題になりました。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '四色定理とグラフ',
      content: '地図の彩色問題は平面グラフの頂点彩色に帰着します。\n\n各領域を頂点、隣接関係を辺としたグラフを作ると、これは平面グラフになります。\n\n四色定理：すべての平面グラフの彩色数は4以下\n\n五色定理はより簡単に証明でき、教科書でよく扱われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '四色定理について正しいものはどれですか？',
        options: [
          { id: 'a', label: 'すべてのグラフは4色で塗れる', correct: false },
          { id: 'b', label: 'すべての平面グラフは4色で塗れる', correct: true },
          { id: 'c', label: '3色では塗れない平面グラフは存在しない', correct: false },
          { id: 'd', label: '四色定理はまだ証明されていない', correct: false },
        ],
        explanation: '四色定理は「すべての平面グラフは4色で彩色できる」という定理です。非平面グラフには適用されません。',
      },
    },
    {
      id: 'alternate',
      title: 'コンピュータ証明の意義',
      content: '四色定理の証明では、1936通りの場合分けをコンピュータで検証しました。\n\n「人間が確認できない証明は数学的に有効か？」という哲学的議論を呼びました。\n\n現在では形式的証明（Coq）でも検証されており、正しさが確認されています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 四色定理：すべての平面グラフは4色で彩色可能\n2. 1976年に初のコンピュータ支援証明として証明された\n3. 地図の塗り分け問題はグラフ彩色に帰着する\n\n4色で地図を塗り分ける練習をしましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'four-color-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
