import { Tutorial } from '../types';

export const gnnIntroTutorial: Tutorial = {
  id: 'gnn-intro',
  title: 'グラフニューラルネットワーク入門',
  description: 'グラフ構造データに対するニューラルネットワークの基本を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'AIがグラフを理解する',
      content: '画像にはCNN、テキストにはRNNがありますが、グラフ構造のデータにはどうする？\n\nグラフニューラルネットワーク（GNN）がその答えです。\n\nGNNがノードの情報を集約する様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'gnn-intro-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'メッセージパッシングを体験しよう',
      content: '各ノードが隣接ノードから情報を集めて自身を更新する「メッセージパッシング」を体験しましょう。\n\n何回パスすると、ノードの情報がグラフ全体に伝わりますか？\n\n層の数を変えて観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'gnn-intro-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'メッセージパッシングの仕組み',
      content: 'GNNの基本操作（1層分）：\n\n1. メッセージ：各ノードが隣接ノードの特徴量を集める\n2. 集約：集めた情報を統合（平均、最大、合計など）\n3. 更新：集約した情報と自身の特徴量から新しい特徴量を計算\n\nh_v^(k) = UPDATE(h_v^(k-1), AGGREGATE({h_u^(k-1) : u ∈ N(v)}))',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'GNNの種類',
      content: '代表的なGNNアーキテクチャ：\n\n- GCN（Graph Convolutional Network）：スペクトル畳み込み\n- GAT（Graph Attention Network）：注意機構で隣接ノードの重要度を学習\n- GraphSAGE：サンプリングによるスケーラブルな学習\n- GIN（Graph Isomorphism Network）：WLテストと同等の表現力',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'GNNのメッセージパッシングで各ノードが行うことは？',
        options: [
          { id: 'a', label: 'すべてのノードに情報を送る', correct: false },
          { id: 'b', label: '隣接ノードから情報を集めて自身を更新する', correct: true },
          { id: 'c', label: 'ランダムにノードを選んで情報交換する', correct: false },
          { id: 'd', label: '辺の重みだけを更新する', correct: false },
        ],
        explanation: 'メッセージパッシングでは各ノードが隣接ノードの情報を集約し、自身の特徴量を更新します。',
      },
    },
    {
      id: 'alternate',
      title: 'GNNの応用',
      content: 'GNNの応用分野：\n\n- 分子特性予測（薬物設計）\n- 推薦システム（ユーザー・アイテムグラフ）\n- 交通流予測（道路ネットワーク）\n- 社会ネットワーク分析\n\n近年はTransformerとの融合やLLMとの組み合わせも研究されています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. GNNはグラフ構造データに対するニューラルネットワーク\n2. メッセージパッシングで隣接情報を集約\n3. 分子設計、推薦、交通予測など応用が広い\n\nメッセージパッシングを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'gnn-intro-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
