import { Tutorial } from '../types';

export const graphIsomorphismTutorial: Tutorial = {
  id: 'graph-isomorphism',
  title: 'グラフの同型判定',
  description: '2つのグラフが「同じ構造」かどうかを判定する問題を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '見た目が違っても同じ？',
      content: '異なる配置で描かれた2つのグラフが、実は同じ構造を持つことがあります。\n\nこの「同じ構造」を同型（isomorphism）と呼びます。\n\n同型なグラフが変形されて一致するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-isomorphism-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '同型を見つけよう',
      content: '2つのグラフが表示されています。頂点の対応を見つけて同型性を確認しましょう。\n\n頂点をドラッグして対応付けてください。\n\n次数列や隣接関係が一致するか確認しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-isomorphism-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフ同型の定義',
      content: 'グラフ G₁=(V₁,E₁) と G₂=(V₂,E₂) が同型とは：\n\n全単射 f: V₁ → V₂ が存在し、(u,v) ∈ E₁ ⟺ (f(u),f(v)) ∈ E₂\n\n必要条件：頂点数、辺数、次数列が一致\n\nしかしこれは十分条件ではありません。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '同型判定の計算量',
      content: 'グラフ同型判定の計算量は未解決問題です。\n\n- NP完全か多項式時間か不明\n- 2015年、ラースロー・バーバイが準多項式時間アルゴリズムを発表\n- 実用的には McKay の nauty が高速に動作\n\n特殊なグラフ（平面グラフ、木など）では多項式時間で判定可能です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'グラフ同型判定に必要な条件でないものはどれですか？',
        options: [
          { id: 'a', label: '頂点数が等しい', correct: false },
          { id: 'b', label: '辺数が等しい', correct: false },
          { id: 'c', label: '次数列が一致する', correct: false },
          { id: 'd', label: 'すべての頂点のラベルが一致する', correct: true },
        ],
        explanation: 'グラフ同型はラベルではなく構造の一致を判定します。ラベルは同型写像で対応付けられればよく、一致する必要はありません。',
      },
    },
    {
      id: 'alternate',
      title: 'ワイスファイラー・レーマンテスト',
      content: 'WL (Weisfeiler-Leman) テストは同型判定の実用的手法です。\n\n各頂点の「色」を、自身と隣接頂点の色に基づいて反復的に更新します。\n\n色のパターンが異なれば非同型と判定できますが、同じでも同型とは限りません。GNNの表現力はこのWLテストと密接に関連しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフ同型は構造の一致を意味する\n2. 計算量は多項式かNP完全か未解決\n3. WLテストやnautyで実用的に判定可能\n\n同型グラフを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-isomorphism-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
