import { Tutorial } from '../types';

export const graphEmbeddingTutorial: Tutorial = {
  id: 'graph-embedding',
  title: 'グラフ埋め込み',
  description: 'グラフの頂点をベクトル空間に埋め込む技術を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'グラフをベクトルに変換',
      content: 'グラフ構造を機械学習に使うには、頂点や辺をベクトルで表現する必要があります。\n\nグラフ埋め込みはこの変換を行う技術です。\n\n頂点が2次元空間に埋め込まれる様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '埋め込みを可視化しよう',
      content: 'グラフの頂点を2次元空間に埋め込んだ結果を観察しましょう。\n\n類似した頂点が近くに配置されているか確認してください。\n\nコミュニティ構造が空間に反映されていますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ランダムウォーク型埋め込み',
      content: 'DeepWalk / Node2Vec：\n\n1. グラフ上でランダムウォークを実行\n2. ウォークの軌跡を「文」として扱う\n3. Word2Vec（Skip-gram）で頂点の埋め込みを学習\n\nNode2Vecはp,qパラメータでBFS的/DFS的な探索を制御します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '行列分解型埋め込み',
      content: '行列分解型：\n\n- Laplacian Eigenmaps：ラプラシアンの固有ベクトル\n- HOPE：高次近接性を保存\n- LINE：1次と2次の近接性を保存\n\nこれらは特定の行列の低ランク近似として解釈できます。\n\nGNNベースの埋め込みも増えています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'DeepWalkでグラフの頂点を埋め込むために使われる技術は？',
        options: [
          { id: 'a', label: '主成分分析（PCA）', correct: false },
          { id: 'b', label: 'Word2Vec（Skip-gram）', correct: true },
          { id: 'c', label: '線形回帰', correct: false },
          { id: 'd', label: 'k-means', correct: false },
        ],
        explanation: 'DeepWalkはグラフ上のランダムウォークを「文」と見なし、Word2Vec（Skip-gram）で頂点の分散表現を学習します。',
      },
    },
    {
      id: 'alternate',
      title: 'グラフレベルの埋め込み',
      content: '頂点だけでなく、グラフ全体の埋め込みも重要です。\n\n- Graph-level readout：頂点埋め込みを集約（平均、和、注意機構）\n- Graph2Vec：グラフ全体をベクトル化\n\n分子のグラフ表現から物性を予測するなど、グラフ分類に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフ埋め込みは頂点をベクトル空間に変換\n2. ランダムウォーク型と行列分解型がある\n3. 機械学習タスクの基盤技術\n\n埋め込みを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
