import { Tutorial } from '../types';

export const graphColoringTutorial: Tutorial = {
  id: 'graph-coloring',
  title: 'グラフ彩色',
  description: '隣接する頂点が異なる色になるようにグラフを彩色する問題を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '色分けの難しさ',
      content: '時間割を作るとき、同じ時間に同じ教室を使う授業がないようにしたいですね。\n\nこれはグラフ彩色の問題として定式化できます。\n\nグラフが次々と色づけされるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'グラフを彩色しよう',
      content: '頂点をクリックして色を選び、隣接する頂点が同じ色にならないように塗りましょう。\n\n最小何色で塗れるでしょうか？\n\nこの最小色数を「彩色数」χ(G) と呼びます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフ彩色の定義',
      content: 'k-彩色：各頂点に k 色のうち1色を割り当て、隣接頂点が異なる色になるもの\n\n彩色数 χ(G)：正しいk-彩色が存在する最小の k\n\n例：\n- 木の彩色数は2\n- 奇数サイクルの彩色数は3\n- 完全グラフ K_n の彩色数は n',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '彩色の応用',
      content: 'グラフ彩色の応用：\n\n- 時間割作成（授業の競合回避）\n- 周波数割り当て（電波の干渉防止）\n- レジスタ割り当て（コンパイラの最適化）\n- 地図の塗り分け\n\n彩色数の計算自体はNP困難ですが、貪欲法で近似できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '五角形（C₅）の彩色数はいくつですか？',
        options: [
          { id: 'a', label: '2', correct: false },
          { id: 'b', label: '3', correct: true },
          { id: 'c', label: '4', correct: false },
          { id: 'd', label: '5', correct: false },
        ],
        explanation: 'C₅は奇数長サイクルなので2色では塗れませんが、3色あれば塗れます。よって彩色数は3です。',
      },
    },
    {
      id: 'alternate',
      title: '貪欲彩色法',
      content: '貪欲彩色法：頂点を順番に処理し、使える最小の色番号を割り当てる\n\nこの方法は最適解を保証しませんが、高速（O(V+E)）です。\n\nブルックスの定理：最大次数Δのグラフの彩色数はΔ+1以下（完全グラフと奇数サイクルを除く）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフ彩色は隣接頂点に異なる色を割り当てる\n2. 彩色数χ(G)は必要な最小色数\n3. 時間割・周波数割り当てなど応用が広い\n\n自分でグラフを彩色して最小色数を見つけましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
