import { Tutorial } from '../types';

export const graphBasicsSummaryTutorial: Tutorial = {
  id: 'graph-basics-summary',
  title: 'グラフの基本まとめ',
  description: 'グラフ理論の基礎概念を総復習します。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '基礎を振り返ろう',
      content: 'ここまでグラフ理論の基本を学んできました。\n\n頂点と辺、有向・無向、次数、連結性、木、彩色、マッチング……\n\nこれらの概念が一つのマインドマップとしてつながるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '概念マップを操作しよう',
      content: 'グラフ理論の概念マップを操作して、各概念の関係を確認しましょう。\n\n各トピックをクリックすると要約が表示されます。\n\nどの概念が最も多くのつながりを持っているでしょうか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '構造に関する概念',
      content: 'グラフの構造：\n- 頂点と辺：グラフの基本要素\n- 有向・無向：辺の方向性\n- 重み：辺のコスト\n- 次数：頂点のつながりの数\n- 連結性：頂点間の到達可能性\n- 木：サイクルのない連結グラフ\n- 二部グラフ：2群に分けられるグラフ',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '問題に関する概念',
      content: 'グラフ上の重要な問題：\n- オイラー路/回路：すべての辺を1回通る\n- ハミルトン路/回路：すべての頂点を1回通る\n- グラフ彩色：隣接頂点に異なる色を割り当て\n- マッチング：頂点のペアリング\n- 全域木/最小全域木：最小の連結部分グラフ\n- 最短経路：2点間の最小コスト経路',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '次のうち、多項式時間で解けるのはどれですか？',
        options: [
          { id: 'a', label: 'ハミルトン路の存在判定', correct: false },
          { id: 'b', label: '最大独立集合の計算', correct: false },
          { id: 'c', label: 'オイラー路の存在判定', correct: true },
          { id: 'd', label: 'グラフ彩色数の計算', correct: false },
        ],
        explanation: 'オイラー路の存在判定は次数のチェックだけで済むためO(V)で解けます。他はすべてNP困難です。',
      },
    },
    {
      id: 'alternate',
      title: '応用への橋渡し',
      content: 'これらの基礎概念は応用編で活用されます。\n\n- BFS/DFS → ネットワーク分析\n- 最短経路 → ナビゲーション、ルーティング\n- マッチング → 割り当て問題、推薦システム\n- 彩色 → スケジューリング\n\n次回からは応用的なアルゴリズムと実世界の問題を扱います。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '基礎編のまとめ：\n\n1. グラフは頂点と辺で構成される数学的構造\n2. 構造的性質（連結性、木、彩色など）が問題の核心\n3. 多くの実世界の問題がグラフとして定式化できる\n\n概念マップを自由に探索して理解を深めましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
