import { Tutorial } from '../types';

export const graphCompressionTutorial: Tutorial = {
  id: 'graph-compression',
  title: 'グラフの圧縮と要約',
  description: '大規模グラフを効率的に保存・処理するための圧縮技術を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '巨大グラフを縮める',
      content: '数十億のノードと辺を持つグラフをそのまま保存するとメモリが足りません。\n\nグラフ圧縮は構造の本質を保ちながらサイズを削減します。\n\nグラフが圧縮される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-compression-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'グラフを要約しよう',
      content: '大きなグラフのノードをグループにまとめて「要約グラフ」を作りましょう。\n\n要約しても重要な構造特徴を保持できているか確認してください。\n\n圧縮率と情報損失のバランスを観察しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-compression-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフ圧縮の手法',
      content: '主なグラフ圧縮手法：\n\n- 隣接リストの圧縮：差分符号化、参照圧縮\n- WebGraph フレームワーク：ウェブグラフの高効率圧縮\n- グラフサマリ：スーパーノードで頂点をグループ化\n\nウェブグラフは1頂点あたり2-3ビットまで圧縮可能です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'グラフスパーシフィケーション',
      content: 'グラフスパーシフィケーション：辺を間引いてグラフを近似\n\n- スペクトルスパーシフィケーション：ラプラシアンの固有値を保持\n- カットスパーシフィケーション：カット値を近似保持\n\nO(n log n) 本の辺でほぼ同じ構造特性を保持できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ウェブグラフの圧縮で1頂点あたり何ビット程度まで圧縮可能ですか？',
        options: [
          { id: 'a', label: '16ビット', correct: false },
          { id: 'b', label: '8ビット', correct: false },
          { id: 'c', label: '2-3ビット', correct: true },
          { id: 'd', label: '1ビット', correct: false },
        ],
        explanation: 'WebGraphフレームワークなどの手法により、ウェブグラフは1頂点あたり2-3ビット程度まで圧縮できます。',
      },
    },
    {
      id: 'alternate',
      title: 'ストリーミンググラフ',
      content: 'ストリーミング設定では、グラフの辺が逐次的に到着します。\n\n限られたメモリで：\n- 連結成分の追跡\n- 三角形の数の推定\n- 頻出パターンの検出\n\nスケッチデータ構造（CountMinSketch等）が活用されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 大規模グラフの圧縮は実用上不可欠\n2. 差分符号化やグラフサマリで圧縮\n3. スパーシフィケーションで構造を近似保持\n\nグラフ圧縮を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-compression-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
