import { Tutorial } from '../types';

export const graphIntroTutorial: Tutorial = {
  id: 'graph-intro',
  title: 'グラフとは',
  description: 'グラフ理論の最も基本的な概念である頂点と辺について学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '世界はつながりでできている',
      content: '友人関係、道路網、インターネット——私たちの身の回りには「つながり」が溢れています。\n\nグラフ理論は、こうした「もの」と「つながり」を数学的に扱う強力なツールです。\n\n画面に表示されるノード（点）とエッジ（線）の動きを観察してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'グラフを触ってみよう',
      content: '頂点（ノード）をドラッグして動かしてみましょう。\n\n辺（エッジ）は頂点同士のつながりを表します。頂点を動かしても、つながりの関係は変わりません。\n\nグラフ理論では「位置」ではなく「つながり方」が重要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '頂点と辺',
      content: 'グラフ G = (V, E) は、頂点の集合 V と辺の集合 E からなります。\n\n例えば、3人の友人 A, B, C がいて、AとB、BとCが友人なら：\n- V = {A, B, C}\n- E = {(A,B), (B,C)}\n\nこれが最もシンプルなグラフの表現です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '身近なグラフの例',
      content: '鉄道路線図もグラフです。駅が頂点、路線が辺に対応します。\n\nSNSの友人関係もグラフです。ユーザーが頂点、フォロー関係が辺です。\n\nウェブページとリンクの関係もグラフで表現できます。グラフは至る所にあるのです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '頂点が4つ、辺が3つのグラフとして正しい組み合わせはどれですか？',
        options: [
          { id: 'a', label: 'V={1,2,3,4}, E={(1,2),(2,3),(3,4)}', correct: true },
          { id: 'b', label: 'V={1,2,3}, E={(1,2),(2,3),(3,1)}', correct: false },
          { id: 'c', label: 'V={1,2,3,4}, E={(1,2),(2,3),(3,4),(4,1)}', correct: false },
          { id: 'd', label: 'V={1,2}, E={(1,2)}', correct: false },
        ],
        explanation: '頂点が4つで辺が3つのグラフは、4つの頂点と3本の辺を持つ必要があります。選択肢Aが正しい組み合わせです。',
      },
    },
    {
      id: 'alternate',
      title: 'グラフの描き方は自由',
      content: '同じグラフでも、頂点の配置を変えれば見た目は全く異なります。\n\n大切なのは「どの頂点とどの頂点がつながっているか」という構造です。\n\nこの性質を「グラフ同型」と呼び、グラフ理論の核心的な考え方です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフは頂点（V）と辺（E）の組 G=(V,E) で表される\n2. グラフは「つながり」を数学的に表現するツール\n3. 頂点の位置ではなく、つながり方が重要\n\n自由にグラフを操作して感覚を掴みましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
