import { Tutorial } from '../types';

export const graphTheoryOverviewTutorial: Tutorial = {
  id: 'graph-theory-overview',
  title: 'グラフ理論の全体像',
  description: 'グラフ理論全60回の学びを振り返り、分野の全体像を把握します。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '60回の旅を振り返る',
      content: '基礎から応用、そして実践的なCS応用まで、グラフ理論の幅広い世界を旅してきました。\n\nこの60回で学んだ概念とその関連を俯瞰しましょう。\n\n全体のマインドマップが展開されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-theory-overview-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '全体マップを探索しよう',
      content: 'グラフ理論の全体マップを操作して、各トピックの関連を確認しましょう。\n\n基礎→応用→実践の流れを辿ってください。\n\nどのトピックが最も多くの他トピックと関連していますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-theory-overview-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '3つの柱',
      content: 'グラフ理論の3つの柱：\n\n1. 構造理論：グラフの性質（連結性、彩色、平面性）\n2. アルゴリズム：効率的な計算（探索、最短路、フロー）\n3. 応用：実世界の問題解決（SNS、ナビ、AI）\n\nこれらは互いに深く関連し、一方の発展が他を推進しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '現在の研究最前線',
      content: 'グラフ理論の最前線：\n\n- GNNと理論の融合（表現力の理論的解析）\n- 量子グラフアルゴリズム\n- 動的・時系列グラフの理論\n- 超大規模グラフの効率的処理\n- グラフ基盤モデル（Foundation Models for Graphs）\n\nグラフ理論は今もなお急速に発展中です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'グラフ理論が関わらない分野はどれですか？',
        options: [
          { id: 'a', label: 'コンピュータサイエンス', correct: false },
          { id: 'b', label: '生物学', correct: false },
          { id: 'c', label: '純粋な一変数の微分方程式', correct: true },
          { id: 'd', label: 'ソーシャルネットワーク', correct: false },
        ],
        explanation: '純粋な一変数の微分方程式はグラフ構造を本質的に必要としません。CS、生物学、SNSはすべてグラフ理論と深く関わっています。',
      },
    },
    {
      id: 'alternate',
      title: 'これからの学び',
      content: 'グラフ理論をさらに学ぶために：\n\n- 教科書：Diestel「Graph Theory」、Bondy & Murty「Graph Theory」\n- 実装：NetworkX（Python）、igraph、Neo4j\n- 競技プログラミング：AtCoder、Codeforces\n- 研究論文：KDD、ICML、NeurIPS のグラフ関連論文\n\nグラフ理論は一生学び続けられる豊かな分野です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '60回の総まとめ：\n\n1. グラフ理論は「つながり」の数学\n2. 基礎理論→アルゴリズム→応用の3層構造\n3. CS、生物学、社会科学など幅広く応用\n\nグラフ理論の全体像を自由に探索しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-theory-overview-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
