import { Tutorial } from '../types';

export const graphDatabaseTutorial: Tutorial = {
  id: 'graph-database',
  title: 'データベースとグラフ',
  description: 'グラフデータベースの仕組みと関係データベースとの違いを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '関係をネイティブに扱う',
      content: 'リレーショナルDBでは複雑な関係をJOINで表現しますが、関係が深くなるとパフォーマンスが低下します。\n\nグラフDBは関係をネイティブに扱い、柔軟なクエリが可能です。\n\nグラフDBの探索を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-database-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'グラフクエリを実行しよう',
      content: 'グラフDB上でパターンマッチングクエリを実行してみましょう。\n\n「AさんのAさんの友人が購入した商品」のような複雑な関係も直感的に表現できます。\n\nクエリ結果の可視化を確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-database-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'グラフデータベースの基本',
      content: '主要なグラフDB：\n\n- Neo4j：プロパティグラフモデル、Cypher言語\n- Amazon Neptune：RDFとプロパティグラフの両対応\n- TigerGraph：大規模並列処理\n\nCypherクエリ例：\nMATCH (a)-[:FRIEND]->(b)-[:BOUGHT]->(p)\nRETURN p.name',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'RDBとの比較',
      content: '関係の深いクエリでの比較：\n\n- 2ホップ：RDBでもグラフDBでも高速\n- 4ホップ：グラフDBが圧倒的に高速\n- 6ホップ：RDBはタイムアウト、グラフDBは数秒\n\nグラフDBはインデックスフリー隣接性により、関係の走査がO(1)です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'グラフデータベースがリレーショナルDBより有利な場面はどれですか？',
        options: [
          { id: 'a', label: '単純な表形式データの格納', correct: false },
          { id: 'b', label: '深い関係のクエリ（多段JOIN）', correct: true },
          { id: 'c', label: '大量の数値集計', correct: false },
          { id: 'd', label: 'トランザクション処理', correct: false },
        ],
        explanation: 'グラフDBは多段の関係を直接走査でき、深いJOINが必要なクエリで圧倒的に高速です。',
      },
    },
    {
      id: 'alternate',
      title: 'グラフDBのユースケース',
      content: 'グラフDBの実用例：\n\n- 不正検知：異常な取引パターンの発見\n- 推薦エンジン：関係に基づく推薦\n- マスターデータ管理：エンティティの統合\n- ネットワーク・IT管理：インフラの依存関係\n\nグラフ思考でデータモデリングすると、複雑な関係を自然に扱えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. グラフDBは関係をネイティブに扱う\n2. 深い関係のクエリでRDBより高速\n3. 不正検知や推薦など幅広い応用\n\nグラフクエリを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'graph-database-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
