import { Tutorial } from '../types';

export const hamiltonPathTutorial: Tutorial = {
  id: 'hamilton-path',
  title: 'ハミルトン路',
  description: 'すべての頂点をちょうど1回ずつ通る経路について学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'すべての都市を巡る',
      content: '旅行ですべての都市を1回ずつ訪問したい——これがハミルトン路の問題です。\n\nオイラー路が「すべての辺」を通るのに対し、ハミルトン路は「すべての頂点」を通ります。\n\n一見似ていますが、難しさは桁違いです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ハミルトン路を探してみよう',
      content: 'すべての頂点をちょうど1回ずつ通る経路を探してみましょう。\n\n頂点をクリックして経路を作ってください。\n\nうまくいかない場合はやり直して別のルートを試しましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ハミルトン路とハミルトン閉路',
      content: 'ハミルトン路：すべての頂点をちょうど1回通るパス\nハミルトン閉路：始点に戻るハミルトン路\n\nオイラー路と違い、存在判定の簡潔な条件は知られていません。\n\nディラックの定理：n≥3の各頂点の次数が n/2 以上ならハミルトン閉路が存在する（十分条件）。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'NP完全問題',
      content: 'ハミルトン路の存在判定はNP完全問題です。\n\nこれは「効率的な（多項式時間の）アルゴリズムが存在しないと考えられている」ことを意味します。\n\n巡回セールスマン問題（TSP）はハミルトン閉路の最短版であり、組合せ最適化の代表的難問です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'オイラー路とハミルトン路の違いとして正しいものはどれですか？',
        options: [
          { id: 'a', label: 'オイラー路はすべての頂点を、ハミルトン路はすべての辺を通る', correct: false },
          { id: 'b', label: 'オイラー路はすべての辺を、ハミルトン路はすべての頂点を通る', correct: true },
          { id: 'c', label: '両方とも同じ意味', correct: false },
          { id: 'd', label: 'オイラー路は有向グラフのみ、ハミルトン路は無向グラフのみ', correct: false },
        ],
        explanation: 'オイラー路はすべての辺をちょうど1回通る経路、ハミルトン路はすべての頂点をちょうど1回通る経路です。',
      },
    },
    {
      id: 'alternate',
      title: 'ヒューリスティクス',
      content: 'ハミルトン路の厳密な解を求めるのは困難ですが、近似的な方法があります。\n\n- 最近傍法：最も近い未訪問頂点に移動\n- 2-opt法：経路を部分的に改善\n- 遺伝的アルゴリズム：進化の仕組みを模倣\n\nこれらは実用的な問題で広く使われています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ハミルトン路はすべての頂点をちょうど1回通る\n2. 存在判定はNP完全で、効率的なアルゴリズムは未知\n3. 巡回セールスマン問題はハミルトン閉路の応用\n\nハミルトン路を自分で探してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
