import { Tutorial } from '../types';

export const independentSetTutorial: Tutorial = {
  id: 'independent-set',
  title: '独立集合と頂点被覆',
  description: '互いに隣接しない頂点の集合と、すべての辺を覆う頂点の集合を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '共存できるグループ',
      content: '互いに競合しない企業をまとめてグループにしたい——これが独立集合の考え方です。\n\n逆に、すべての問題をカバーする最小人数のチームは？——これが頂点被覆です。\n\nこの双対関係をアニメーションで見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '独立集合を見つけよう',
      content: '互いに辺で結ばれていない頂点をできるだけ多く選びましょう。\n\n選んだ頂点同士に辺があってはいけません。\n\n最大の独立集合を見つけられますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '定義と関係',
      content: '独立集合：互いに隣接しない頂点の集合 S ⊆ V\n頂点被覆：すべての辺の少なくとも一方の端点を含む集合 C ⊆ V\n\n重要な関係：S が独立集合 ⟺ V \\ S が頂点被覆\n\nよって最大独立集合 + 最小頂点被覆 = 頂点数 n',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '計算の難しさ',
      content: '最大独立集合問題と最小頂点被覆問題はどちらもNP困難です。\n\n近似アルゴリズム：頂点被覆には2近似アルゴリズムが存在します（任意の辺を選び両端点を追加する貪欲法）。\n\n独立集合は近似すら難しく、P≠NP のもとで定数近似不可能であることが知られています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '6頂点のグラフで最大独立集合のサイズが4のとき、最小頂点被覆のサイズはいくつですか？',
        options: [
          { id: 'a', label: '4', correct: false },
          { id: 'b', label: '2', correct: true },
          { id: 'c', label: '3', correct: false },
          { id: 'd', label: '6', correct: false },
        ],
        explanation: '最大独立集合 + 最小頂点被覆 = n より、4 + 最小頂点被覆 = 6、よって最小頂点被覆 = 2 です。',
      },
    },
    {
      id: 'alternate',
      title: 'ケーニヒの定理',
      content: '二部グラフでは美しい結果が成り立ちます。\n\nケーニヒの定理：二部グラフにおいて、最大マッチングのサイズ = 最小頂点被覆のサイズ\n\nこれは一般のグラフでは成り立たない特別な性質です。\n\n二部グラフの構造がこの等式を可能にしています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 独立集合は互いに隣接しない頂点の集合\n2. 頂点被覆はすべての辺をカバーする頂点の集合\n3. 両者は補集合の関係にある\n\n独立集合と頂点被覆を操作して関係を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
