import { Tutorial } from '../types';

export const knowledgeGraphTutorial: Tutorial = {
  id: 'knowledge-graph',
  title: '知識グラフ',
  description: 'エンティティ間の関係をグラフで構造化する知識グラフを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '知識を構造化する',
      content: '「東京は日本の首都である」——この知識をどうデータとして表現しますか？\n\n知識グラフは（エンティティ, 関係, エンティティ）のトリプルでグラフを構成します。\n\n知識グラフが構築される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '知識を追加しよう',
      content: 'エンティティ（ノード）と関係（エッジ）を追加して知識グラフを構築しましょう。\n\n例：（東京, 首都の, 日本）、（日本, 大陸の, アジア）\n\n推論で新しい知識を導けますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '知識グラフの構造',
      content: '知識グラフのトリプル（s, p, o）：\n- s（主語）：エンティティ\n- p（述語）：関係\n- o（目的語）：エンティティまたはリテラル\n\n代表例：\n- Wikidata：6000万以上のエンティティ\n- DBpedia：Wikipediaから自動抽出\n- Google Knowledge Graph：検索エンジンの基盤',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '知識グラフ推論',
      content: '知識グラフ上の推論：\n\n- TransE：関係をベクトルの平行移動で表現 h + r ≈ t\n- RotatE：関係を回転で表現\n- GNN-based：グラフ構造を直接活用\n\nリンク予測（欠けたトリプルの補完）に応用されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '知識グラフの基本単位はどれですか？',
        options: [
          { id: 'a', label: '頂点と辺のペア', correct: false },
          { id: 'b', label: '（主語, 述語, 目的語）のトリプル', correct: true },
          { id: 'c', label: '隣接行列', correct: false },
          { id: 'd', label: 'ラプラシアン行列', correct: false },
        ],
        explanation: '知識グラフは（主語, 述語, 目的語）のトリプルで知識を表現します。',
      },
    },
    {
      id: 'alternate',
      title: 'LLMとの連携',
      content: '大規模言語モデル（LLM）と知識グラフの連携：\n\n- RAG：知識グラフを検索拡張に使用\n- ファクトチェック：LLMの出力を知識グラフで検証\n- 知識グラフ構築：LLMでテキストからトリプルを自動抽出\n\n両者の長所を組み合わせることで、より正確な情報処理が可能になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 知識グラフはトリプルで知識を構造化\n2. 推論で新しい知識を導出可能\n3. LLMとの連携で応用が広がる\n\n知識グラフを構築して操作してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
