import { Tutorial } from '../types';

export const matchingTutorial: Tutorial = {
  id: 'matching',
  title: 'マッチングと完全マッチング',
  description: '頂点のペアを重複なく対応付けるマッチング問題を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '最適なペアリング',
      content: 'ダンスパーティーで全員がパートナーを見つけるには？\n\n仕事と人の最適な割り当ては？\n\nこれらは「マッチング」問題です。ペアが成立するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'マッチングを作ろう',
      content: '辺を選んでマッチングを構成しましょう。\n\n選んだ辺は頂点を共有してはいけません（各頂点は最大1本の辺にマッチ）。\n\n最大何本の辺を選べますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'マッチングの定義',
      content: 'マッチング M は、互いに端点を共有しない辺の集合です。\n\n最大マッチング：辺の数が最大のマッチング\n完全マッチング：すべての頂点がマッチに含まれるマッチング\n\n完全マッチングは頂点数が偶数でないと存在しません。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'ホールの定理',
      content: '二部グラフ G = (U ∪ V, E) で完全マッチングが存在する条件：\n\nホールの定理：Uの任意の部分集合Sについて、|N(S)| ≥ |S|\n（N(S)はSの隣接頂点の集合）\n\n直感的には「どのグループの希望先も十分に多い」ことを意味します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '5頂点のグラフにおける最大マッチングの辺数は最大でいくつですか？',
        options: [
          { id: 'a', label: '1', correct: false },
          { id: 'b', label: '2', correct: true },
          { id: 'c', label: '3', correct: false },
          { id: 'd', label: '5', correct: false },
        ],
        explanation: 'マッチングでは各辺が2つの頂点を使うため、5頂点では最大 ⌊5/2⌋ = 2 本です。',
      },
    },
    {
      id: 'alternate',
      title: '増加パスとハンガリアン法',
      content: '最大マッチングを見つけるアルゴリズム：\n\n増加パス（augmenting path）：マッチに含まれない辺から始まり、交互にマッチ辺・非マッチ辺を通るパス\n\n増加パスに沿ってマッチ/非マッチを反転するとマッチング数が1増えます。\n\nハンガリアン法は重み付きマッチングの最適化に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. マッチングは端点を共有しない辺の集合\n2. ホールの定理で完全マッチングの存在を判定\n3. 増加パスで最大マッチングを構成できる\n\nマッチングを自分で作ってみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
