import { Tutorial } from '../types';

export const maxFlowTutorial: Tutorial = {
  id: 'max-flow',
  title: '最大フロー問題',
  description: 'ネットワーク上で送れる最大の流量を求める問題を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'パイプにどれだけ流せる？',
      content: '水道管のネットワークで、源泉から蛇口までどれだけの水を流せるでしょうか？\n\n各パイプには容量があり、それを超えて流すことはできません。\n\nフローが増加していくアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'max-flow-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'フローを送ってみよう',
      content: 'ソース（源泉）からシンク（排出口）へフローを送る経路を選びましょう。\n\n各辺の容量を超えないように注意してください。\n\n最大フローを達成できますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'max-flow-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'フォード・ファルカーソン法',
      content: 'フォード・ファルカーソン法：\n\n1. 初期フローを0に設定\n2. 残余グラフ上で増加パス（s→tのパス）を見つける\n3. 増加パス上の最小残余容量だけフローを追加\n4. 増加パスがなくなるまで繰り返し\n\nBFSで増加パスを探す方法をエドモンズ・カープ法と呼び、O(VE²) で動作します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '最大フロー最小カット定理',
      content: '最大フロー = 最小カット\n\nこれはグラフ理論で最も重要な定理の一つです。\n\nカット：ソースとシンクを分離する辺の集合\n最小カット：容量の合計が最小のカット\n\nこの双対性は線形計画法の双対定理の特殊ケースです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'フォード・ファルカーソン法が終了するのはどのような状態ですか？',
        options: [
          { id: 'a', label: 'すべての辺がフルに使われた状態', correct: false },
          { id: 'b', label: '残余グラフに増加パスがない状態', correct: true },
          { id: 'c', label: 'シンクに流入するフローが0の状態', correct: false },
          { id: 'd', label: 'すべての頂点を訪問した状態', correct: false },
        ],
        explanation: 'フォード・ファルカーソン法は残余グラフにソースからシンクへの増加パスがなくなったとき終了します。このとき最大フローが達成されています。',
      },
    },
    {
      id: 'alternate',
      title: '高度なフローアルゴリズム',
      content: 'より高速なアルゴリズム：\n\n- ディニッツ法：O(V²E)、実用的に高速\n- プッシュ・リラベル法：O(V²√E)\n- 最高ラベル法：実装により O(V²√E)\n\n最大フローは二部マッチング、最小費用フローなど多くの問題の基礎です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 最大フロー問題はネットワーク上の流量最大化\n2. フォード・ファルカーソン法で増加パスを繰り返し探索\n3. 最大フロー = 最小カット（双対定理）\n\nフローネットワークを操作してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'max-flow-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
