import { Tutorial } from '../types';

export const minCutTutorial: Tutorial = {
  id: 'min-cut',
  title: '最小カット',
  description: 'ネットワークを分断する最小コストのカットを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ネットワークを断ち切る',
      content: '敵のネットワークを最小コストで分断するには、どの回線を切ればよいでしょうか？\n\nこれが最小カット問題です。\n\nグラフが2つに分断されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'min-cut-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'カットを見つけよう',
      content: '辺を選んでネットワークをソースとシンクに分断しましょう。\n\n選んだ辺の容量の合計を最小にしてください。\n\n最小カットは最大フローと等しい値になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'min-cut-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'カットの定義',
      content: 's-tカット：頂点集合を S と T に分割し、s ∈ S、t ∈ T となるもの\n\nカットの容量：S から T への辺の容量の合計（逆方向は含まない）\n\n最小カット：容量が最小の s-t カット\n\n最大フロー最小カット定理により、最大フロー値 = 最小カット容量',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '最小カットの求め方',
      content: '最大フローアルゴリズムを実行した後：\n\n1. 残余グラフ上でソースから到達可能な頂点集合を S とする\n2. T = V \\ S とする\n3. S から T への辺が最小カットを構成する\n\nこの手順で O(VE²) 以内に最小カットが求まります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '最大フローが10のとき、最小カットの容量はいくつですか？',
        options: [
          { id: 'a', label: '5', correct: false },
          { id: 'b', label: '10', correct: true },
          { id: 'c', label: '20', correct: false },
          { id: 'd', label: '判定不能', correct: false },
        ],
        explanation: '最大フロー最小カット定理より、最大フロー = 最小カット容量 = 10 です。',
      },
    },
    {
      id: 'alternate',
      title: 'グローバル最小カット',
      content: 's-t を固定しない「グローバル最小カット」も重要です。\n\nストエル・ワグナーのアルゴリズムで O(VE + V² log V) で求まります。\n\n応用：画像セグメンテーション、ネットワーク信頼性解析、クラスタリングなどに使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 最小カットはネットワークを分断する最小コスト\n2. 最大フロー = 最小カット（双対定理）\n3. 画像処理やネットワーク解析に応用される\n\nカットを操作して最小カットを見つけましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'min-cut-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
