import { Tutorial } from '../types';

export const minimumSpanningTutorial: Tutorial = {
  id: 'minimum-spanning',
  title: '最小全域木',
  description: '重み付きグラフで総コストが最小の全域木を求める方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '最安のネットワーク敷設',
      content: '都市間にケーブルを敷設してすべてを接続したい。ただしコストを最小にしたい。\n\nこれが最小全域木（MST）の問題です。\n\nコストの低い辺から順に選ばれていくアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'minimum-spanning-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'MSTを構成しよう',
      content: '重み付きグラフから辺を選んで最小全域木を構成しましょう。\n\nサイクルを作らないように注意しつつ、重みの合計を最小にしてください。\n\n貪欲に軽い辺を選ぶとうまくいくことが多いです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'minimum-spanning-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'クラスカル法',
      content: 'クラスカル法：辺を重みの昇順にソートし、サイクルを作らない辺を貪欲に追加\n\n1. すべての辺を重み順にソート\n2. 軽い辺から順に、サイクルを作らなければ追加\n3. n-1本選んだら終了\n\nUnion-Find を使うと O(E log E) で動作します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'プリム法',
      content: 'プリム法：1頂点から始めて、木に隣接する最軽辺を順に追加\n\n1. 任意の頂点から開始\n2. 木に隣接する辺の中で最軽のものを追加\n3. n-1本選んだら終了\n\n優先度キューを使うと O(E log V) で動作します。密グラフではO(V²)版が効率的です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'クラスカル法で辺の追加をスキップするのはどのような場合ですか？',
        options: [
          { id: 'a', label: '辺の重みが大きい場合', correct: false },
          { id: 'b', label: '追加するとサイクルができる場合', correct: true },
          { id: 'c', label: '辺が有向辺の場合', correct: false },
          { id: 'd', label: '辺の両端が同じ次数の場合', correct: false },
        ],
        explanation: 'クラスカル法では、サイクルを作る辺はスキップします。木の条件（サイクルなし）を維持するためです。',
      },
    },
    {
      id: 'alternate',
      title: 'MSTのカット性質',
      content: 'MSTの正当性はカット性質に基づきます。\n\nカット性質：グラフの任意のカット（頂点を2群に分ける）に対して、カットを横断する最軽辺はMSTに含まれる。\n\nこの性質が貪欲法の正当性を保証します。クラスカル法もプリム法もこの性質を利用しています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 最小全域木は重みの合計が最小の全域木\n2. クラスカル法：辺をソートして貪欲に追加\n3. プリム法：木を成長させながら最軽辺を追加\n\nMSTを自分で構成してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'minimum-spanning-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
