import { Tutorial } from '../types';

export const navigationTutorial: Tutorial = {
  id: 'navigation',
  title: '経路探索とナビゲーション',
  description: 'カーナビやマップアプリの経路探索技術をグラフ理論で理解します。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '目的地までの最適ルート',
      content: 'Google Mapsがルートを瞬時に計算できるのはなぜでしょうか？\n\n道路網は巨大グラフであり、最適ルートの計算には高度な技術が必要です。\n\n経路が計算される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'navigation-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ルートを計算しよう',
      content: '地図上で出発地と目的地を選んで、最短ルートを計算しましょう。\n\n時間優先と距離優先で結果が変わります。\n\n交通渋滞の影響も観察してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'navigation-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '大規模グラフの最短経路',
      content: '数百万ノードの道路ネットワークでは素のダイクストラ法は遅すぎます。\n\n高速化技術：\n- 双方向探索：始点と終点の両方から探索\n- A*：ヒューリスティクスで方向を絞る\n- 前計算（CH法）：ショートカット辺を追加\n- ランドマーク法（ALT）：距離の下界を前計算',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'Contraction Hierarchies',
      content: 'CH（Contraction Hierarchies）法：\n\n1. 前処理：頂点を重要度順に縮約し、ショートカット辺を追加\n2. クエリ：上向き探索のみで最短経路を発見\n\n前処理 O(n log n)、クエリ O(k) で、大陸規模の道路ネットワークでもマイクロ秒で応答できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '大規模道路ネットワークの経路探索を高速化する技術はどれですか？',
        options: [
          { id: 'a', label: 'ベルマン・フォード法', correct: false },
          { id: 'b', label: 'ワーシャル・フロイド法', correct: false },
          { id: 'c', label: 'Contraction Hierarchies', correct: true },
          { id: 'd', label: 'プリム法', correct: false },
        ],
        explanation: 'Contraction Hierarchiesは前処理でグラフを縮約し、クエリ時に高速な経路探索を実現します。',
      },
    },
    {
      id: 'alternate',
      title: 'リアルタイム交通情報',
      content: '現実のナビゲーションは時刻によって重みが変わります。\n\n- 時間依存グラフ：辺の重みが時刻の関数\n- リアルタイム更新：交通情報で重みを動的に変更\n- 代替経路：最短以外の「良い」経路も提案\n\nこれらの技術が快適なナビゲーション体験を支えています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 道路ネットワークは巨大グラフとして表現される\n2. CH法やA*で高速な経路探索が可能\n3. リアルタイム交通情報で動的に対応\n\n経路探索を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'navigation-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
