import { Tutorial } from '../types';

export const networkReliabilityTutorial: Tutorial = {
  id: 'network-reliability',
  title: 'ネットワークの信頼性',
  description: 'グラフの連結性を用いてネットワークの信頼性を評価する方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '通信障害に備える',
      content: 'インターネットの一部が故障しても通信が続けられるのはなぜでしょうか？\n\nネットワークの冗長性（信頼性）はグラフ理論で分析できます。\n\nノードが故障していくアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ノードを除去してみよう',
      content: '頂点を1つずつ除去して、ネットワークがいつ分断されるか観察しましょう。\n\n除去すると分断される頂点を「関節点」と呼びます。\n\n関節点を見つけてください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '連結度',
      content: '頂点連結度 κ(G)：グラフを非連結にするために除去が必要な最小頂点数\n辺連結度 λ(G)：グラフを非連結にするために除去が必要な最小辺数\n\nホイットニーの不等式：κ(G) ≤ λ(G) ≤ δ(G)\n（δ(G) は最小次数）',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'メンガーの定理',
      content: 'メンガーの定理：2頂点 u,v 間の独立なパスの最大数は、u-v を分離する最小頂点カットに等しい\n\n独立なパス：内部の頂点を共有しないパス\n\nこの定理はネットワークの冗長性の基礎理論です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '頂点連結度が3のグラフでは、最低何個の頂点を除去するとネットワークが分断されますか？',
        options: [
          { id: 'a', label: '1', correct: false },
          { id: 'b', label: '2', correct: false },
          { id: 'c', label: '3', correct: true },
          { id: 'd', label: '4', correct: false },
        ],
        explanation: '頂点連結度3は、3個の頂点を除去して初めて非連結になることを意味します。',
      },
    },
    {
      id: 'alternate',
      title: '実世界の信頼性設計',
      content: 'インターネットは高い連結度を持つよう設計されています。\n\n- バックボーンネットワーク：複数の独立経路を確保\n- データセンター：冗長な接続\n- 電力網：N-1基準（1か所故障しても動作）\n\nグラフ理論の信頼性解析が設計の基盤です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 連結度はネットワークの耐故障性を定量化する\n2. メンガーの定理が独立パスとカットを結びつける\n3. 実世界のインフラ設計に応用される\n\nネットワークの信頼性を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
