import { Tutorial } from '../types';

export const networkAttackTutorial: Tutorial = {
  id: 'network-attack',
  title: 'ネットワーク攻撃と防御',
  description: 'グラフ理論を用いたネットワークセキュリティの基本を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ネットワークを守る',
      content: 'サイバー攻撃はネットワークの弱点を突きます。\n\nグラフ理論で脆弱性を分析し、防御策を設計できます。\n\nネットワークの弱点が攻撃されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '脆弱点を見つけよう',
      content: 'ネットワークの関節点や橋を見つけましょう。\n\nこれらを除去するとネットワークが分断されます。\n\n最も脆弱な箇所はどこですか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '攻撃モデル',
      content: 'グラフ理論的な攻撃モデル：\n\n- ランダム故障：ノードをランダムに除去\n- 標的攻撃：高次数ノード（ハブ）を優先除去\n- カスケード故障：1つの故障が連鎖的に伝播\n\nスケールフリーネットワークはランダム故障に強いが標的攻撃に弱い特性を持ちます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '防御戦略',
      content: 'グラフ理論的な防御戦略：\n\n- 冗長性の確保：連結度を高める\n- バックアップリンク：橋の代替経路\n- 分散化：単一障害点の排除\n- ファイアウォール配置：最小カットの活用\n\nコスト対効果を考慮した最適な防御設計が重要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'スケールフリーネットワークが最も脆弱なのはどのような攻撃ですか？',
        options: [
          { id: 'a', label: 'ランダムなノード除去', correct: false },
          { id: 'b', label: 'ハブを狙った標的攻撃', correct: true },
          { id: 'c', label: '辺の重みの変更', correct: false },
          { id: 'd', label: '新しいノードの追加', correct: false },
        ],
        explanation: 'スケールフリーネットワークはハブに依存しているため、ハブを標的にした攻撃に最も脆弱です。',
      },
    },
    {
      id: 'alternate',
      title: 'カスケード故障と復元力',
      content: 'カスケード故障：1つのノードの故障が、負荷の再分配を通じて連鎖的に広がる\n\n例：電力網の大停電、金融システムの連鎖破綻\n\n復元力（レジリエンス）の分析にはグラフの構造特性が不可欠です。冗長な経路の確保が鍵になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ネットワークの脆弱性はグラフ構造で分析できる\n2. 攻撃モデルに応じた防御戦略が必要\n3. カスケード故障の理解と対策が重要\n\nネットワーク防御を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
