import { Tutorial } from '../types';

export const pagerankGraphTutorial: Tutorial = {
  id: 'pagerank-graph',
  title: 'PageRankとグラフ',
  description: 'Googleの基礎技術であるPageRankのグラフ理論的な理解を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ウェブページの重要度',
      content: '何十億ものウェブページの中から重要なページを見つけるには？\n\nPageRankはリンク構造をグラフとして分析し、各ページの重要度を計算します。\n\nランクが伝播する様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'pagerank-graph-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'PageRankを計算しよう',
      content: 'リンク構造のグラフでPageRankを計算してみましょう。\n\nリンクを追加・削除して、ランクの変化を観察してください。\n\n多くのページからリンクされるページほどランクが高くなります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'pagerank-graph-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'PageRankの定義',
      content: 'PageRank は各ページの重要度を反復計算します。\n\nPR(v) = (1-d)/n + d × Σ PR(u)/L(u)\n（uはvにリンクするページ、L(u)はuの出次数、dは減衰率≈0.85）\n\nこれはランダムウォークの定常分布に対応します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '行列としての解釈',
      content: 'PageRankは遷移行列 M の最大固有値に対応する固有ベクトルです。\n\nM_{ij} = 1/L(j) （jからiへリンクがある場合）\n\nべき乗法で反復計算できます。\n\nテレポート（確率1-d でランダムなページに移動）がエルゴード性を保証します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'PageRankでページの重要度が高くなる条件は？',
        options: [
          { id: 'a', label: 'ページの文字数が多い', correct: false },
          { id: 'b', label: '多くの重要なページからリンクされている', correct: true },
          { id: 'c', label: 'ページの作成日が新しい', correct: false },
          { id: 'd', label: '出リンクが多い', correct: false },
        ],
        explanation: 'PageRankは「多くの重要なページからリンクされているページは重要」という再帰的な定義に基づきます。',
      },
    },
    {
      id: 'alternate',
      title: 'HITS アルゴリズム',
      content: 'PageRankの代替として HITS（Hypertext-Induced Topic Search）があります。\n\n各ページにハブスコアとオーソリティスコアの2つの値を持たせます。\n\n良いハブは良いオーソリティにリンクし、良いオーソリティは良いハブからリンクされる——この相互依存を反復で解きます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. PageRankはリンク構造からページの重要度を計算\n2. ランダムウォークの定常分布に対応\n3. 行列の固有ベクトルとして解釈できる\n\nPageRankの変化を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'pagerank-graph-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
