import { Tutorial } from '../types';

export const pathConnectivityTutorial: Tutorial = {
  id: 'path-connectivity',
  title: 'パスと連結性',
  description: '頂点間のパスと、グラフが連結であるかどうかを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'たどり着けるか？',
      content: 'ある場所から別の場所に道をたどって行けるかどうか——これはグラフ理論の根本的な問いです。\n\n頂点から頂点へ辺をたどる道筋を「パス」と呼びます。\n\nパスが光る様子を観察してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'パスを見つけよう',
      content: '始点と終点を選んで、パスを見つけてみましょう。\n\n同じ頂点を2度通らない経路を「単純パス」と呼びます。\n\nパスが存在しない頂点のペアはありますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'パスの定義',
      content: 'パスとは、頂点の列 v₀, v₁, ..., vₖ で、連続する各頂点間に辺があるものです。\n\nパスの長さは通過する辺の数 k です。\n\n単純パス：同じ頂点を2度通らないパス\n閉路（サイクル）：始点と終点が同じパス',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '連結性',
      content: 'グラフが連結であるとは、任意の2頂点間にパスが存在することです。\n\n連結でないグラフは複数の連結成分に分かれます。\n\n例：離島がある地図は、島ごとに連結成分が分かれています。道で行ける範囲が1つの連結成分です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '6頂点のグラフに連結成分が3つあるとき、最小の辺の数はいくつですか？',
        options: [
          { id: 'a', label: '2', correct: false },
          { id: 'b', label: '3', correct: true },
          { id: 'c', label: '5', correct: false },
          { id: 'd', label: '6', correct: false },
        ],
        explanation: '各連結成分を最小の辺で連結にするには木構造にします。3つの連結成分に頂点を2,2,2と分けると、各成分に1本の辺が必要で合計3本です。',
      },
    },
    {
      id: 'alternate',
      title: '連結性の強さ',
      content: 'グラフの連結性にはレベルがあります。\n\nk-頂点連結：任意のk-1頂点を除いても連結\nk-辺連結：任意のk-1辺を除いても連結\n\n高い連結性は、ネットワークの故障耐性の高さを意味します。インターネットは高い連結性を持つよう設計されています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. パスは頂点間を辺で結ぶ経路\n2. 連結グラフは任意の2頂点間にパスが存在する\n3. 連結性の強さはネットワークの信頼性に直結する\n\nグラフを操作してパスと連結性を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
