import { Tutorial } from '../types';

export const planarGraphTutorial: Tutorial = {
  id: 'planar-graph',
  title: '平面グラフ',
  description: '辺が交差しないように平面に描けるグラフを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '交差しない配線',
      content: '回路基板の配線は、できるだけ交差しないように設計したいですね。\n\n辺が交差しないように平面に描けるグラフを「平面グラフ」と呼びます。\n\nグラフが平面に展開される様子を観察してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'planar-graph-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '頂点を動かして平面的に描こう',
      content: '頂点をドラッグして、辺が交差しないように配置してみましょう。\n\n平面グラフなら必ず交差なしに描けます。\n\n交差をゼロにできないグラフは非平面的です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'planar-graph-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '平面グラフの性質',
      content: '平面グラフは平面を「面」に分割します。外側の無限領域も1つの面として数えます。\n\nオイラーの公式：V - E + F = 2\n（V:頂点数、E:辺数、F:面数）\n\nこの式から、平面グラフでは E ≤ 3V - 6 が成り立ちます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'クラトウスキーの定理',
      content: 'グラフが平面グラフでないための条件：\n\nクラトウスキーの定理：グラフが平面的 ⟺ K₅ または K₃,₃ の細分を部分グラフとして含まない\n\nK₅（完全グラフ）と K₃,₃（完全二部グラフ）は最小の非平面グラフです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '平面グラフでV=6, E=10のとき、面の数Fはいくつですか？',
        options: [
          { id: 'a', label: '4', correct: false },
          { id: 'b', label: '5', correct: false },
          { id: 'c', label: '6', correct: true },
          { id: 'd', label: '8', correct: false },
        ],
        explanation: 'オイラーの公式 V - E + F = 2 より、6 - 10 + F = 2、F = 6 です。',
      },
    },
    {
      id: 'alternate',
      title: '交差数',
      content: '非平面グラフでも、交差の数を最小化することは重要です。\n\nこの最小交差数を「交差数」と呼びます。\n\nVLSI設計やグラフ描画アルゴリズムで重要な概念です。交差数の計算自体もNP困難です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 平面グラフは辺の交差なしに平面に描ける\n2. オイラーの公式：V - E + F = 2\n3. K₅とK₃,₃が非平面性の判定に使われる\n\n頂点を動かして平面的な配置を探してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'planar-graph-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
