import { Tutorial } from '../types';

export const ramseyTheoryTutorial: Tutorial = {
  id: 'ramsey-theory',
  title: 'ラムゼー理論',
  description: '「完全な無秩序は不可能」というラムゼー理論の基本を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '秩序は必ず生まれる',
      content: '6人のパーティーでは、必ず3人の互いに知り合いか、3人の互いに見知らぬ人が存在します。\n\nこの驚くべき事実がラムゼー理論の出発点です。\n\n完全グラフが2色に塗り分けられる様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ramsey-theory-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '2色で塗ってみよう',
      content: 'K₆（6頂点の完全グラフ）の辺を赤と青の2色で塗り分けてみましょう。\n\n同色の三角形を避けることはできるでしょうか？\n\nどう塗っても必ず単色三角形ができることを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ramsey-theory-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ラムゼー数',
      content: 'ラムゼー数 R(s,t)：辺を2色で塗ったとき、赤の完全グラフ K_s か青の完全グラフ K_t が必ず現れる最小頂点数\n\nR(3,3) = 6：6人の集まりで上記の性質が成立\n\nR(4,4) = 18 は知られていますが、R(5,5) は未解決です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'ラムゼー数の爆発的増加',
      content: 'ラムゼー数は非常に急速に増加します。\n\nエルデシュの名言：「5×5のラムゼー数を求めよと脅す宇宙人が来たら、全人類で計算に挑むべきだ。6×6なら……宇宙人を攻撃した方がいい。」\n\n上界：R(s,t) ≤ C(s+t-2, s-1)\n下界の構成は確率的手法で示されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'R(3,3)の値はいくつですか？',
        options: [
          { id: 'a', label: '3', correct: false },
          { id: 'b', label: '5', correct: false },
          { id: 'c', label: '6', correct: true },
          { id: 'd', label: '9', correct: false },
        ],
        explanation: 'R(3,3)=6は、6人の集まりで必ず3人の互いの知り合いか、3人の互いの見知らぬ人がいることを意味します。',
      },
    },
    {
      id: 'alternate',
      title: '無限ラムゼー理論',
      content: '無限集合にもラムゼー型の結果があります。\n\n無限ラムゼーの定理：自然数の対を有限色で塗ると、すべての対が同色の無限部分集合が存在する\n\nこれは組合せ論、集合論、位相幾何学に深い影響を与えています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ラムゼー理論は「完全な無秩序は不可能」を示す\n2. R(3,3)=6が最も基本的なラムゼー数\n3. ラムゼー数の正確な値の計算は極めて困難\n\n辺の塗り分けを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'ramsey-theory-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
