import { Tutorial } from '../types';

export const randomGraphTutorial: Tutorial = {
  id: 'random-graph',
  title: 'ランダムグラフ',
  description: 'エルデシュ・レーニイモデルとランダムグラフの性質を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '偶然が生む構造',
      content: 'コインを投げて辺を作るか決める——このシンプルな操作で驚くべき構造が生まれます。\n\nランダムグラフは確率論とグラフ理論の融合です。\n\nランダムに辺が追加されていくアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ランダムグラフを生成しよう',
      content: '辺の確率 p を調整して、ランダムグラフの性質を観察しましょう。\n\np を変えると連結性やクラスタリングがどう変わるか確認してください。\n\n閾値現象を探してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'エルデシュ・レーニイモデル',
      content: 'G(n,p) モデル：n頂点で、各辺が独立に確率 p で存在\n\n期待辺数：n(n-1)p/2\n期待次数：(n-1)p\n\n重要な閾値：\n- p = 1/n あたりで巨大連結成分が出現\n- p = ln(n)/n あたりでグラフが連結になる',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '閾値現象',
      content: 'ランダムグラフには劇的な「閾値現象」があります。\n\nある確率を境に、性質が突然現れます（相転移）：\n\n- p ≪ 1/n：孤立した辺と頂点\n- p ≈ 1/n：巨大成分の出現\n- p ≈ ln(n)/n：ほぼ確実に連結\n- p = 1/2：ほぼすべてのグラフ',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'G(n,p) モデルでグラフがほぼ確実に連結になる閾値は？',
        options: [
          { id: 'a', label: 'p = 1/n²', correct: false },
          { id: 'b', label: 'p = 1/n', correct: false },
          { id: 'c', label: 'p = ln(n)/n', correct: true },
          { id: 'd', label: 'p = 1/2', correct: false },
        ],
        explanation: 'p = ln(n)/n が連結性の閾値です。これ以上の確率では高確率で連結になり、以下では非連結です。',
      },
    },
    {
      id: 'alternate',
      title: '確率的手法',
      content: 'エルデシュはランダムグラフを使って「存在証明」を行いました。\n\nランダムに選んだグラフが高確率で性質を持つなら、その性質を持つグラフが存在する——これが確率的手法です。\n\nラムゼー理論の下界もこの方法で示されました。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ランダムグラフ G(n,p) は辺を確率的に生成\n2. 閾値現象で性質が突然変化する\n3. 確率的手法は存在証明の強力なツール\n\nパラメータを変えてランダムグラフを探索しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
