import { Tutorial } from '../types';

export const recommendationTutorial: Tutorial = {
  id: 'recommendation',
  title: '推薦アルゴリズム',
  description: 'グラフベースの推薦システムの仕組みを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'あなたへのおすすめ',
      content: 'ECサイトの「おすすめ商品」はどうやって選ばれているのでしょうか？\n\nユーザーと商品の関係をグラフで表現すると、推薦問題が見えてきます。\n\n二部グラフ上の推薦が生成されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '推薦を生成しよう',
      content: 'ユーザー・アイテム二部グラフで、まだ見ていないアイテムのスコアを計算しましょう。\n\n類似ユーザーが好むアイテムほど高スコアになります。\n\n推薦リストを確認してください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '協調フィルタリング',
      content: 'グラフベースの協調フィルタリング：\n\n- ユーザーベース：類似ユーザーの嗜好を参考にする\n- アイテムベース：類似アイテムを推薦する\n\n類似度の計算にグラフ上のランダムウォークやパスの長さを使えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'グラフ畳み込みによる推薦',
      content: 'GNNを使った推薦システム：\n\n- LightGCN：隣接情報の集約のみでシンプルかつ高性能\n- PinSage：Pinterestの数十億ノードのグラフに適用\n\nユーザーとアイテムの埋め込みを学習し、内積で推薦スコアを計算します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'グラフベースの推薦で「類似ユーザー」を見つけるのに有用なのは？',
        options: [
          { id: 'a', label: 'グラフの彩色数', correct: false },
          { id: 'b', label: 'ユーザー・アイテム二部グラフの構造', correct: true },
          { id: 'c', label: 'トポロジカルソート', correct: false },
          { id: 'd', label: '最小全域木', correct: false },
        ],
        explanation: 'ユーザー・アイテム二部グラフの構造（共通購入アイテムなど）から類似ユーザーを特定できます。',
      },
    },
    {
      id: 'alternate',
      title: '知識グラフとの連携',
      content: '推薦システムに知識グラフを組み合わせると、推薦の説明可能性が向上します。\n\n例：「この映画をおすすめする理由：同じ監督の作品を好んでいます」\n\nエンティティ間の関係をグラフで表現し、推薦の質と説明力を高めます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 推薦はユーザー・アイテム二部グラフの問題\n2. 協調フィルタリングとGNNベースの方法がある\n3. 知識グラフで説明可能性を向上\n\n推薦アルゴリズムを操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
