import { Tutorial } from '../types';

export const scaleFreeTutorial: Tutorial = {
  id: 'scale-free',
  title: 'スケールフリーネットワーク',
  description: 'べき乗則に従う次数分布を持つネットワークを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'ハブの力',
      content: 'インターネットには数千のリンクを持つサイトと、数本しかないサイトがあります。\n\nこの極端な格差は「スケールフリー」ネットワークの特徴です。\n\n次数分布がべき乗則に従うアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'scale-free-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'ハブを見つけよう',
      content: 'ネットワーク内でリンク数（次数）が特に多い「ハブ」を見つけましょう。\n\n次数分布のヒストグラムを観察してください。\n\nランダムグラフとの違いは何ですか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'scale-free-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'バラバシ・アルバートモデル',
      content: '優先的選択（preferential attachment）：次数が高い頂点にさらに辺がつきやすい\n\n1. 少数の頂点で開始\n2. 新しい頂点を追加し、既存頂点に確率 k_i/Σk で接続\n\n結果：次数分布が P(k) ∝ k^(-γ)（γ≈3）のべき乗則に従う',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'スケールフリーの特徴',
      content: 'スケールフリーネットワークの特徴：\n\n- 少数のハブが多数のリンクを持つ\n- ランダム故障に強いが、標的攻撃に弱い\n- ハブを除去するとネットワークが急速に崩壊\n\n例：インターネット、SNS、代謝ネットワーク、航空網',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'スケールフリーネットワークが脆弱なのはどのような場合ですか？',
        options: [
          { id: 'a', label: '辺がランダムに除去される場合', correct: false },
          { id: 'b', label: 'ハブが標的攻撃される場合', correct: true },
          { id: 'c', label: '新しい頂点が追加される場合', correct: false },
          { id: 'd', label: '重みが変化する場合', correct: false },
        ],
        explanation: 'スケールフリーネットワークはランダム故障には耐性がありますが、ハブを狙った標的攻撃には脆弱です。',
      },
    },
    {
      id: 'alternate',
      title: 'ロバストでありフラジャイル',
      content: 'スケールフリーネットワークの二面性：\n\n- ロバスト（堅牢）：ランダム故障に強い\n- フラジャイル（脆弱）：ハブへの攻撃に弱い\n\nこれは「Robust yet Fragile」と呼ばれ、多くの実世界ネットワークの特性です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. スケールフリーネットワークはべき乗則の次数分布を持つ\n2. 優先的選択がハブを生む\n3. ランダム故障に強く標的攻撃に弱い\n\nネットワークを操作して性質を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'scale-free-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
