import { Tutorial } from '../types';

export const shortestPathTutorial: Tutorial = {
  id: 'shortest-path',
  title: '最短経路問題',
  description: '重み付きグラフで2頂点間の最短経路を求める基本的な方法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '最速ルートを見つけろ',
      content: 'カーナビが最短ルートを教えてくれるのは、グラフアルゴリズムのおかげです。\n\n道路網をグラフ、距離を重みとして、最短経路を計算します。\n\nダイクストラ法で最短経路が見つかる様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '最短経路を探そう',
      content: '始点と終点を選んで最短経路を探してみましょう。\n\n各頂点までの暫定距離が更新されていく過程を観察してください。\n\n重みの異なる経路を比較してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ダイクストラ法',
      content: 'ダイクストラ法：非負重みグラフの単一始点最短経路\n\n1. 始点の距離を0、他を∞に初期化\n2. 未確定の頂点のうち距離最小の頂点vを確定\n3. vの隣接頂点の距離を更新（緩和）\n4. すべて確定するまで繰り返し\n\n計算量：O((V+E) log V)（優先度キュー使用時）',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'BFSによる最短経路',
      content: '重みなしグラフ（すべての辺の重みが1）では、BFS（幅優先探索）で最短経路が求まります。\n\nBFSは始点から近い頂点を順に探索するため、最初に到達した時点の距離が最短です。\n\n計算量：O(V+E)で、ダイクストラ法より高速です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ダイクストラ法が正しく動作しないのはどのような場合ですか？',
        options: [
          { id: 'a', label: 'グラフが大きい場合', correct: false },
          { id: 'b', label: '辺に負の重みがある場合', correct: true },
          { id: 'c', label: 'グラフが有向の場合', correct: false },
          { id: 'd', label: '辺の重みが整数でない場合', correct: false },
        ],
        explanation: 'ダイクストラ法は非負の重みを前提としています。負の重みがある場合、確定した距離が後から短くなる可能性があり、正しく動作しません。',
      },
    },
    {
      id: 'alternate',
      title: '全対最短経路',
      content: 'ダイクストラ法は1つの始点からの最短経路を求めます。\n\nすべてのペア間の最短経路が必要な場合は：\n- ダイクストラ法をV回実行：O(V(V+E) log V)\n- ワーシャル・フロイド法：O(V³)\n\n密グラフではワーシャル・フロイド法が効率的です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ダイクストラ法は非負重みグラフの最短経路を求める\n2. 重みなしグラフではBFSが最適\n3. 全対最短経路にはワーシャル・フロイド法も有効\n\n最短経路を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
