import { Tutorial } from '../types';

export const smallWorldTutorial: Tutorial = {
  id: 'small-world',
  title: 'スモールワールドネットワーク',
  description: '六次の隔たりとスモールワールド現象を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '世界は狭い？',
      content: '地球上の誰とでも、6人の知り合いの連鎖でつながれる——「六次の隔たり」です。\n\nこの驚くべき現象をスモールワールドネットワークが説明します。\n\n短い経路が見つかるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'small-world-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '最短距離を測ろう',
      content: 'ネットワーク内の任意の2頂点間の最短距離を測ってみましょう。\n\nノード数に比べて驚くほど短いパスが見つかるはずです。\n\n平均パス長はどのくらいですか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'small-world-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ワッツ・ストロガッツモデル',
      content: '規則的なリング格子の辺を確率 p で張り替えます。\n\n- p=0：規則的（クラスタリング高、パス長大）\n- p=1：ランダム（クラスタリング低、パス長小）\n- 中間の p：両方の良い性質（スモールワールド）\n\n少数のショートカットで平均パス長が劇的に短縮されます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '実世界のスモールワールド',
      content: 'スモールワールド性を持つネットワーク：\n\n- 社会的ネットワーク（友人関係）\n- 脳の神経回路\n- 電力網\n- 映画俳優の共演ネットワーク\n\n高いクラスタリング係数と短い平均パス長が特徴です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'スモールワールドネットワークの特徴として正しいものはどれですか？',
        options: [
          { id: 'a', label: 'すべての頂点の次数が等しい', correct: false },
          { id: 'b', label: '高いクラスタリングと短い平均パス長', correct: true },
          { id: 'c', label: '辺の数が少ない', correct: false },
          { id: 'd', label: '完全にランダムな構造', correct: false },
        ],
        explanation: 'スモールワールドネットワークは高いクラスタリング係数（局所的に密なつながり）と短い平均パス長（グローバルな近さ）を両立します。',
      },
    },
    {
      id: 'alternate',
      title: 'ミルグラム実験',
      content: '1967年、スタンレー・ミルグラムは手紙転送実験で六次の隔たりを検証しました。\n\nネブラスカの人からボストンの人へ、知人を介して手紙を転送。\n\n平均約6ステップで届きました。この実験はネットワーク科学の基礎となりました。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. スモールワールドは高クラスタリング＋短パス長\n2. 少数のショートカットで平均パス長が激減\n3. 社会ネットワークや脳に広く見られる\n\nネットワークを操作してスモールワールド性を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'small-world-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
