import { Tutorial } from '../types';

export const socialNetworkTutorial: Tutorial = {
  id: 'social-network',
  title: 'ソーシャルネットワーク分析',
  description: 'SNSの友人関係をグラフ理論で分析する手法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'SNSをグラフで解析',
      content: 'Facebook、Twitter、LINEの友人関係はグラフそのものです。\n\n中心性、クラスタリング係数、コミュニティ構造——グラフ理論でSNSを深く理解できます。\n\nソーシャルネットワークの構造を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '中心性を計算しよう',
      content: 'ネットワーク内で「重要な人物」を見つけましょう。\n\n次数中心性、媒介中心性、近接中心性を比較してください。\n\nそれぞれの指標で異なる人物が「重要」になります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '中心性指標',
      content: '主な中心性指標：\n\n- 次数中心性：つながりの数（人気度）\n- 媒介中心性：最短経路上に位置する頻度（仲介者）\n- 近接中心性：他の頂点への平均距離の逆数（情報伝達の早さ）\n- 固有ベクトル中心性：重要な人とつながっている度合い',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'ソーシャルネットワークの特徴',
      content: '実際のSNSの特徴：\n\n- スモールワールド性（短い平均パス長）\n- 高いクラスタリング係数（友人の友人も友人）\n- スケールフリー性（インフルエンサーの存在）\n- コミュニティ構造（グループ形成）',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ネットワークで「仲介者」としての重要度を測る指標はどれですか？',
        options: [
          { id: 'a', label: '次数中心性', correct: false },
          { id: 'b', label: '媒介中心性', correct: true },
          { id: 'c', label: '近接中心性', correct: false },
          { id: 'd', label: 'クラスタリング係数', correct: false },
        ],
        explanation: '媒介中心性は、最短経路上に位置する頻度を測り、情報の仲介者としての重要度を表します。',
      },
    },
    {
      id: 'alternate',
      title: '影響力の伝播',
      content: 'SNS上での情報拡散やバイラルマーケティングも、グラフ上の伝播問題として分析できます。\n\n独立カスケードモデルや線形閾値モデルで拡散をシミュレートし、影響力最大化問題として最適なシードユーザーを選びます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. SNSはグラフとして分析できる\n2. 中心性指標で重要なノードを特定\n3. 影響力の伝播もグラフ上の問題\n\nネットワークを操作して分析してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
