import { Tutorial } from '../types';

export const spanningTreeTutorial: Tutorial = {
  id: 'spanning-tree',
  title: '全域木',
  description: 'グラフのすべての頂点を含む部分木について学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '最小のネットワーク',
      content: 'すべてのコンピュータを接続するのに、最少の配線で済ませたい。\n\nすべての頂点を含みつつ辺数が最小の連結部分グラフ——それが全域木です。\n\n不要な辺が削られて木が残るアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '全域木を作ろう',
      content: 'グラフから辺を選んで全域木を構成しましょう。\n\nルール：サイクルを作らず、すべての頂点を連結にする辺の集合を選びます。\n\nn頂点なら n-1 本の辺が必要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '全域木の定義',
      content: '全域木（spanning tree）は、グラフのすべての頂点を含む部分グラフで、木であるものです。\n\n性質：\n- n頂点の連結グラフには必ず全域木が存在する\n- 全域木は n-1 本の辺を持つ\n- 全域木に辺を1本加えるとサイクルが1つできる',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '全域木の数え方',
      content: '完全グラフ K_n の全域木の数はケイリーの公式で求められます：\n\nT(K_n) = n^(n-2)\n\n例：K₃ は 3 本、K₄ は 16 本の全域木を持ちます。\n\n一般のグラフではキルヒホッフの行列木定理で計算できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '8頂点の連結グラフの全域木の辺の数はいくつですか？',
        options: [
          { id: 'a', label: '8', correct: false },
          { id: 'b', label: '7', correct: true },
          { id: 'c', label: '6', correct: false },
          { id: 'd', label: '9', correct: false },
        ],
        explanation: 'n頂点の木は必ず n-1 本の辺を持つので、8頂点の全域木は7本の辺を持ちます。',
      },
    },
    {
      id: 'alternate',
      title: 'DFS木とBFS木',
      content: '全域木は探索アルゴリズムで構成できます。\n\nDFS木：深さ優先探索で得られる全域木。「後退辺」がサイクル検出に使える。\nBFS木：幅優先探索で得られる全域木。根からの最短パスを保持。\n\nどちらの方法でも O(V+E) で構成可能です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 全域木はすべての頂点を含むサイクルのない連結部分グラフ\n2. n頂点の全域木は n-1 本の辺を持つ\n3. DFSやBFSで構成できる\n\n全域木を自分で構成してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
