import { Tutorial } from '../types';

export const spectralGraphTutorial: Tutorial = {
  id: 'spectral-graph',
  title: 'スペクトルグラフ理論入門',
  description: 'グラフのラプラシアン行列とその固有値が持つ意味を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '行列でグラフを解析する',
      content: 'グラフの構造を行列の固有値で理解する——これがスペクトルグラフ理論です。\n\n隣接行列やラプラシアン行列の固有値はグラフの性質を反映します。\n\n固有値が変化するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'spectral-graph-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '固有値を観察しよう',
      content: 'グラフの辺を変更して、ラプラシアン行列の固有値がどう変わるか観察しましょう。\n\n特に最小の非ゼロ固有値（代数的連結度）に注目してください。\n\n辺を追加・削除してみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'spectral-graph-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'ラプラシアン行列',
      content: 'グラフラプラシアン L = D - A\n- D：次数行列（対角行列）\n- A：隣接行列\n\nLの性質：\n- 半正定値（固有値は非負）\n- 最小固有値は常に0\n- 0の固有値の重複度 = 連結成分の数',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'スペクトルの意味',
      content: 'ラプラシアンの固有値の意味：\n\n- λ₁ = 0：常に存在\n- λ₂（代数的連結度）：大きいほど連結性が高い\n- チーガー不等式：λ₂ と最小カットの関係\n\n固有ベクトルはグラフの分割（スペクトルクラスタリング）に使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'ラプラシアン行列の最小固有値0の重複度は何を表しますか？',
        options: [
          { id: 'a', label: '辺の数', correct: false },
          { id: 'b', label: '連結成分の数', correct: true },
          { id: 'c', label: '最大次数', correct: false },
          { id: 'd', label: '彩色数', correct: false },
        ],
        explanation: 'ラプラシアン行列の固有値0の重複度は、グラフの連結成分の数と一致します。',
      },
    },
    {
      id: 'alternate',
      title: 'スペクトルクラスタリング',
      content: 'ラプラシアンの固有ベクトルを使ったクラスタリング：\n\n1. ラプラシアン L の最小固有ベクトルを k 個計算\n2. 各頂点を k 次元の特徴量で表現\n3. k-means等でクラスタリング\n\nコミュニティ検出やデータクラスタリングに広く使われています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. ラプラシアン L = D - A でグラフを行列表現\n2. 固有値がグラフの連結性を反映\n3. スペクトルクラスタリングに応用される\n\n固有値の変化を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'spectral-graph-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
