import { Tutorial } from '../types';

export const stronglyConnectedTutorial: Tutorial = {
  id: 'strongly-connected',
  title: '強連結成分',
  description: '有向グラフの強連結成分分解とそのアルゴリズムを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '互いに行き来できるグループ',
      content: '有向グラフで、互いに到達可能な頂点同士をグループにまとめたい。\n\nこのグループが「強連結成分（SCC）」です。\n\nSCCが色分けされるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'SCCを見つけよう',
      content: '有向グラフの頂点をグループ分けして、強連結成分を特定しましょう。\n\n互いに到達可能な頂点を同じ色でまとめてください。\n\nすべてのSCCを見つけられますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'コサラジュのアルゴリズム',
      content: 'コサラジュのアルゴリズム：\n\n1. 元のグラフでDFSを実行し、終了時刻の降順で頂点を並べる\n2. すべての辺を逆向きにした転置グラフを作る\n3. 転置グラフ上で、上記の順序でDFSを実行\n4. 各DFS木が1つのSCCに対応\n\n計算量：O(V+E)',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'タージャンのアルゴリズム',
      content: 'タージャンのアルゴリズムはDFS1回でSCCを求めます。\n\n各頂点に発見時刻とlowlink値を記録し、スタックを使ってSCCを検出します。\n\nlowlink[v] = vからDFS木の辺と後退辺で到達できる最小発見時刻\n\n計算量：O(V+E)で、コサラジュより実装がやや複雑です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '強連結成分を縮約して得られるグラフはどのような構造になりますか？',
        options: [
          { id: 'a', label: '木', correct: false },
          { id: 'b', label: 'DAG（有向非巡回グラフ）', correct: true },
          { id: 'c', label: '完全グラフ', correct: false },
          { id: 'd', label: '二部グラフ', correct: false },
        ],
        explanation: 'SCCを1つの頂点に縮約すると、サイクルがなくなるためDAGになります。SCCの間にサイクルがあればより大きなSCCに統合されるはずだからです。',
      },
    },
    {
      id: 'alternate',
      title: 'SCC DAGの活用',
      content: 'SCCを縮約したDAGは様々な問題に活用できます。\n\n- 2-SAT問題の解法\n- 有向グラフの到達可能性解析\n- コンパイラの最適化（関数呼び出しグラフの解析）\n\nSCC分解は有向グラフ解析の最も基本的なツールの一つです。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 強連結成分は互いに到達可能な頂点の最大集合\n2. コサラジュ・タージャンのアルゴリズムで O(V+E) で求まる\n3. SCC縮約はDAGを生み、様々な問題に応用できる\n\nSCCの分解を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
