import { Tutorial } from '../types';

export const temporalGraphTutorial: Tutorial = {
  id: 'temporal-graph',
  title: '時系列グラフ',
  description: '時間とともに変化するグラフの分析手法を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '変化するネットワーク',
      content: '友人関係は時間とともに変わります。通信記録にはタイムスタンプがあります。\n\n時間を考慮したグラフが「時系列グラフ」です。\n\nネットワークが時間とともに変化するアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '時間変化を観察しよう',
      content: 'タイムスライダーを動かして、ネットワークの変化を観察しましょう。\n\nどのエッジがいつ現れ、いつ消えるか確認してください。\n\n時間的な到達可能性は静的グラフと異なります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '時系列グラフの定義',
      content: '時系列グラフ（temporal graph）：各辺にタイムスタンプが付与\n\nG = (V, E, T) where E ⊆ V × V × T\n\n時間的パス：辺のタイムスタンプが非減少のパス\n\n静的グラフでは到達可能でも、時間的には到達不可能な場合があります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '時系列グラフの分析',
      content: '時系列グラフ特有の問題：\n\n- 時間的最短パス：最早到着、最速、最短（辺数最少）\n- 時間的連結性：任意の時点での連結性\n- バースト検出：辺の出現頻度の異常\n\n感染症の伝播分析にも時系列グラフが使われます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '時系列グラフの「時間的パス」の条件として正しいものは？',
        options: [
          { id: 'a', label: '辺の重みが非減少', correct: false },
          { id: 'b', label: '辺のタイムスタンプが非減少', correct: true },
          { id: 'c', label: '頂点の次数が非減少', correct: false },
          { id: 'd', label: 'パスの長さが非減少', correct: false },
        ],
        explanation: '時間的パスでは、使う辺のタイムスタンプが時間的に後になっていく（非減少）必要があります。',
      },
    },
    {
      id: 'alternate',
      title: '動的グラフアルゴリズム',
      content: '動的グラフでは辺の追加・削除に対して効率的に更新するアルゴリズムが必要です。\n\n- 動的連結性：O(log² n) で辺の追加削除と連結性クエリ\n- 動的最短路：辺の変更に応じて最短距離を更新\n\nこれらはオンラインアルゴリズムとも呼ばれます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 時系列グラフは辺にタイムスタンプを持つ\n2. 時間的パスは静的パスと異なる\n3. 感染症分析や動的ネットワークに応用\n\n時間変化を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
