import { Tutorial } from '../types';

export const topologicalSortTutorial: Tutorial = {
  id: 'topological-sort',
  title: 'トポロジカルソート',
  description: '有向非巡回グラフ（DAG）の頂点を順序付けるトポロジカルソートを学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: 'タスクの順序を決める',
      content: 'プロジェクトのタスクには依存関係があります。先に終わらせるべきタスクが後になってはいけません。\n\nこの順序付けがトポロジカルソートです。\n\nタスクが順番に整列されるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: 'タスクの順序を操作しよう',
      content: '依存関係のある有向グラフでトポロジカル順序を構成してみましょう。\n\n頂点をドラッグして正しい順序に並べてください。\n\n入次数が0の頂点から始められます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: 'トポロジカルソートの定義',
      content: '有向非巡回グラフ（DAG）のトポロジカルソートとは、すべての辺 (u,v) について u が v より前に来る頂点の線形順序です。\n\nDAGにのみ存在し、サイクルがあると不可能です。\n\nKahnのアルゴリズム：入次数0の頂点を繰り返し除去する方法。O(V+E)。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'DFSによるトポロジカルソート',
      content: 'DFSの終了時刻の逆順がトポロジカル順序になります。\n\n1. 各頂点についてDFSを実行\n2. 頂点の処理が完了したらスタックに追加\n3. スタックの逆順がトポロジカル順序\n\nこちらも O(V+E) で動作します。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'DAGでないグラフにトポロジカルソートを適用するとどうなりますか？',
        options: [
          { id: 'a', label: '適用できない（サイクルがあるため）', correct: false },
          { id: 'b', label: '結果が複数通りになる', correct: true },
          { id: 'c', label: 'ランダムな順序が得られる', correct: false },
          { id: 'd', label: '逆順になる', correct: false },
        ],
        explanation: 'a',
      },
    },
    {
      id: 'alternate',
      title: 'トポロジカルソートはDAG（有向非巡回グラフ）にのみ定義されます。サイクルがあると、前後関係が矛盾するため順序付けができません。',
      content: 'コンパイルの依存関係',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: 'makefileやビルドシステムでは、ソースファイルの依存関係をDAGで表現します。\n\nトポロジカルソートでコンパイル順序を決定します。\n\n大学の履修計画も同様で、前提科目の依存関係をDAGで表してトポロジカルソートで計画を立てられます。|トポロジカルソートを操作して順序を確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
