import { Tutorial } from '../types';

export const tspAdvancedTutorial: Tutorial = {
  id: 'tsp-advanced',
  title: '巡回セールスマン問題深化',
  description: 'TSPの厳密解法と近似アルゴリズムを深く学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '最短巡回路の追求',
      content: '巡回セールスマン問題（TSP）は最も有名な組合せ最適化問題です。\n\nn都市をすべて1回ずつ訪問して戻る最短ルートを求めます。\n\n様々な近似解が改善される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '近似解を改善しよう',
      content: '初期解（最近傍法）から2-opt改善を適用してルートを短くしましょう。\n\n2本の辺を入れ替えて距離が短くなるか試してください。\n\nどこまで改善できますか？',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '厳密解法',
      content: 'TSPの厳密解法：\n\n- 全探索：O(n!)、小規模のみ\n- Held-Karpの動的計画法：O(n² 2ⁿ)\n- 分枝限定法：上界と下界で枝刈り\n- 整数計画法：巡回路の定式化をソルバーで解く\n\n現在、数万都市規模まで厳密に解かれています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '近似アルゴリズム',
      content: 'TSPの近似アルゴリズム：\n\n- 最近傍法：O(n²)、近似比保証なし\n- クリストフィデスのアルゴリズム：3/2近似（メトリックTSP）\n- LKH（Lin-Kernighan-Helsgott）：実用的に最良\n\nクリストフィデスの3/2近似は1976年以来最良の理論的保証です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: 'クリストフィデスのアルゴリズムの近似比はどれですか？',
        options: [
          { id: 'a', label: '1.0（最適解）', correct: false },
          { id: 'b', label: '3/2', correct: true },
          { id: 'c', label: '2', correct: false },
          { id: 'd', label: 'log n', correct: false },
        ],
        explanation: 'クリストフィデスのアルゴリズムはメトリックTSPに対して3/2近似を保証します。',
      },
    },
    {
      id: 'alternate',
      title: 'メタヒューリスティクス',
      content: 'TSPのメタヒューリスティクス：\n\n- 焼きなまし法（SA）：温度パラメータで探索と収束を制御\n- 遺伝的アルゴリズム（GA）：交叉と突然変異で解を進化\n- アリコロニー最適化：フェロモンで経路を学習\n\nこれらは最適性保証はないが、大規模問題で実用的な解を素早く得られます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. TSPはNP困難の代表的問題\n2. 厳密解と近似解の両方のアプローチがある\n3. メタヒューリスティクスが実用的に有効\n\nTSPの解を操作して改善しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
