import { Tutorial } from '../types';

export const vehicleRoutingTutorial: Tutorial = {
  id: 'vehicle-routing',
  title: '車両配送問題',
  description: '複数の車両で効率的に配送する最適化問題を学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '配送ルートの最適化',
      content: 'Amazon やヤマト運輸の配送ルートはどう決まっているのでしょうか？\n\n複数の車両で複数の配送先を効率的にカバーする——これが車両配送問題（VRP）です。\n\n最適な配送ルートが構成される様子を見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '配送計画を立てよう',
      content: '複数の車両の配送ルートを計画しましょう。\n\n各車両の容量制約と顧客の需要を考慮してください。\n\n総走行距離を最小にする計画を見つけてください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '車両配送問題の種類',
      content: 'VRPのバリエーション：\n\n- CVRP：容量制約付きVRP\n- VRPTW：時間枠制約付きVRP\n- DVRP：動的VRP（リアルタイムに注文追加）\n- MDVRP：複数デポVRP\n\nいずれもNP困難ですが、実用的な解法が開発されています。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: 'VRPの解法',
      content: 'VRPの解法：\n\n- 構築法：セービング法、挿入法\n- 改善法：or-opt、cross-exchange\n- メタヒューリスティクス：LNS（大近傍探索）\n- 機械学習：Attention Model（Transformer応用）\n\nOR-Toolsなどのライブラリで実装できます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '車両配送問題はTSPとどのような関係がありますか？',
        options: [
          { id: 'a', label: 'VRPはTSPの特殊ケース', correct: false },
          { id: 'b', label: 'TSPはVRP（車両1台）の特殊ケース', correct: true },
          { id: 'c', label: '関係がない', correct: false },
          { id: 'd', label: 'VRPはTSPより簡単', correct: false },
        ],
        explanation: 'TSPは車両が1台のVRPの特殊ケースです。VRPはTSPを一般化した問題であり、さらに複雑です。',
      },
    },
    {
      id: 'alternate',
      title: 'ラストマイル配送',
      content: 'ラストマイル配送（最終区間の配送）は物流コストの大部分を占めます。\n\n最適化のポイント：\n- クラスタリングで配送エリアを分割\n- 各エリア内でTSPを解く\n- ドローンやロボットとの組み合わせ\n\nリアルタイムの動的最適化が今後の課題です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. VRPは複数車両の配送ルート最適化\n2. TSPの一般化でNP困難\n3. メタヒューリスティクスや機械学習で実用的に解ける\n\n配送計画を操作して確認しましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
