import { Tutorial } from '../types';

export const weightedGraphTutorial: Tutorial = {
  id: 'weighted-graph',
  title: '重み付きグラフ',
  description: '辺に重み（コスト・距離など）を持たせたグラフについて学びます。',
  category: 'graph-theory',
  steps: [
    {
      id: 'hook',
      title: '距離も大切',
      content: '東京から大阪へ行く方法はたくさんありますが、距離や時間はルートによって異なります。\n\nグラフの辺に「重み」を付けると、こうした違いを表現できます。\n\n重みの大小で辺の太さが変わるアニメーションを見てみましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'weighted-graph-animation',
      interactive: false,
      nextCondition: 'click',
      stepType: 'animation',
    },
    {
      id: 'touch',
      title: '重みを変更してみよう',
      content: '辺の重みを変更して、グラフの見た目がどう変わるか確認しましょう。\n\n重みは距離、コスト、時間、容量など様々な意味を持てます。\n\n辺をクリックして重みを調整してみてください。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'weighted-graph-interactive',
      interactive: true,
      nextCondition: 'interaction',
      stepType: 'interactive',
    },
    {
      id: 'example-1',
      title: '重み付きグラフの定義',
      content: '重み付きグラフでは、各辺 e に重み w(e) が割り当てられます。\n\nG = (V, E, w) と書き、w: E → R は重み関数です。\n\n例：都市間の距離を表すグラフでは、w(東京, 大阪) = 500 (km) のようになります。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'example-2',
      title: '重みの解釈',
      content: '重みの意味は問題によって異なります：\n\n- 道路網：距離や所要時間\n- 通信ネットワーク：帯域幅や遅延\n- 経済モデル：取引コスト\n- ソーシャルネットワーク：関係の強さ\n\n負の重みを持つグラフも存在し、特別なアルゴリズムが必要です。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'predict',
      title: '確認クイズ',
      content: 'クイズに答えましょう。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'quiz',
      quiz: {
        question: '頂点A,B,Cがあり、辺の重みがw(A,B)=3, w(B,C)=4, w(A,C)=10のとき、AからCへの最短経路の重みは？',
        options: [
          { id: 'a', label: '10', correct: false },
          { id: 'b', label: '7', correct: true },
          { id: 'c', label: '3', correct: false },
          { id: 'd', label: '4', correct: false },
        ],
        explanation: 'A→B→Cの経路は重み3+4=7で、直接のA→Cの重み10より小さいため、最短経路の重みは7です。',
      },
    },
    {
      id: 'alternate',
      title: '重みなしグラフとの関係',
      content: '重みなしグラフは、すべての辺の重みが1の重み付きグラフと見なせます。\n\nこの場合、最短経路は「辺の本数が最小の経路」と同じです。\n\n重み付きグラフは重みなしグラフの一般化であり、より豊かな問題を扱えます。',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      interactive: false,
      nextCondition: 'click',
      stepType: 'explanation',
    },
    {
      id: 'summary',
      title: 'まとめ',
      content: '今回学んだポイント：\n\n1. 重み付きグラフは辺にコスト・距離などの数値を持つ\n2. 重みの意味は応用分野によって異なる\n3. 重みによって最短経路などの問題が豊かになる\n\n重みを変えて経路の変化を体験してみましょう！',
      sceneConfig: { showGrid: true, showAxes: true, cameraPosition: [0, 0, 5] },
      customScene: 'weighted-graph-summary',
      interactive: true,
      nextCondition: 'click',
      stepType: 'interactive',
    },
  ],
};
